// apps/web-core/src/lib/blueprint/blueprintTemplates.ts
/**
 * Authoritative Industry & Business Type Templates Catalog
 * Covers Healthcare, Real Estate, Restaurant, Retail, Agency, Construction, SaaS, etc.
 * Supports: Global Platform -> Industry Template -> Business Type -> Workspace Configuration
 */

import { BusinessTypeTemplate, IndustryKey } from './blueprintModel';

export const BUSINESS_TYPE_TEMPLATES: Record<string, BusinessTypeTemplate> = {
  // =========================================================================
  // HEALTHCARE - 1. DENTAL CLINIC
  // =========================================================================
  'dental_clinic': {
    id: 'dental_clinic',
    industry: 'HEALTHCARE',
    name: 'Dental Clinic & Orthodontics',
    slug: 'dental-clinic',
    description: 'Comprehensive dental operatory, appointments, periodontal charting, and patient care.',
    iconName: 'Stethoscope',
    coreServiceIds: [
      'srv_healthcare_patients',
      'srv_healthcare_appointments',
      'srv_invoices_billing',
      'srv_healthcare_digital_rx',
    ],
    recommendedServiceIds: [
      'srv_documents_esign',
      'srv_inventory_stock',
      'srv_hr_people',
      'srv_support_desk',
    ],
    optionalServiceIds: [
      'srv_marketing_studio',
      'srv_projects_tasks',
      'srv_dual_khata',
    ],
    advancedServiceIds: [
      'srv_universal_automation',
      'srv_customer_360',
    ],
    terminology: {
      contacts: 'Patients & Families',
      deals: 'Treatment Plans & Restorations',
      projects: 'Operatory Schedules',
      invoices: 'Dental Invoices & Co-Pays',
      products: 'Dental Supplies & Implants',
      tickets: 'Patient Inquiries & Triage',
      records: 'Dental Charts',
    },
    recordTypes: [
      {
        id: 'rec_patient',
        name: 'Dental Patient Chart',
        singular: 'Patient',
        plural: 'Patients',
        route: '/contacts',
        iconName: 'Users',
        description: 'Complete patient dental chart, medical alerts, insurance, and history',
        category: 'Clinical',
        views: ['TABLE', 'KANBAN', 'LIST'],
        fields: [
          { id: 'f_pat_id', name: 'patient_id', label: 'Patient Chart Number', key: 'chart_no', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_pat_name', name: 'full_name', label: 'Patient Full Name', key: 'full_name', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_pat_dob', name: 'dob', label: 'Date of Birth', key: 'dob', type: 'DATE', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_pat_phone', name: 'phone', label: 'SMS & WhatsApp Phone', key: 'phone', type: 'PHONE', required: true, searchable: true, filterable: false, reportable: false, visibility: 'ALWAYS' },
          { id: 'f_pat_ins', name: 'insurance_carrier', label: 'Dental Insurance Carrier', key: 'insurance_carrier', type: 'TEXT', required: false, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_pat_dentist', name: 'primary_dentist', label: 'Primary Attending Dentist', key: 'primary_dentist', type: 'DROPDOWN', options: ['Dr. Sarah Jenkins (Orthodontist)', 'Dr. Alan Rivera (Endodontist)', 'Dr. Michael Chen (General)'], required: false, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_active', name: 'Active Care', label: 'Active Care', color: '#10b981', order: 1, isDefault: true },
          { id: 'st_recall', name: 'Recall Due (6mo)', label: 'Recall Due', color: '#f59e0b', order: 2 },
          { id: 'st_inactive', name: 'Archived', label: 'Archived', color: '#64748b', order: 3, isTerminal: true },
        ],
        relationships: [
          { targetRecordId: 'rec_treatment_plan', relationshipType: 'ONE_TO_MANY', label: 'Treatment Plans', reverseLabel: 'Patient' },
          { targetRecordId: 'rec_invoice', relationshipType: 'ONE_TO_MANY', label: 'Dental Invoices', reverseLabel: 'Billed Patient' },
        ],
      },
      {
        id: 'rec_treatment_plan',
        name: 'Dental Treatment Plan',
        singular: 'Treatment Plan',
        plural: 'Treatment Plans',
        route: '/deals',
        iconName: 'Briefcase',
        description: 'Multi-phase tooth restoration, root canals, crown prep, and orthodontics',
        category: 'Clinical',
        views: ['KANBAN', 'TABLE'],
        fields: [
          { id: 'f_tp_title', name: 'plan_title', label: 'Procedure / Plan Title', key: 'plan_title', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_tp_cost', name: 'estimated_cost', label: 'Total Estimated Cost', key: 'estimated_cost', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_tp_tooth', name: 'tooth_numbers', label: 'Tooth Quadrant / Numbers', key: 'tooth_numbers', type: 'TEXT', required: false, searchable: true, filterable: true, reportable: false, visibility: 'ALWAYS' },
          { id: 'f_tp_copay', name: 'patient_copay', label: 'Patient Co-Pay ($)', key: 'patient_copay', type: 'CURRENCY', required: false, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_diag', name: 'Diagnosed', label: 'Diagnosed', color: '#38bdf8', order: 1, isDefault: true },
          { id: 'st_ins_pre', name: 'Insurance Pre-Auth', label: 'Pre-Auth Submitted', color: '#a855f7', order: 2 },
          { id: 'st_sched', name: 'Appointment Scheduled', label: 'Scheduled', color: '#f59e0b', order: 3 },
          { id: 'st_in_prog', name: 'In Treatment', label: 'In Progress', color: '#06b6d4', order: 4 },
          { id: 'st_comp', name: 'Completed & Restored', label: 'Completed', color: '#10b981', order: 5, isTerminal: true, outcome: 'SUCCESS' },
        ],
        relationships: [],
      },
    ],
    dashboardWidgets: [
      { id: 'w_today_chairs', title: "Today's Chair Consultations", type: 'KPI', size: 'SMALL', metricValue: '34 visits', metricDelta: '96% on-time', metricSubtext: '4 Operatories active', iconName: 'Clock' },
      { id: 'w_active_treatments', title: 'Active Dental Treatment Plans', type: 'KPI', size: 'SMALL', metricValue: '$48,200', metricDelta: '22 cases', metricSubtext: 'Orthodontics & Implants', iconName: 'Briefcase' },
      { id: 'w_unpaid_copays', title: 'Outstanding Patient Co-Pays', type: 'KPI', size: 'SMALL', metricValue: '$6,450', metricDelta: '8 overdue', metricSubtext: 'Average collection 14 days', iconName: 'Receipt' },
      { id: 'w_recall_rate', title: '6-Month Hygiene Recall Rate', type: 'KPI', size: 'SMALL', metricValue: '82.4%', metricDelta: '+4.1%', metricSubtext: 'Above national benchmark', iconName: 'CheckCircle2' },
      { id: 'w_tp_pipeline', title: 'Treatment Plan Pipeline', type: 'PIPELINE', size: 'LARGE', iconName: 'Briefcase' },
      { id: 'w_recent_patients', title: 'Upcoming Patient Appointments', type: 'TABLE', size: 'FULL', iconName: 'Users' },
    ],
    kpis: [
      { id: 'kpi_patient_vol', name: 'Monthly Patient Volume', source: 'srv_healthcare_patients', calculation: 'COUNT', timePeriod: 'MONTH', displayType: 'NUMBER', currentValue: '384', deltaText: '+12.5%', subtext: 'Trailing 30 days', iconName: 'Users' },
      { id: 'kpi_chair_rev', name: 'Operatory Chair Revenue', source: 'srv_invoices_billing', calculation: 'SUM', timePeriod: 'MONTH', displayType: 'CURRENCY', currentValue: '$94,200', deltaText: '+8.3%', subtext: 'Across 4 operatories', iconName: 'DollarSign' },
    ],
    quickActions: [
      { id: 'qa_add_patient', label: 'Add Patient Chart', actionType: 'NAVIGATE', href: '/contacts?action=new', iconName: 'Plus', primary: true },
      { id: 'qa_book_chair', label: 'Book Operatory Chair', actionType: 'NAVIGATE', href: '/industry/hospital?action=book', iconName: 'Clock' },
      { id: 'qa_create_tx', label: 'Create Treatment Plan', actionType: 'NAVIGATE', href: '/deals?action=new', iconName: 'Briefcase' },
      { id: 'qa_dental_invoice', label: 'Generate Dental Bill', actionType: 'NAVIGATE', href: '/invoices?action=new', iconName: 'Receipt' },
    ],
    workflowTemplates: [
      { id: 'wf_dent_sms', name: '48-Hour SMS Appointment Reminder', category: 'Patient Comms', trigger: '48h Prior to Appointment', actions: ['Send SMS', 'Send WhatsApp with Google Maps Pin'], description: 'Reduces no-shows by 40%', enabledByDefault: true, requiredServiceIds: ['srv_healthcare_appointments'] },
      { id: 'wf_hygiene_recall', name: '6-Month Preventative Recall Notice', category: 'Retention', trigger: '6 Months After Last Cleaning', actions: ['Send WhatsApp Recall Alert', 'Create Recall Task'], description: 'Automatically nurtures patients for bi-annual cleanings', enabledByDefault: true, requiredServiceIds: ['srv_healthcare_patients'] },
    ],
    documentTemplates: [
      { id: 'doc_consent', name: 'Dental Surgical Consent Form', category: 'Clinical', fileFormat: 'ESIGN', linkedRecordId: 'rec_patient', description: 'Informed consent for extractions, implants, and nitrous sedation', fieldsIncluded: ['patient_name', 'procedure', 'signature', 'date'] },
      { id: 'doc_treatment_estimate', name: 'Itemized Treatment Cost Estimate', category: 'Financial', fileFormat: 'PDF', linkedRecordId: 'rec_treatment_plan', description: 'Itemized ADA codes, insurance coverage, and patient share', fieldsIncluded: ['patient_name', 'ada_codes', 'insurance_est', 'total'] },
    ],
    reports: [
      { id: 'rep_operatory_util', title: 'Operatory Chair Utilization & Downtime', category: 'Operations', dataSource: 'srv_healthcare_appointments', chartType: 'BAR', description: 'Hours utilized per dental chair per day', timeframe: 'Last 30 Days' },
      { id: 'rep_co_pay_recovery', title: 'Insurance A/R & Co-Pay Recovery Report', category: 'Finance', dataSource: 'srv_invoices_billing', chartType: 'TABLE', description: 'Aging buckets (0-30, 31-60, 60+ days)', timeframe: 'All Time' },
    ],
    roles: [
      { id: 'role_dentist', name: 'Doctor / Dentist', label: 'Dentist & Specialist', description: 'Full access to clinical charts, treatment plans, and digital prescriptions', permissions: ['PATIENTS_READ', 'PATIENTS_WRITE', 'CLINICAL_WRITE', 'RX_WRITE'], accessibleSections: ['Clinical Operations', 'Patients', 'Appointments'], quickActionIds: ['qa_book_chair', 'qa_create_tx'], defaultDashboardWidgetIds: ['w_today_chairs', 'w_active_treatments'] },
      { id: 'role_hygienist', name: 'Dental Hygienist', label: 'Hygienist', description: 'Periodontal notes, prophylaxis logs, and appointments', permissions: ['PATIENTS_READ', 'APPOINTMENTS_WRITE'], accessibleSections: ['Clinical Operations', 'Appointments'], quickActionIds: ['qa_book_chair'], defaultDashboardWidgetIds: ['w_today_chairs'] },
      { id: 'role_front_desk', name: 'Front Desk & Receptionist', label: 'Front Desk Coordinator', description: 'Check-in, scheduling, payments, and patient communications', permissions: ['PATIENTS_READ', 'PATIENTS_WRITE', 'INVOICES_WRITE', 'APPOINTMENTS_WRITE'], accessibleSections: ['Patients', 'Appointments', 'Billing'], quickActionIds: ['qa_add_patient', 'qa_book_chair', 'qa_dental_invoice'], defaultDashboardWidgetIds: ['w_today_chairs', 'w_unpaid_copays'] },
    ],
    navigation: [
      {
        id: 'sec_dental_ops',
        sectionTitle: 'Dental Operatory & Clinical',
        iconName: 'Stethoscope',
        order: 1,
        items: [
          { id: 'nav_chairs', label: 'Operatory Chair Schedule', href: '/industry/hospital#appointments', iconName: 'Clock', badge: 'Chairs' },
          { id: 'nav_patients', label: 'Patient Charts & EHR', href: '/contacts', iconName: 'Users', badge: 'Charts' },
          { id: 'nav_treatment_plans', label: 'Treatment Plans & Cases', href: '/deals', iconName: 'Briefcase', badge: 'Plans' },
          { id: 'nav_prescriptions', label: 'Dental Rx & Labs', href: '/industry/hospital#rx', iconName: 'HeartPulse' },
        ],
      },
      {
        id: 'sec_dental_billing',
        sectionTitle: 'Billing & Insurance',
        iconName: 'Receipt',
        order: 2,
        items: [
          { id: 'nav_invoices', label: 'Patient Statements & Invoices', href: '/invoices', iconName: 'Receipt' },
          { id: 'nav_claims', label: 'Insurance Pre-Auth & Claims', href: '/invoices#claims', iconName: 'Shield' },
          { id: 'nav_payment_links', label: 'SMS Co-Pay Instant Links', href: '/payment-links', iconName: 'Zap' },
        ],
      },
    ],
    theme: {
      primaryColor: '#0d9488',
      accentColor: '#14b8a6',
      badgeStyle: 'bg-teal-500/15 text-teal-400 border border-teal-500/30',
    },
  },

  // =========================================================================
  // HEALTHCARE - 2. PRIVATE CLINIC
  // =========================================================================
  'private_clinic': {
    id: 'private_clinic',
    industry: 'HEALTHCARE',
    name: 'Private Specialist Clinic',
    slug: 'private-clinic',
    description: 'Outpatient consultation rooms, physician queues, e-prescriptions, and lab pathology.',
    iconName: 'Stethoscope',
    coreServiceIds: [
      'srv_healthcare_patients',
      'srv_healthcare_appointments',
      'srv_healthcare_digital_rx',
      'srv_invoices_billing',
    ],
    recommendedServiceIds: [
      'srv_documents_esign',
      'srv_inventory_stock',
      'srv_support_desk',
      'srv_universal_automation',
    ],
    optionalServiceIds: ['srv_hr_people', 'srv_marketing_studio'],
    advancedServiceIds: ['srv_customer_360'],
    terminology: {
      contacts: 'Patients & Consultations',
      deals: 'Specialist Care Episodes',
      projects: 'Clinic Rosters',
      invoices: 'Consultation Fees & Invoices',
      products: 'Medicines & Lab Packages',
      tickets: 'Telemedicine & Triage',
      records: 'Patient Files',
    },
    recordTypes: [],
    dashboardWidgets: [
      { id: 'w_clinic_visits', title: "Today's Outpatient Visits", type: 'KPI', size: 'SMALL', metricValue: '48 patients', metricDelta: '12 waiting', metricSubtext: 'Avg wait: 11 mins', iconName: 'Clock' },
      { id: 'w_rx_dispensed', title: 'Digital Rx Issued', type: 'KPI', size: 'SMALL', metricValue: '39 Rx', metricDelta: '100% digital', metricSubtext: 'Integrated pharmacy sync', iconName: 'HeartPulse' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_add_patient_pc', label: 'Register Patient', actionType: 'NAVIGATE', href: '/contacts?action=new', iconName: 'Plus', primary: true },
      { id: 'qa_book_appt_pc', label: 'Schedule Consultation', actionType: 'NAVIGATE', href: '/industry/hospital?action=book', iconName: 'Clock' },
    ],
    workflowTemplates: [],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#0284c7', accentColor: '#38bdf8', badgeStyle: 'bg-sky-500/15 text-sky-400 border border-sky-500/30' },
  },

  // =========================================================================
  // HEALTHCARE - 3. GENERAL HOSPITAL & MEDICAL CENTER
  // =========================================================================
  'hospital_center': {
    id: 'hospital_center',
    industry: 'HEALTHCARE',
    name: 'General Hospital & Medical Center',
    slug: 'hospital-center',
    description: 'Inpatient wards, bed census management, emergency triage, physician on-call rosters, and digital Rx.',
    iconName: 'Building2',
    coreServiceIds: [
      'srv_healthcare_patients',
      'srv_healthcare_appointments',
      'srv_healthcare_digital_rx',
      'srv_invoices_billing',
      'srv_inventory_stock',
    ],
    recommendedServiceIds: [
      'srv_documents_esign',
      'srv_support_desk',
      'srv_hr_people',
      'srv_universal_automation',
      'srv_customer_360',
    ],
    optionalServiceIds: ['srv_marketing_studio', 'srv_projects_tasks', 'srv_dual_khata'],
    advancedServiceIds: ['srv_neural_ocr'],
    terminology: {
      contacts: 'Patients & Admissions',
      deals: 'Clinical Episodes & Surgeries',
      projects: 'Hospital Operations & Wings',
      invoices: 'Hospital Invoices & Insurance Claims',
      products: 'Pharmaceuticals & Medical Supplies',
      tickets: 'Nursing Calls & Patient Requests',
      records: 'Inpatient Records',
    },
    recordTypes: [
      {
        id: 'rec_admission',
        name: 'Inpatient Admission & Bed Census',
        singular: 'Admission',
        plural: 'Admissions',
        route: '/industry/hospital',
        iconName: 'Building2',
        description: 'Track inpatient hospital admissions, assigned ward/bed, attending physician, and triage status.',
        category: 'Clinical Operations',
        views: ['TABLE', 'KANBAN'],
        fields: [
          { id: 'f_adm_no', name: 'admission_no', label: 'Admission Code', key: 'admission_no', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_adm_pat', name: 'patient_name', label: 'Patient Name', key: 'patient_name', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_adm_ward', name: 'ward_wing', label: 'Ward / Unit', key: 'ward_wing', type: 'DROPDOWN', options: ['Emergency Triage', 'Intensive Care Unit (ICU)', 'Surgical Ward A', 'Pediatrics Wing', 'Maternity Suite', 'General Ward B'], required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_adm_bed', name: 'bed_id', label: 'Bed Number', key: 'bed_id', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_adm_doctor', name: 'attending_physician', label: 'Attending Specialist', key: 'attending_physician', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_adm_triage', name: 'triage_priority', label: 'Triage Severity', key: 'triage_priority', type: 'DROPDOWN', options: ['P1 - Resuscitation (Immediate)', 'P2 - Emergent (<15m)', 'P3 - Urgent (<30m)', 'P4 - Semi-Urgent', 'P5 - Non-Urgent'], required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_triage', name: 'Triage Queue', label: 'Triage Queue', color: '#ef4444', order: 1, isDefault: true },
          { id: 'st_admitted', name: 'Admitted in Ward', label: 'Admitted', color: '#38bdf8', order: 2 },
          { id: 'st_icu', name: 'ICU Critical Care', label: 'In ICU', color: '#f59e0b', order: 3 },
          { id: 'st_surgery', name: 'Operating Theatre', label: 'In Surgery', color: '#a855f7', order: 4 },
          { id: 'st_discharged', name: 'Discharged', label: 'Discharged', color: '#10b981', order: 5, isTerminal: true, outcome: 'SUCCESS' },
        ],
        relationships: [],
      },
    ],
    dashboardWidgets: [
      { id: 'w_bed_occupancy', title: 'Hospital Bed Occupancy', type: 'KPI', size: 'SMALL', metricValue: '84.2%', metricDelta: '138 / 165 beds occupied', metricSubtext: 'ICU Capacity at 92%', iconName: 'Building2' },
      { id: 'w_er_wait', title: 'Emergency Triage Avg Wait Time', type: 'KPI', size: 'SMALL', metricValue: '18 mins', metricDelta: '-6 mins vs yesterday', metricSubtext: '5 Physicians on duty', iconName: 'Clock' },
      { id: 'w_active_surgeries', title: 'Active OR Surgical Cases', type: 'KPI', size: 'SMALL', metricValue: '6 Theatres', metricDelta: '12 completed today', metricSubtext: 'Sterile turnover on schedule', iconName: 'Activity' },
      { id: 'w_pharm_claims', title: 'Hospital & Insurance Revenue', type: 'KPI', size: 'SMALL', metricValue: '$342k', metricDelta: 'Trailing 7 days', metricSubtext: 'Claims recovery at 97.4%', iconName: 'Receipt' },
    ],
    kpis: [
      { id: 'kpi_hosp_census', name: 'Current Inpatient Census', source: 'srv_healthcare_patients', calculation: 'COUNT', timePeriod: 'TODAY', displayType: 'NUMBER', currentValue: '138', deltaText: '+4 today', subtext: 'Total admitted', iconName: 'Users' },
    ],
    quickActions: [
      { id: 'qa_admit_patient', label: 'Emergency Patient Admission', actionType: 'NAVIGATE', href: '/industry/hospital?action=admit', iconName: 'Plus', primary: true },
      { id: 'qa_issue_rx', label: 'Issue Digital Rx', actionType: 'NAVIGATE', href: '/industry/hospital?action=rx', iconName: 'HeartPulse' },
    ],
    workflowTemplates: [
      { id: 'wf_hosp_critical_alert', name: 'Critical Vitals Automated Alert', category: 'Patient Safety', trigger: 'Abnormal Vitals Logged', actions: ['Page Attending Specialist', 'Notify Head Nurse'], description: 'Emergency notification on severe patient vitals fluctuation', enabledByDefault: true, requiredServiceIds: ['srv_healthcare_patients'] },
    ],
    documentTemplates: [
      { id: 'doc_discharge_summary', name: 'Clinical Discharge Summary', category: 'Clinical', fileFormat: 'PDF', linkedRecordId: 'rec_admission', description: 'Itemized discharge diagnosis, medication regimen, and follow-up plan', fieldsIncluded: ['patient_name', 'discharge_date', 'diagnoses', 'prescriptions'] },
    ],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#0ea5e9', accentColor: '#38bdf8', badgeStyle: 'bg-sky-500/15 text-sky-400 border border-sky-500/30' },
  },

  // =========================================================================
  // REAL ESTATE - 3. PROPERTY BROKERAGE / AGENCY
  // =========================================================================
  'realestate_brokerage': {
    id: 'realestate_brokerage',
    industry: 'REAL_ESTATE',
    name: 'Real Estate Agency & Brokerage',
    slug: 'realestate-brokerage',
    description: 'Agent commissions, MLS listings, escrow sales pipelines, buyers, and sellers.',
    iconName: 'Home',
    coreServiceIds: [
      'srv_realestate_listings',
      'srv_deals_pipeline',
      'srv_contacts',
      'srv_documents_esign',
      'srv_invoices_billing',
    ],
    recommendedServiceIds: [
      'srv_b2b_prospector',
      'srv_marketing_studio',
      'srv_universal_automation',
      'srv_dual_khata',
    ],
    optionalServiceIds: ['srv_hr_people', 'srv_projects_tasks'],
    advancedServiceIds: ['srv_customer_360', 'srv_neural_ocr'],
    terminology: {
      contacts: 'Buyers, Sellers & Investors',
      deals: 'Property Deals & Escrow',
      projects: 'Open Houses & Showings',
      invoices: 'Commission Settlements',
      products: 'MLS Property Listings',
      tickets: 'Property Inquiries',
      records: 'Property Files',
    },
    recordTypes: [
      {
        id: 'rec_property',
        name: 'MLS Property Listing',
        singular: 'Property',
        plural: 'Properties',
        route: '/price-books',
        iconName: 'Home',
        description: 'Residential and commercial real estate inventory',
        category: 'Properties',
        views: ['TABLE', 'KANBAN'],
        fields: [
          { id: 'f_prop_title', name: 'title', label: 'Listing Title', key: 'title', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_prop_type', name: 'property_type', label: 'Property Type', key: 'property_type', type: 'DROPDOWN', options: ['Single Family Home', 'Luxury Condominium', 'Commercial Office', 'Townhouse', 'Land Plot'], required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_prop_price', name: 'asking_price', label: 'Asking Price ($)', key: 'asking_price', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_prop_beds', name: 'bedrooms', label: 'Bedrooms', key: 'bedrooms', type: 'NUMBER', required: false, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_prop_location', name: 'location_address', label: 'Full Street Address', key: 'location_address', type: 'ADDRESS', required: true, searchable: true, filterable: true, reportable: false, visibility: 'ALWAYS' },
          { id: 'f_prop_agent', name: 'listing_agent', label: 'Listing Broker / Agent', key: 'listing_agent', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_pre_mls', name: 'Pre-Market Pocket', label: 'Pre-Market', color: '#a855f7', order: 1, isDefault: true },
          { id: 'st_active_mls', name: 'Active on MLS', label: 'Active MLS', color: '#10b981', order: 2 },
          { id: 'st_pending_contract', name: 'Under Contract (Pending)', label: 'Pending Escrow', color: '#f59e0b', order: 3 },
          { id: 'st_sold', name: 'Sold & Closed', label: 'Sold', color: '#06b6d4', order: 4, isTerminal: true, outcome: 'SUCCESS' },
          { id: 'st_withdrawn', name: 'Withdrawn / Delisted', label: 'Withdrawn', color: '#64748b', order: 5, isTerminal: true },
        ],
        relationships: [],
      },
    ],
    dashboardWidgets: [
      { id: 'w_active_listings', title: 'Active MLS Listings Value', type: 'KPI', size: 'SMALL', metricValue: '$24.8M', metricDelta: '34 properties', metricSubtext: 'Average DOM: 24 days', iconName: 'Home' },
      { id: 'w_escrow_pipe', title: 'Deals in Escrow & Closing', type: 'KPI', size: 'SMALL', metricValue: '$6.4M', metricDelta: '7 pending', metricSubtext: 'Est. commissions $192k', iconName: 'Briefcase' },
      { id: 'w_new_leads', title: 'New Buyer & Seller Inquiries', type: 'KPI', size: 'SMALL', metricValue: '128', metricDelta: '+18% this wk', metricSubtext: 'Zillow & Portal Sync', iconName: 'Users' },
      { id: 'w_agent_commissions', title: 'Brokerage Gross Commissions (YTD)', type: 'KPI', size: 'SMALL', metricValue: '$682k', metricDelta: '+24.2%', metricSubtext: 'Paid out across 14 agents', iconName: 'DollarSign' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_add_listing', label: 'Create MLS Listing', actionType: 'NAVIGATE', href: '/price-books?action=new', iconName: 'Home', primary: true },
      { id: 'qa_add_buyer', label: 'Add Qualified Buyer', actionType: 'NAVIGATE', href: '/contacts?action=new', iconName: 'Users' },
      { id: 'qa_open_escrow', label: 'Open Escrow Deal', actionType: 'NAVIGATE', href: '/deals?action=new', iconName: 'Briefcase' },
      { id: 'qa_draft_offer', label: 'Draft Purchase Agreement', actionType: 'NAVIGATE', href: '/documents', iconName: 'FileSignature' },
    ],
    workflowTemplates: [
      { id: 'wf_new_inquiry_sms', name: 'Instant 2-Minute Lead Follow-Up', category: 'Lead Response', trigger: 'When Web Lead Inquires', actions: ['Send Automated SMS', 'Route to On-Duty Agent'], description: 'Fast automated text to lock in buyers', enabledByDefault: true, requiredServiceIds: ['srv_contacts'] },
    ],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [
      {
        id: 'sec_realestate_ops',
        sectionTitle: 'Real Estate & Property Hub',
        iconName: 'Home',
        order: 1,
        items: [
          { id: 'nav_prop_cmd', label: 'Property Command Center', href: '/industry/realestate', iconName: 'Home', badge: 'MLS' },
          { id: 'nav_prop_listings', label: 'Property Listings & Portfolio', href: '/price-books', iconName: 'Layers', badge: 'Portfolio' },
          { id: 'nav_prop_escrow', label: 'Property Sales & Escrow', href: '/deals', iconName: 'Briefcase', badge: 'Escrow' },
          { id: 'nav_prop_clients', label: 'Buyers, Sellers & Tenants', href: '/contacts', iconName: 'Users', badge: 'CRM' },
        ],
      },
      {
        id: 'sec_realestate_docs',
        sectionTitle: 'Contracts & Closings',
        iconName: 'FileSignature',
        order: 2,
        items: [
          { id: 'nav_prop_deeds', label: 'Purchase Agreements & Deeds', href: '/e-signatures', iconName: 'FileSignature' },
          { id: 'nav_prop_quotes', label: 'Buyer Proposals & Quotes', href: '/quotes', iconName: 'FileBadge' },
          { id: 'nav_prop_vault', label: 'Floor Plans & Media Vault', href: '/documents', iconName: 'Folder' },
        ],
      },
    ],
    theme: { primaryColor: '#f59e0b', accentColor: '#fbbf24', badgeStyle: 'bg-amber-500/15 text-amber-400 border border-amber-500/30' },
  },

  // =========================================================================
  // REAL ESTATE - 4. PROPERTY MANAGEMENT & RENTALS
  // =========================================================================
  'property_management': {
    id: 'property_management',
    industry: 'REAL_ESTATE',
    name: 'Property Management & Rentals',
    slug: 'property-management',
    description: 'Residential & commercial rent rolls, tenant leases, maintenance dispatch, and automated late fees.',
    iconName: 'Building',
    coreServiceIds: [
      'srv_realestate_rentals',
      'srv_invoices_billing',
      'srv_contacts',
      'srv_documents_esign',
      'srv_support_desk',
    ],
    recommendedServiceIds: [
      'srv_projects_tasks',
      'srv_dual_khata',
      'srv_universal_automation',
      'srv_inventory_stock',
    ],
    optionalServiceIds: ['srv_marketing_studio', 'srv_hr_people'],
    advancedServiceIds: ['srv_customer_360'],
    terminology: {
      contacts: 'Tenants & Landlords',
      deals: 'Lease Renewals & Move-Ins',
      projects: 'Unit Turns & Renovations',
      invoices: 'Monthly Rent Invoices & CAM Charges',
      products: 'Rental Units & Amenities',
      tickets: 'Maintenance Work Orders',
      records: 'Tenant Files',
    },
    recordTypes: [
      {
        id: 'rec_lease',
        name: 'Tenant Lease Contract',
        singular: 'Lease',
        plural: 'Leases',
        route: '/deals',
        iconName: 'FileText',
        description: 'Manage active tenant leases, monthly base rent, security deposits, and expiration dates.',
        category: 'Leasing & Occupancy',
        views: ['TABLE', 'KANBAN'],
        fields: [
          { id: 'f_l_unit', name: 'unit_number', label: 'Unit Number / Suite', key: 'unit_number', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_l_tenant', name: 'tenant_name', label: 'Primary Tenant Name', key: 'tenant_name', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_l_rent', name: 'monthly_rent', label: 'Monthly Rent ($)', key: 'monthly_rent', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_l_deposit', name: 'security_deposit', label: 'Security Deposit ($)', key: 'security_deposit', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_l_exp', name: 'lease_end', label: 'Lease Expiration Date', key: 'lease_end', type: 'DATE', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_l_active', name: 'Current & Active', label: 'Active Lease', color: '#10b981', order: 1, isDefault: true },
          { id: 'st_l_notice', name: 'Notice Given', label: 'Notice Given', color: '#f59e0b', order: 2 },
          { id: 'st_l_expired', name: 'Lease Expired', label: 'Expired', color: '#64748b', order: 3, isTerminal: true },
        ],
        relationships: [],
      },
    ],
    dashboardWidgets: [
      { id: 'w_occupancy_rate', title: 'Portfolio Occupancy Rate', type: 'KPI', size: 'SMALL', metricValue: '96.4%', metricDelta: '142 / 148 units leased', metricSubtext: 'Average rent: $2,180/mo', iconName: 'Building' },
      { id: 'w_rent_collected', title: 'Current Month Rent Collected', type: 'KPI', size: 'SMALL', metricValue: '$309k', metricDelta: '97.1% on-time', metricSubtext: '4 late notices queued', iconName: 'DollarSign' },
      { id: 'w_active_tickets', title: 'Open Maintenance Dispatches', type: 'KPI', size: 'SMALL', metricValue: '7 open', metricDelta: '2 HVAC priority', metricSubtext: 'Avg resolution: 18 hrs', iconName: 'Clock' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_add_lease', label: 'Sign New Lease', actionType: 'NAVIGATE', href: '/deals?action=new', iconName: 'Plus', primary: true },
      { id: 'qa_dispatch_maint', label: 'Dispatch Work Order', actionType: 'NAVIGATE', href: '/tickets?action=new', iconName: 'Tool' },
    ],
    workflowTemplates: [],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#d97706', accentColor: '#f59e0b', badgeStyle: 'bg-amber-600/15 text-amber-400 border border-amber-600/30' },
  },

  // =========================================================================
  // RESTAURANT - 4. FINE DINING / CAFE / CLOUD KITCHEN
  // =========================================================================
  'restaurant_cafe': {
    id: 'restaurant_cafe',
    industry: 'HOSPITALITY',
    name: 'Restaurant, Cafe & Cloud Kitchen',
    slug: 'restaurant-cafe',
    description: 'Floor plan table management, kitchen display system (KDS), table QR orders, and par stock.',
    iconName: 'UtensilsCrossed',
    coreServiceIds: [
      'srv_restaurant_floor_kds',
      'srv_invoices_billing',
      'srv_inventory_stock',
      'srv_contacts',
    ],
    recommendedServiceIds: [
      'srv_payment_links_pos',
      'srv_dual_khata',
      'srv_universal_automation',
    ],
    optionalServiceIds: ['srv_hr_people', 'srv_marketing_studio'],
    advancedServiceIds: ['srv_neural_ocr'],
    terminology: {
      contacts: 'Guests & Diners',
      deals: 'Private Dining & Catering',
      projects: 'Kitchen Stations',
      invoices: 'Dining Bills & Receipts',
      products: 'Food & Beverage Menu',
      tickets: 'Guest Inquiries & Feedback',
      records: 'Order Tickets',
    },
    recordTypes: [
      {
        id: 'rec_table',
        name: 'Dining Floor Table',
        singular: 'Table',
        plural: 'Tables',
        route: '/industry/restaurant',
        iconName: 'UtensilsCrossed',
        description: 'Restaurant dining floor tables, current covers, seating status, and running tab.',
        category: 'Dining Floor',
        views: ['TABLE', 'KANBAN'],
        fields: [
          { id: 'f_tbl_no', name: 'table_number', label: 'Table Code', key: 'table_number', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_tbl_sec', name: 'section', label: 'Dining Area', key: 'section', type: 'DROPDOWN', options: ['Main Dining Hall', 'Patio Terrace', 'Private Dining Room', 'Bar Counter', 'Mezzanine'], required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_tbl_cap', name: 'capacity', label: 'Seat Capacity', key: 'capacity', type: 'NUMBER', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_tbl_server', name: 'server_name', label: 'Assigned Waiter / Server', key: 'server_name', type: 'TEXT', required: false, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_tbl_bill', name: 'current_bill', label: 'Active Tab Total ($)', key: 'current_bill', type: 'CURRENCY', required: false, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_t_vacant', name: 'Vacant / Clean', label: 'Available', color: '#10b981', order: 1, isDefault: true },
          { id: 'st_t_seated', name: 'Guests Seated', label: 'Seated', color: '#38bdf8', order: 2 },
          { id: 'st_t_dining', name: 'Food Served', label: 'Dining', color: '#f59e0b', order: 3 },
          { id: 'st_t_bill', name: 'Check Requested', label: 'Bill Out', color: '#ec4899', order: 4 },
          { id: 'st_t_bussing', name: 'Needs Bussing', label: 'Bussing', color: '#64748b', order: 5 },
        ],
        relationships: [],
      },
    ],
    dashboardWidgets: [
      { id: 'w_today_covers', title: "Today's Table Covers & Diners", type: 'KPI', size: 'SMALL', metricValue: '184 diners', metricDelta: '42 tables seated', metricSubtext: 'Avg ticket: $54.20', iconName: 'UtensilsCrossed' },
      { id: 'w_kds_speed', title: 'Average Kitchen Ticket Time', type: 'KPI', size: 'SMALL', metricValue: '13.2 mins', metricDelta: '-2.4 mins', metricSubtext: 'Target under 16 mins', iconName: 'Clock' },
      { id: 'w_sales_today', title: "Today's Gross F&B Sales", type: 'KPI', size: 'SMALL', metricValue: '$8,420', metricDelta: '+14% vs yesterday', metricSubtext: 'Live register tally', iconName: 'DollarSign' },
      { id: 'w_par_alerts', title: 'Low Stock Par Level Alerts', type: 'KPI', size: 'SMALL', metricValue: '3 items', metricDelta: 'Urgent', metricSubtext: 'Ribeye & Truffle Oil', iconName: 'ShoppingBag' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_new_order_rest', label: 'Seat Table & Order', actionType: 'NAVIGATE', href: '/industry/restaurant', iconName: 'Plus', primary: true },
      { id: 'qa_kds_view', label: 'Open Live KDS', actionType: 'NAVIGATE', href: '/industry/restaurant#kds', iconName: 'ClipboardList' },
    ],
    workflowTemplates: [
      { id: 'wf_vip_seating', name: 'VIP Guest Host Alert', category: 'Guest Experience', trigger: 'VIP Guest Seated', actions: ['Notify Floor Manager', 'Complimentary Chef Greeting'], description: 'Ensures executive treatment for VIP patrons', enabledByDefault: true, requiredServiceIds: ['srv_restaurant_floor_kds'] },
    ],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#f97316', accentColor: '#fb923c', badgeStyle: 'bg-orange-500/15 text-orange-400 border border-orange-500/30' },
  },

  // =========================================================================
  // RETAIL - 5. SUPERMARKET / FASHION / PHARMACY STORE
  // =========================================================================
  'retail_store': {
    id: 'retail_store',
    industry: 'RETAIL',
    name: 'Retail Storefront & Supermarket',
    slug: 'retail-store',
    description: 'Barcode checkout POS, customer khata credit book, SKU stock matrix, and thermal receipts.',
    iconName: 'ShoppingBag',
    coreServiceIds: [
      'srv_retail_pos_cashier',
      'srv_inventory_stock',
      'srv_invoices_billing',
      'srv_contacts',
      'srv_retail_khata_credit',
    ],
    recommendedServiceIds: [
      'srv_dual_khata',
      'srv_payment_links_pos',
      'srv_universal_automation',
    ],
    optionalServiceIds: ['srv_hr_people', 'srv_marketing_studio'],
    advancedServiceIds: ['srv_customer_360'],
    terminology: {
      contacts: 'Loyal Shoppers & Khata Customers',
      deals: 'Wholesale Orders',
      projects: 'Inventory Stock Audits',
      invoices: 'Cashier Receipts & Z-Reports',
      products: 'SKU Products & Barcodes',
      tickets: 'Returns & Exchanges',
      records: 'Store Transactions',
    },
    recordTypes: [
      {
        id: 'rec_khata_book',
        name: 'Customer Khata Credit Ledger',
        singular: 'Khata Account',
        plural: 'Khata Accounts',
        route: '/contacts',
        iconName: 'BookOpen',
        description: 'Track neighborhood customer informal credit, outstanding store balances, and WhatsApp payment reminders.',
        category: 'Customer Accounts',
        views: ['TABLE', 'KANBAN'],
        fields: [
          { id: 'f_kh_name', name: 'customer_name', label: 'Customer Name', key: 'customer_name', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_kh_phone', name: 'phone', label: 'WhatsApp Phone Number', key: 'phone', type: 'PHONE', required: true, searchable: true, filterable: false, reportable: false, visibility: 'ALWAYS' },
          { id: 'f_kh_bal', name: 'balance_due', label: 'Credit Balance Due ($)', key: 'balance_due', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_kh_limit', name: 'credit_limit', label: 'Max Approved Credit Limit ($)', key: 'credit_limit', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_kh_active', name: 'Current & In Good Standing', label: 'Good Standing', color: '#10b981', order: 1, isDefault: true },
          { id: 'st_kh_overdue', name: 'Credit Overdue', label: 'Overdue', color: '#f59e0b', order: 2 },
          { id: 'st_kh_frozen', name: 'Credit Frozen', label: 'Frozen', color: '#ef4444', order: 3 },
        ],
        relationships: [],
      },
    ],
    dashboardWidgets: [
      { id: 'w_pos_gross', title: "Today's Store Gross Sales", type: 'KPI', size: 'SMALL', metricValue: '$14,890', metricDelta: '420 receipts', metricSubtext: 'Cash: $6.2k · Card: $8.6k', iconName: 'DollarSign' },
      { id: 'w_khata_receivables', title: 'Customer Khata Credit Dues', type: 'KPI', size: 'SMALL', metricValue: '$3,420', metricDelta: '14 customers', metricSubtext: 'Pending local recovery', iconName: 'Users' },
      { id: 'w_skus_low', title: 'Low Stock SKU Warning', type: 'KPI', size: 'SMALL', metricValue: '12 SKUs', metricDelta: 'Reorder triggered', metricSubtext: 'Auto PO generated', iconName: 'Layers' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_pos_ring', label: 'Open POS Register', actionType: 'NAVIGATE', href: '/industry/retail', iconName: 'ShoppingBag', primary: true },
      { id: 'qa_khata_credit', label: 'Log Customer Khata Credit', actionType: 'NAVIGATE', href: '/contacts', iconName: 'Plus' },
    ],
    workflowTemplates: [
      { id: 'wf_khata_reminder', name: 'Khata Weekly WhatsApp Balance Ping', category: 'Credit Recovery', trigger: 'Every Sunday 10am', actions: ['Send WhatsApp Balance Statement', 'Include Instant UPI/Card Link'], description: 'Automates customer credit settlements', enabledByDefault: true, requiredServiceIds: ['srv_retail_khata_credit'] },
    ],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#ec4899', accentColor: '#f472b6', badgeStyle: 'bg-pink-500/15 text-pink-400 border border-pink-500/30' },
  },

  // =========================================================================
  // AGENCY - 6. CREATIVE / SOFTWARE / MARKETING AGENCY
  // =========================================================================
  'creative_agency': {
    id: 'creative_agency',
    industry: 'AGENCY',
    name: 'Creative Agency & Consultancy',
    slug: 'creative-agency',
    description: 'Client retainers, rate cards, pitch proposals, deliverable milestones, and SOW e-signatures.',
    iconName: 'Palette',
    coreServiceIds: [
      'srv_contacts',
      'srv_deals_pipeline',
      'srv_projects_tasks',
      'srv_invoices_billing',
      'srv_documents_esign',
      'srv_cpq_quotes',
    ],
    recommendedServiceIds: [
      'srv_marketing_studio',
      'srv_support_desk',
      'srv_dual_khata',
      'srv_universal_automation',
    ],
    optionalServiceIds: ['srv_hr_people', 'srv_b2b_prospector'],
    advancedServiceIds: ['srv_customer_360'],
    terminology: {
      contacts: 'Client Accounts & Stakeholders',
      deals: 'Pitch Proposals & SOWs',
      projects: 'Client Sprints & Deliverables',
      invoices: 'Milestone & Retainer Bills',
      products: 'Agency Rate Cards',
      tickets: 'Client Feedback & Revisions',
      records: 'Client Files',
    },
    recordTypes: [
      {
        id: 'rec_deliverable',
        name: 'Client Project Deliverable',
        singular: 'Deliverable',
        plural: 'Deliverables',
        route: '/projects',
        iconName: 'Layers',
        description: 'Track agency client sprint deliverables, review rounds, billable hours, and milestone sign-offs.',
        category: 'Client Delivery',
        views: ['TABLE', 'KANBAN'],
        fields: [
          { id: 'f_del_title', name: 'title', label: 'Deliverable Name', key: 'title', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_del_client', name: 'client_account', label: 'Client Brand / Account', key: 'client_account', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_del_lead', name: 'creative_lead', label: 'Creative Lead / Art Director', key: 'creative_lead', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_del_due', name: 'due_date', label: 'Delivery Deadline', key: 'due_date', type: 'DATE', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_del_hours', name: 'budgeted_hours', label: 'Allocated Hours', key: 'budgeted_hours', type: 'NUMBER', required: false, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_d_concept', name: 'Concept & Briefing', label: 'Concept', color: '#a855f7', order: 1, isDefault: true },
          { id: 'st_d_prod', name: 'In Production', label: 'Production', color: '#38bdf8', order: 2 },
          { id: 'st_d_review', name: 'Client Review & Feedback', label: 'Client Review', color: '#f59e0b', order: 3 },
          { id: 'st_d_approved', name: 'Approved & Signed Off', label: 'Approved', color: '#10b981', order: 4, isTerminal: true, outcome: 'SUCCESS' },
        ],
        relationships: [],
      },
    ],
    dashboardWidgets: [
      { id: 'w_retainer_rev', title: 'Monthly Recurring Retainers (MRR)', type: 'KPI', size: 'SMALL', metricValue: '$84,500', metricDelta: '18 active retainers', metricSubtext: '92% realization rate', iconName: 'DollarSign' },
      { id: 'w_active_sprints', title: 'Active Client Deliverables', type: 'KPI', size: 'SMALL', metricValue: '14 projects', metricDelta: '3 sprints due this wk', metricSubtext: 'Design & Engineering', iconName: 'ClipboardList' },
      { id: 'w_pitch_pipe', title: 'Agency Pitch Pipeline', type: 'KPI', size: 'SMALL', metricValue: '$195,000', metricDelta: '6 proposals out', metricSubtext: 'Avg deal size $32.5k', iconName: 'Briefcase' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_new_pitch', label: 'Create Pitch Opportunity', actionType: 'NAVIGATE', href: '/deals?action=new', iconName: 'Briefcase', primary: true },
      { id: 'qa_new_sow', label: 'Draft Client Proposal (SOW)', actionType: 'NAVIGATE', href: '/quotes?action=new', iconName: 'FileBadge' },
    ],
    workflowTemplates: [
      { id: 'wf_retainer_milestone', name: 'Deliverable Approval to Invoice Trigger', category: 'Billing Automation', trigger: 'Deliverable Status -> Approved', actions: ['Generate Milestone Invoice', 'Notify Accounting'], description: 'Auto-bills client upon deliverable sign-off', enabledByDefault: true, requiredServiceIds: ['srv_invoices_billing'] },
    ],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#8b5cf6', accentColor: '#a78bfa', badgeStyle: 'bg-purple-500/15 text-purple-400 border border-purple-500/30' },
  },

  // =========================================================================
  // CONSTRUCTION - 7. GENERAL CONTRACTOR & CONSTRUCTION
  // =========================================================================
  'construction_contractor': {
    id: 'construction_contractor',
    industry: 'CONSTRUCTION',
    name: 'General Contractor & Construction',
    slug: 'construction-contractor',
    description: 'Job sites, subcontractors, equipment tracking, milestone draws, and material takeoff.',
    iconName: 'Building2',
    coreServiceIds: [
      'srv_projects_tasks',
      'srv_invoices_billing',
      'srv_documents_esign',
      'srv_contacts',
      'srv_inventory_stock',
    ],
    recommendedServiceIds: [
      'srv_deals_pipeline',
      'srv_dual_khata',
      'srv_universal_automation',
      'srv_hr_people',
    ],
    optionalServiceIds: ['srv_marketing_studio', 'srv_neural_ocr'],
    advancedServiceIds: ['srv_customer_360'],
    terminology: {
      contacts: 'Clients, Architects & Subcontractors',
      deals: 'Bids & Estimates',
      projects: 'Active Job Sites & Milestones',
      invoices: 'Progress Draws & AIA Invoices',
      products: 'Building Materials & Equipment',
      tickets: 'Punch List & Field Issues',
      records: 'Job Site Records',
    },
    recordTypes: [
      {
        id: 'rec_equipment',
        name: 'Heavy Equipment & Machinery',
        singular: 'Equipment',
        plural: 'Equipment',
        route: '/projects',
        iconName: 'Truck',
        description: 'Track excavators, cranes, generators, site assignments, and preventative maintenance logs.',
        category: 'Job Site Logistics',
        views: ['TABLE', 'KANBAN'],
        fields: [
          { id: 'f_eq_name', name: 'equipment_title', label: 'Machine / Tool Title', key: 'equipment_title', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_eq_sn', name: 'serial_number', label: 'Serial / Asset ID', key: 'serial_number', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_eq_site', name: 'job_site', label: 'Assigned Job Site', key: 'job_site', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_eq_hours', name: 'operating_hours', label: 'Engine Operating Hours', key: 'operating_hours', type: 'NUMBER', required: false, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_eq_avail', name: 'Yard Available', label: 'In Yard', color: '#10b981', order: 1, isDefault: true },
          { id: 'st_eq_deployed', name: 'Deployed to Site', label: 'Deployed', color: '#38bdf8', order: 2 },
          { id: 'st_eq_maint', name: 'Under Maintenance', label: 'Repair', color: '#f59e0b', order: 3 },
        ],
        relationships: [],
      },
    ],
    dashboardWidgets: [
      { id: 'w_active_sites', title: 'Active Job Sites Under Construction', type: 'KPI', size: 'SMALL', metricValue: '8 Sites', metricDelta: '14 Subcontractor crews', metricSubtext: 'Safety: 412 Days Incident-Free', iconName: 'Building2' },
      { id: 'w_bid_pipeline', title: 'Pending Tender Bids', type: 'KPI', size: 'SMALL', metricValue: '$3.8M', metricDelta: '5 Submissions', metricSubtext: 'Win rate: 42%', iconName: 'Briefcase' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_add_site', label: 'Create Job Site', actionType: 'NAVIGATE', href: '/projects?action=new', iconName: 'Plus', primary: true },
      { id: 'qa_log_equipment', label: 'Deploy Heavy Equipment', actionType: 'NAVIGATE', href: '/projects', iconName: 'Truck' },
    ],
    workflowTemplates: [
      { id: 'wf_site_safety_alert', name: 'Incident Safety OSHA Escalation', category: 'Site Safety', trigger: 'Incident Logged', actions: ['Notify Safety Director', 'Lock Site Work Order'], description: 'Mandatory OSHA safety triage workflow', enabledByDefault: true, requiredServiceIds: ['srv_projects_tasks'] },
    ],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#d97706', accentColor: '#f59e0b', badgeStyle: 'bg-amber-600/15 text-amber-400 border border-amber-600/30' },
  },

  // =========================================================================
  // SAAS - 8. B2B SAAS SCALE-UP
  // =========================================================================
  'saas_scaleup': {
    id: 'saas_scaleup',
    industry: 'SAAS',
    name: 'B2B SaaS Scale-Up & Cloud Tech',
    slug: 'saas-scaleup',
    description: 'SaaS recurring subscriptions (MRR/ARR), customer success health, developer APIs, and quotes.',
    iconName: 'Cpu',
    coreServiceIds: [
      'srv_saas_subscriptions',
      'srv_deals_pipeline',
      'srv_contacts',
      'srv_support_desk',
      'srv_invoices_billing',
    ],
    recommendedServiceIds: [
      'srv_customer_360',
      'srv_cpq_quotes',
      'srv_b2b_prospector',
      'srv_universal_automation',
    ],
    optionalServiceIds: ['srv_marketing_studio', 'srv_documents_esign'],
    advancedServiceIds: ['srv_hr_people'],
    terminology: {
      contacts: 'Accounts & Tenant Admins',
      deals: 'Expansion & New ARR Pipeline',
      projects: 'Sprint Deliverables',
      invoices: 'Recurring SaaS Invoices',
      products: 'Tier Plans & Add-Ons',
      tickets: 'CS Helpdesk & Bug Tickets',
      records: 'Tenant Accounts',
    },
    recordTypes: [
      {
        id: 'rec_subscription',
        name: 'B2B SaaS Subscription Contract',
        singular: 'Subscription',
        plural: 'Subscriptions',
        route: '/subscriptions',
        iconName: 'Cpu',
        description: 'Track recurring customer cloud contracts, active plan tiers, contracted ARR/MRR, and renewal dates.',
        category: 'Revenue Operations',
        views: ['TABLE', 'KANBAN'],
        fields: [
          { id: 'f_sub_acc', name: 'account_name', label: 'Company / Tenant Name', key: 'account_name', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_sub_plan', name: 'plan_tier', label: 'Plan Tier', key: 'plan_tier', type: 'DROPDOWN', options: ['Starter Cloud ($499/mo)', 'Growth Scale ($1,499/mo)', 'Enterprise Dedicated ($4,999/mo)', 'Custom Multi-Region'], required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_sub_mrr', name: 'mrr_amount', label: 'Contracted MRR ($)', key: 'mrr_amount', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_sub_seats', name: 'licensed_seats', label: 'Seat Licenses', key: 'licensed_seats', type: 'NUMBER', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_sub_ren', name: 'renewal_date', label: 'Renewal Date', key: 'renewal_date', type: 'DATE', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_sub_trial', name: 'Proof-of-Concept Trial', label: 'Trial', color: '#a855f7', order: 1, isDefault: true },
          { id: 'st_sub_active', name: 'Active Subscription', label: 'Active', color: '#10b981', order: 2 },
          { id: 'st_sub_past_due', name: 'Dunning / Past Due', label: 'Past Due', color: '#f59e0b', order: 3 },
          { id: 'st_sub_churned', name: 'Cancelled / Churned', label: 'Churned', color: '#ef4444', order: 4, isTerminal: true },
        ],
        relationships: [],
      },
    ],
    dashboardWidgets: [
      { id: 'w_arr_mrr', title: 'Monthly Recurring Revenue (MRR)', type: 'KPI', size: 'SMALL', metricValue: '$118,400', metricDelta: '+14.2% MoM', metricSubtext: 'Net ARR: $1.42M', iconName: 'TrendingUp' },
      { id: 'w_net_churn', title: 'Net Revenue Retention (NRR)', type: 'KPI', size: 'SMALL', metricValue: '116%', metricDelta: 'Cohort 2025', metricSubtext: 'Gross Churn: 0.8%', iconName: 'ShieldCheck' },
      { id: 'w_nps_health', title: 'Customer Success Health Score', type: 'KPI', size: 'SMALL', metricValue: '88 / 100', metricDelta: '3 accounts at risk', metricSubtext: 'CSM check-in assigned', iconName: 'Activity' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_new_sub', label: 'Create SaaS Subscription', actionType: 'NAVIGATE', href: '/subscriptions?action=new', iconName: 'Plus', primary: true },
      { id: 'qa_send_quote', label: 'Send Enterprise CPQ Quote', actionType: 'NAVIGATE', href: '/quotes?action=new', iconName: 'FileBadge' },
    ],
    workflowTemplates: [
      { id: 'wf_dunning_retry', name: 'Automated Stripe Dunning & In-App Notice', category: 'Revenue Recovery', trigger: 'Payment Failed', actions: ['Retry Charge in 48h', 'In-App Banner', 'Email Billing Contact'], description: 'Recovers 82% of failed credit card transactions', enabledByDefault: true, requiredServiceIds: ['srv_saas_subscriptions', 'srv_invoices_billing'] },
    ],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#6366f1', accentColor: '#818cf8', badgeStyle: 'bg-indigo-500/15 text-indigo-400 border border-indigo-500/30' },
  },

  // =========================================================================
  // CUSTOM - 9. BESPOKE CUSTOM ARCHITECTURE
  // =========================================================================
  'custom_bespoke': {
    id: 'custom_bespoke',
    industry: 'CUSTOM',
    name: 'Custom Tailored Workspace',
    slug: 'custom-bespoke',
    description: 'Bespoke workspace dynamically assembled with user-selected features and modules.',
    iconName: 'Layers',
    coreServiceIds: [
      'srv_contacts',
      'srv_deals_pipeline',
      'srv_invoices_billing',
      'srv_projects_tasks',
    ],
    recommendedServiceIds: [
      'srv_documents_esign',
      'srv_universal_automation',
      'srv_support_desk',
    ],
    optionalServiceIds: ['srv_hr_people', 'srv_marketing_studio'],
    advancedServiceIds: ['srv_customer_360'],
    terminology: {
      contacts: 'Contacts & Accounts',
      deals: 'Sales & Deals',
      projects: 'Tasks & Projects',
      invoices: 'Invoices & Billing',
      products: 'Catalog & Products',
      tickets: 'Support & Inquiries',
      records: 'Custom Records',
    },
    recordTypes: [],
    dashboardWidgets: [
      { id: 'w_custom_ops', title: 'Operational Efficiency', type: 'KPI', size: 'SMALL', metricValue: '99.4%', metricDelta: '+2.1%', metricSubtext: 'All systems normal', iconName: 'Compass' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_custom_add', label: 'Create Record', actionType: 'NAVIGATE', href: '/contacts', iconName: 'Plus', primary: true },
    ],
    workflowTemplates: [],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#10b981', accentColor: '#34d399', badgeStyle: 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30' },
  },

  // =========================================================================
  // ENTERPRISE - 10. MASTER ENTERPRISE (ALL MODULES)
  // =========================================================================
  'enterprise_master': {
    id: 'enterprise_master',
    industry: 'ENTERPRISE',
    name: 'Master Enterprise (All Modules)',
    slug: 'enterprise-master',
    description: 'Unfiltered access to all 67 enterprise CRM, platform, and revenue modules.',
    iconName: 'Globe',
    coreServiceIds: [
      'srv_contacts',
      'srv_deals_pipeline',
      'srv_invoices_billing',
      'srv_projects_tasks',
      'srv_documents_esign',
      'srv_cpq_quotes',
      'srv_saas_subscriptions',
      'srv_support_desk',
      'srv_universal_automation',
    ],
    recommendedServiceIds: [
      'srv_customer_360',
      'srv_b2b_prospector',
      'srv_marketing_studio',
      'srv_hr_people',
      'srv_inventory_stock',
    ],
    optionalServiceIds: ['srv_neural_ocr', 'srv_payment_links_pos'],
    advancedServiceIds: ['srv_dual_khata'],
    terminology: {
      contacts: 'Contacts & Accounts',
      deals: 'Deals Pipeline',
      projects: 'Sprint Projects',
      invoices: 'Commercial Invoices',
      products: 'Price Books',
      tickets: 'Helpdesk Support',
      records: 'Enterprise Records',
    },
    recordTypes: [],
    dashboardWidgets: [
      { id: 'w_all_revenue', title: 'Global Enterprise ARR', type: 'KPI', size: 'SMALL', metricValue: '$4.28M', metricDelta: '+18.4% YoY', metricSubtext: 'Consolidated subsidiaries', iconName: 'DollarSign' },
      { id: 'w_all_compliance', title: 'SOC2 & HIPAA Compliance', type: 'KPI', size: 'SMALL', metricValue: '100%', metricDelta: 'Audit Verified', metricSubtext: 'Zero vulnerabilities', iconName: 'Shield' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_ent_dash', label: 'Executive Cockpit', actionType: 'NAVIGATE', href: '/dashboard', iconName: 'Compass', primary: true },
    ],
    workflowTemplates: [],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [],
    theme: { primaryColor: '#6366f1', accentColor: '#818cf8', badgeStyle: 'bg-indigo-500/15 text-indigo-400 border border-indigo-500/30' },
  },

  // =========================================================================
  // LEGAL - LAW FIRM & LEGAL PRACTICE
  // =========================================================================
  'legal_practice': {
    id: 'legal_practice',
    industry: 'LEGAL',
    name: 'Law Firm & Legal Practice',
    slug: 'legal-practice',
    description: 'Litigation matters, legal briefs, court deadlines, trust ledger, and billable time entries.',
    iconName: 'Scale',
    coreServiceIds: [
      'srv_contacts',
      'srv_deals_pipeline',
      'srv_invoices_billing',
      'srv_documents_esign',
    ],
    recommendedServiceIds: [
      'srv_projects_tasks',
      'srv_support_desk',
      'srv_hr_people',
    ],
    optionalServiceIds: [
      'srv_marketing_studio',
      'srv_dual_khata',
    ],
    advancedServiceIds: [
      'srv_universal_automation',
      'srv_customer_360',
    ],
    terminology: {
      contacts: 'Clients & Counsel',
      deals: 'Matters & Retainers',
      projects: 'Litigation Briefs',
      invoices: 'Fee Notes & Trust Billings',
      products: 'Legal Practice Areas',
      tickets: 'Client Inquiries',
      records: 'Case Files',
    },
    recordTypes: [
      {
        id: 'rec_legal_matter',
        name: 'Legal Case Matter',
        singular: 'Case Matter',
        plural: 'Case Matters',
        route: '/industry/legal',
        iconName: 'Scale',
        description: 'Litigation, corporate filings, discovery documents, and opposing counsel',
        category: 'Litigation',
        isCustom: false,
        fields: [
          { id: 'f_lm_docket', name: 'docket_number', label: 'Court Docket / Case #', key: 'docket_number', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_lm_practice', name: 'practice_area', label: 'Practice Area', key: 'practice_area', type: 'DROPDOWN', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS', options: ['Corporate', 'Litigation', 'Intellectual Property', 'Real Estate', 'Tax Law', 'Family Law'] },
          { id: 'f_lm_lead_attorney', name: 'lead_attorney', label: 'Lead Partner Attorney', key: 'lead_attorney', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_lm_billable_rate', name: 'billable_rate', label: 'Hourly Billable Rate ($/hr)', key: 'billable_rate', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_lm_retainer_bal', name: 'retainer_balance', label: 'Trust Retainer Balance ($)', key: 'retainer_balance', type: 'CURRENCY', required: false, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_lm_intake', name: 'Client Intake', label: 'Client Intake', color: '#64748b', order: 1, isDefault: true },
          { id: 'st_lm_discovery', name: 'Discovery & Briefs', label: 'Discovery & Briefs', color: '#0ea5e9', order: 2 },
          { id: 'st_lm_pre_trial', name: 'Pre-Trial Hearing', label: 'Pre-Trial Hearing', color: '#f59e0b', order: 3 },
          { id: 'st_lm_verdict', name: 'Settlement / Verdict', label: 'Settlement / Verdict', color: '#10b981', order: 4, isTerminal: true, outcome: 'SUCCESS' },
          { id: 'st_lm_archived', name: 'Archived / Closed', label: 'Archived / Closed', color: '#334155', order: 5, isTerminal: true, outcome: 'NEUTRAL' },
        ],
        relationships: [],
        views: ['TABLE', 'KANBAN'],
      },
    ],
    dashboardWidgets: [
      { id: 'w_leg_billable', title: 'Monthly Billable Hours', type: 'KPI', size: 'SMALL', metricValue: '342 hrs', metricDelta: '+12.4%', metricSubtext: '88% realization rate', iconName: 'Clock' },
      { id: 'w_leg_active_matters', title: 'Active Case Matters', type: 'KPI', size: 'SMALL', metricValue: '48 Matters', metricDelta: '14 Court Dates', metricSubtext: 'Next 14 business days', iconName: 'Scale' },
      { id: 'w_leg_trust', title: 'Trust & Retainer Escrow', type: 'KPI', size: 'SMALL', metricValue: '$284,500', metricDelta: 'Compliant', metricSubtext: 'Zero IOLTA deficit', iconName: 'Landmark' },
      { id: 'w_leg_fees', title: 'Realized Legal Fees', type: 'KPI', size: 'SMALL', metricValue: '$148,900', metricDelta: '+8.2% vs target', metricSubtext: 'Invoiced Net-30', iconName: 'Receipt' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_leg_matter', label: 'New Legal Matter', actionType: 'NAVIGATE', href: '/industry/legal#matters', iconName: 'Plus', primary: true },
      { id: 'qa_leg_time', label: 'Log Billable Time', actionType: 'NAVIGATE', href: '/industry/legal#time', iconName: 'Clock' },
    ],
    workflowTemplates: [],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [
      {
        id: 'sec_legal_ops',
        sectionTitle: 'Legal & Practice Operations',
        iconName: 'Scale',
        order: 1,
        items: [
          { id: 'nav_leg_hub', label: 'Practice Command Hub', href: '/industry/legal', iconName: 'Scale', badge: 'Live' },
          { id: 'nav_leg_matters', label: 'Case Matters & Docket', href: '/industry/legal#matters', iconName: 'FileText', badge: 'Active' },
          { id: 'nav_leg_clients', label: 'Clients & Retainers', href: '/contacts', iconName: 'Users', badge: 'Clients' },
          { id: 'nav_leg_trust', label: 'IOLTA Trust Ledger', href: '/invoices', iconName: 'Landmark', badge: 'Trust' },
        ],
      },
    ],
    theme: { primaryColor: '#0ea5e9', accentColor: '#38bdf8', badgeStyle: 'bg-sky-500/15 text-sky-400 border border-sky-500/30' },
  },

  // =========================================================================
  // LOGISTICS - FREIGHT & FLEET LOGISTICS
  // =========================================================================
  'logistics_freight': {
    id: 'logistics_freight',
    industry: 'LOGISTICS',
    name: 'Freight Brokerage & Fleet Logistics',
    slug: 'logistics-freight',
    description: 'Dispatch board, carrier telematics, BOL bills of lading, and freight contract invoicing.',
    iconName: 'Truck',
    coreServiceIds: [
      'srv_contacts',
      'srv_deals_pipeline',
      'srv_invoices_billing',
      'srv_inventory_stock',
    ],
    recommendedServiceIds: [
      'srv_projects_tasks',
      'srv_support_desk',
      'srv_documents_esign',
    ],
    optionalServiceIds: [
      'srv_marketing_studio',
      'srv_hr_people',
    ],
    advancedServiceIds: [
      'srv_universal_automation',
      'srv_customer_360',
    ],
    terminology: {
      contacts: 'Shippers & Carriers',
      deals: 'Freight Lane Contracts',
      projects: 'Active Dispatched Loads',
      invoices: 'Freight Bills & POD Receipts',
      products: 'Lane Tariffs & Reefer Classes',
      tickets: 'Dispatch Incidents',
      records: 'Freight Loads',
    },
    recordTypes: [
      {
        id: 'rec_freight_load',
        name: 'Freight Load Manifest',
        singular: 'Freight Load',
        plural: 'Freight Loads',
        route: '/industry/logistics',
        iconName: 'Truck',
        description: 'Bill of Lading manifest, origin-destination route, trailer type, and rate confirmation',
        category: 'Fleet',
        isCustom: false,
        fields: [
          { id: 'f_fl_load_num', name: 'load_number', label: 'Load PRO / BOL #', key: 'load_number', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_fl_origin', name: 'origin_city', label: 'Origin City & State', key: 'origin_city', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_fl_dest', name: 'destination_city', label: 'Destination City & State', key: 'destination_city', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_fl_weight', name: 'total_weight_lbs', label: 'Cargo Weight (lbs)', key: 'total_weight_lbs', type: 'NUMBER', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_fl_rate', name: 'agreed_rate', label: 'Shipper Rate ($)', key: 'agreed_rate', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_fl_booked', name: 'Booked / Scheduled', label: 'Booked / Scheduled', color: '#64748b', order: 1, isDefault: true },
          { id: 'st_fl_dispatched', name: 'Dispatched / In-Transit', label: 'Dispatched / In-Transit', color: '#38bdf8', order: 2 },
          { id: 'st_fl_delivered', name: 'Delivered / POD Signed', label: 'Delivered / POD Signed', color: '#10b981', order: 3, isTerminal: true, outcome: 'SUCCESS' },
          { id: 'st_fl_exception', name: 'Exception / Layover', label: 'Exception / Layover', color: '#ef4444', order: 4, outcome: 'FAILURE' },
        ],
        relationships: [],
        views: ['TABLE', 'KANBAN'],
      },
    ],
    dashboardWidgets: [
      { id: 'w_log_active_loads', title: 'Active Dispatched Loads', type: 'KPI', size: 'SMALL', metricValue: '124 Loads', metricDelta: '99.2% On-Time', metricSubtext: 'Across 18 national lanes', iconName: 'Truck' },
      { id: 'w_log_freight_rev', title: 'Gross Freight Revenue', type: 'KPI', size: 'SMALL', metricValue: '$348,200', metricDelta: '+14.8% MoM', metricSubtext: 'Carrier payout: $286K', iconName: 'DollarSign' },
      { id: 'w_log_diesel', title: 'Fleet Diesel Index', type: 'KPI', size: 'SMALL', metricValue: '$3.82 / gal', metricDelta: '-1.4% vs avg', metricSubtext: 'Fuel surcharge applied', iconName: 'Activity' },
      { id: 'w_log_pod', title: 'Pending POD Sign-offs', type: 'KPI', size: 'SMALL', metricValue: '18 Delivery BOLs', metricDelta: '92% Cleared', metricSubtext: 'Ready for factoring', iconName: 'Receipt' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_log_dispatch', label: 'Dispatch New Load', actionType: 'NAVIGATE', href: '/industry/logistics#dispatch', iconName: 'Plus', primary: true },
      { id: 'qa_log_carrier', label: 'Assign Carrier', actionType: 'NAVIGATE', href: '/industry/logistics#carriers', iconName: 'Truck' },
    ],
    workflowTemplates: [],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [
      {
        id: 'sec_logistics_ops',
        sectionTitle: 'Fleet & Dispatch Operations',
        iconName: 'Truck',
        order: 1,
        items: [
          { id: 'nav_log_hub', label: 'Dispatch Command HUD', href: '/industry/logistics', iconName: 'Truck', badge: 'Live' },
          { id: 'nav_log_loads', label: 'Active Loads Board', href: '/industry/logistics#loads', iconName: 'ClipboardList', badge: 'Loads' },
          { id: 'nav_log_carriers', label: 'Carrier Network & Vetting', href: '/contacts', iconName: 'Users', badge: 'Fleets' },
          { id: 'nav_log_billing', label: 'Freight Invoices & Factors', href: '/invoices', iconName: 'Receipt', badge: 'Invoices' },
        ],
      },
    ],
    theme: { primaryColor: '#f97316', accentColor: '#fb923c', badgeStyle: 'bg-orange-500/15 text-orange-400 border border-orange-500/30' },
  },

  // =========================================================================
  // FITNESS - GYM & FITNESS STUDIO
  // =========================================================================
  'fitness_gym': {
    id: 'fitness_gym',
    industry: 'FITNESS',
    name: 'Gym Club & Fitness Studio',
    slug: 'fitness-gym',
    description: 'Member turnstile check-ins, personal training sessions, recurring dues, and trainer schedules.',
    iconName: 'Dumbbell',
    coreServiceIds: [
      'srv_contacts',
      'srv_invoices_billing',
      'srv_projects_tasks',
      'srv_support_desk',
    ],
    recommendedServiceIds: [
      'srv_deals_pipeline',
      'srv_inventory_stock',
      'srv_documents_esign',
    ],
    optionalServiceIds: [
      'srv_marketing_studio',
      'srv_hr_people',
    ],
    advancedServiceIds: [
      'srv_universal_automation',
      'srv_customer_360',
    ],
    terminology: {
      contacts: 'Gym Members',
      deals: 'Membership Subscriptions',
      projects: 'Group Class Schedules',
      invoices: 'Monthly Member Dues',
      products: 'Supplements & Passes',
      tickets: 'Member Support Inquiries',
      records: 'Memberships',
    },
    recordTypes: [
      {
        id: 'rec_gym_member',
        name: 'Gym Member Profile',
        singular: 'Member',
        plural: 'Members',
        route: '/industry/fitness',
        iconName: 'Dumbbell',
        description: 'Keycard access, personal trainer assignments, fitness assessment records, and waivers',
        category: 'Members',
        isCustom: false,
        fields: [
          { id: 'f_gm_keycard', name: 'keycard_barcode', label: 'Keycard / RFID Barcode', key: 'keycard_barcode', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_gm_tier', name: 'membership_tier', label: 'Membership Tier', key: 'membership_tier', type: 'DROPDOWN', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS', options: ['Basic Open Gym', 'All-Access VIP', 'Student / Corporate', 'Personal Training Plus'] },
          { id: 'f_gm_waiver', name: 'waiver_signed', label: 'Liability Waiver Signed', key: 'waiver_signed', type: 'CHECKBOX', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_gm_monthly_fee', name: 'monthly_fee', label: 'Monthly Recurring Dues ($)', key: 'monthly_fee', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_gm_active', name: 'Active In-Good-Standing', label: 'Active In-Good-Standing', color: '#10b981', order: 1, isDefault: true },
          { id: 'st_gm_past_due', name: 'Past-Due / Freeze', label: 'Past-Due / Freeze', color: '#f59e0b', order: 2 },
          { id: 'st_gm_cancelled', name: 'Cancelled / Expired', label: 'Cancelled / Expired', color: '#ef4444', order: 3, isTerminal: true, outcome: 'FAILURE' },
        ],
        relationships: [],
        views: ['TABLE', 'KANBAN'],
      },
    ],
    dashboardWidgets: [
      { id: 'w_fit_active_members', title: 'Active Gym Memberships', type: 'KPI', size: 'SMALL', metricValue: '1,420', metricDelta: '+82 this month', metricSubtext: '94% renewal retention', iconName: 'Users' },
      { id: 'w_fit_checkins', title: 'Daily Turnstile Check-ins', type: 'KPI', size: 'SMALL', metricValue: '386 Visits', metricDelta: 'Peak: 17:30 - 20:00', metricSubtext: 'Capacity: 52%', iconName: 'Activity' },
      { id: 'w_fit_mrr', title: 'Recurring Membership Dues', type: 'KPI', size: 'SMALL', metricValue: '$92,400', metricDelta: '+6.8% MoM', metricSubtext: 'Auto-debit on 1st', iconName: 'DollarSign' },
      { id: 'w_fit_classes', title: 'Group Fitness Fill Rate', type: 'KPI', size: 'SMALL', metricValue: '86% Seats', metricDelta: '24 Classes Today', metricSubtext: 'Top: Spin & HIIT', iconName: 'Calendar' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_fit_checkin', label: 'Fast Member Check-In', actionType: 'NAVIGATE', href: '/industry/fitness#checkin', iconName: 'Plus', primary: true },
      { id: 'qa_fit_class', label: 'Book Class / Trainer', actionType: 'NAVIGATE', href: '/industry/fitness#classes', iconName: 'Calendar' },
    ],
    workflowTemplates: [],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [
      {
        id: 'sec_fitness_ops',
        sectionTitle: 'Gym & Studio Operations',
        iconName: 'Dumbbell',
        order: 1,
        items: [
          { id: 'nav_fit_hub', label: 'Turnstile & Front Desk', href: '/industry/fitness', iconName: 'Dumbbell', badge: 'Live' },
          { id: 'nav_fit_members', label: 'Member Roster & Passes', href: '/contacts', iconName: 'Users', badge: 'Members' },
          { id: 'nav_fit_schedule', label: 'Group Fitness Classes', href: '/industry/fitness#classes', iconName: 'Calendar', badge: 'Schedule' },
          { id: 'nav_fit_dues', label: 'Auto-Debit Dues & POS', href: '/invoices', iconName: 'Receipt', badge: 'Billing' },
        ],
      },
    ],
    theme: { primaryColor: '#ec4899', accentColor: '#f472b6', badgeStyle: 'bg-pink-500/15 text-pink-400 border border-pink-500/30' },
  },

  // =========================================================================
  // AUTOMOTIVE - REPAIR BAY & FLEET SERVICE
  // =========================================================================
  'automotive_repair': {
    id: 'automotive_repair',
    industry: 'AUTOMOTIVE',
    name: 'Automotive Repair & Service Bay',
    slug: 'automotive-repair',
    description: 'Repair orders (RO), VIN lookup, diagnostic bay scheduling, OEM parts markup, and labor rates.',
    iconName: 'Wrench',
    coreServiceIds: [
      'srv_contacts',
      'srv_deals_pipeline',
      'srv_invoices_billing',
      'srv_inventory_stock',
    ],
    recommendedServiceIds: [
      'srv_projects_tasks',
      'srv_support_desk',
      'srv_documents_esign',
    ],
    optionalServiceIds: [
      'srv_marketing_studio',
      'srv_dual_khata',
    ],
    advancedServiceIds: [
      'srv_universal_automation',
      'srv_customer_360',
    ],
    terminology: {
      contacts: 'Vehicle Owners & Fleet Accounts',
      deals: 'Service Estimates & Diagnostics',
      projects: 'Bay Repair Orders (RO)',
      invoices: 'Repair Invoices & Parts Bills',
      products: 'OEM & Aftermarket Parts Catalog',
      tickets: 'Service Inquiries',
      records: 'Repair Orders',
    },
    recordTypes: [
      {
        id: 'rec_auto_ro',
        name: 'Repair Order (RO)',
        singular: 'Repair Order',
        plural: 'Repair Orders',
        route: '/industry/automotive',
        iconName: 'Wrench',
        description: 'Vehicle VIN, odometer mileage, diagnostic trouble codes (DTC), parts requisition, and tech labor',
        category: 'Service Bay',
        isCustom: false,
        fields: [
          { id: 'f_ro_num', name: 'ro_number', label: 'Repair Order (RO) #', key: 'ro_number', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_ro_vin', name: 'vehicle_vin', label: 'Vehicle 17-digit VIN', key: 'vehicle_vin', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_ro_make_model', name: 'make_model_year', label: 'Make / Model / Year', key: 'make_model_year', type: 'TEXT', required: true, searchable: true, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_ro_mileage', name: 'odometer_mileage', label: 'Odometer Mileage', key: 'odometer_mileage', type: 'NUMBER', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
          { id: 'f_ro_est_total', name: 'estimate_total', label: 'Approved Estimate Total ($)', key: 'estimate_total', type: 'CURRENCY', required: true, searchable: false, filterable: true, reportable: true, visibility: 'ALWAYS' },
        ],
        statuses: [
          { id: 'st_ro_writeup', name: 'Service Advisor Writeup', label: 'Service Advisor Writeup', color: '#64748b', order: 1, isDefault: true },
          { id: 'st_ro_bay', name: 'In Service Bay (Repairing)', label: 'In Service Bay (Repairing)', color: '#3b82f6', order: 2 },
          { id: 'st_ro_parts_hold', name: 'Waiting on OEM Parts', label: 'Waiting on OEM Parts', color: '#f59e0b', order: 3 },
          { id: 'st_ro_qc', name: 'Road Test & QC Check', label: 'Road Test & QC Check', color: '#10b981', order: 4 },
          { id: 'st_ro_completed', name: 'Closed & Invoiced', label: 'Closed & Invoiced', color: '#059669', order: 5, isTerminal: true, outcome: 'SUCCESS' },
        ],
        relationships: [],
        views: ['TABLE', 'KANBAN'],
      },
    ],
    dashboardWidgets: [
      { id: 'w_auto_active_ro', title: 'Open Repair Orders (RO)', type: 'KPI', size: 'SMALL', metricValue: '28 Bays Active', metricDelta: '6 Ready for Pickup', metricSubtext: 'Avg Turnaround: 4.2 hrs', iconName: 'Wrench' },
      { id: 'w_auto_parts_rev', title: 'Bay Parts & Labor Gross', type: 'KPI', size: 'SMALL', metricValue: '$84,500', metricDelta: '+9.2% vs target', metricSubtext: 'Gross margin: 54.2%', iconName: 'DollarSign' },
      { id: 'w_auto_bay_util', title: 'Service Bay Utilization', type: 'KPI', size: 'SMALL', metricValue: '91.4%', metricDelta: '8 Master Techs', metricSubtext: 'Efficiency index 1.18', iconName: 'Activity' },
      { id: 'w_auto_csi', title: 'Customer Satisfaction (CSI)', type: 'KPI', size: 'SMALL', metricValue: '4.92 / 5.0', metricDelta: '98 reviews', metricSubtext: 'Top rating this quarter', iconName: 'Sparkles' },
    ],
    kpis: [],
    quickActions: [
      { id: 'qa_auto_ro', label: 'Create Repair Order (RO)', actionType: 'NAVIGATE', href: '/industry/automotive#create-ro', iconName: 'Plus', primary: true },
      { id: 'qa_auto_vin', label: 'VIN Decoder & History', actionType: 'NAVIGATE', href: '/industry/automotive#vin', iconName: 'Search' },
    ],
    workflowTemplates: [],
    documentTemplates: [],
    reports: [],
    roles: [],
    navigation: [
      {
        id: 'sec_automotive_ops',
        sectionTitle: 'Automotive & Bay Operations',
        iconName: 'Wrench',
        order: 1,
        items: [
          { id: 'nav_auto_hub', label: 'Service Bay Dispatch', href: '/industry/automotive', iconName: 'Wrench', badge: 'Bays' },
          { id: 'nav_auto_ro', label: 'Repair Orders Queue', href: '/industry/automotive#ro', iconName: 'ClipboardList', badge: 'Active' },
          { id: 'nav_auto_clients', label: 'Vehicle Owners & Fleets', href: '/contacts', iconName: 'Users', badge: 'Owners' },
          { id: 'nav_auto_invoices', label: 'Repair Invoices & Parts Bills', href: '/invoices', iconName: 'Receipt', badge: 'Invoices' },
        ],
      },
    ],
    theme: { primaryColor: '#ef4444', accentColor: '#f87171', badgeStyle: 'bg-red-500/15 text-red-400 border border-red-500/30' },
  },
};

/**
 * List of available Industries and their Business Types
 */
export const INDUSTRY_CATALOG = [
  {
    key: 'HEALTHCARE' as IndustryKey,
    name: 'Healthcare & Life Sciences',
    iconName: 'Stethoscope',
    description: 'Hospitals, outpatient medical practices, dental clinics, and diagnostic labs.',
    businessTypes: [
      { id: 'dental_clinic', name: 'Dental Clinic & Orthodontics' },
      { id: 'private_clinic', name: 'Private Specialist Clinic' },
      { id: 'hospital_center', name: 'General Hospital & Medical Center' },
      { id: 'diagnostic_lab', name: 'Diagnostic Pathology & Imaging' },
      { id: 'physio_center', name: 'Physiotherapy & Rehab Center' },
    ],
  },
  {
    key: 'REAL_ESTATE' as IndustryKey,
    name: 'Real Estate & Brokerage',
    iconName: 'Home',
    description: 'Agencies, commercial brokerages, property developers, and rental management.',
    businessTypes: [
      { id: 'realestate_brokerage', name: 'Real Estate Agency & Brokerage' },
      { id: 'property_management', name: 'Property Management & Rentals' },
      { id: 'property_developer', name: 'Property Developer' },
      { id: 'commercial_brokerage', name: 'Commercial Brokerage' },
    ],
  },
  {
    key: 'HOSPITALITY' as IndustryKey,
    name: 'Food & Hospitality',
    iconName: 'UtensilsCrossed',
    description: 'Fine dining, cafes, cloud kitchens, catering, and franchise restaurant chains.',
    businessTypes: [
      { id: 'restaurant_cafe', name: 'Restaurant, Cafe & Cloud Kitchen' },
      { id: 'fine_dining', name: 'Fine Dining & Banquet' },
      { id: 'fast_food_chain', name: 'Fast Food Counter & Franchise' },
      { id: 'catering_events', name: 'Catering & Event Dining' },
    ],
  },
  {
    key: 'RETAIL' as IndustryKey,
    name: 'Retail & Storefront Commerce',
    iconName: 'ShoppingBag',
    description: 'Supermarkets, neighborhood grocery, fashion boutiques, and specialty pharmacy.',
    businessTypes: [
      { id: 'retail_store', name: 'Retail Storefront & Supermarket' },
      { id: 'fashion_boutique', name: 'Fashion & Apparel Boutique' },
      { id: 'pharmacy_store', name: 'Pharmacy & Drugstore' },
      { id: 'electronics_store', name: 'Electronics & Gadgets' },
    ],
  },
  {
    key: 'AGENCY' as IndustryKey,
    name: 'Agencies & Professional Services',
    iconName: 'Palette',
    description: 'Creative design studios, marketing agencies, software dev shops, and consultancy.',
    businessTypes: [
      { id: 'creative_agency', name: 'Creative Agency & Consultancy' },
      { id: 'marketing_studio', name: 'Performance Marketing Agency' },
      { id: 'software_agency', name: 'Software Development Shop' },
      { id: 'management_consulting', name: 'Management Consulting Firm' },
    ],
  },
  {
    key: 'CONSTRUCTION' as IndustryKey,
    name: 'Construction & Contracting',
    iconName: 'Building2',
    description: 'General contractors, residential builders, MEP subcontractors, and heavy civils.',
    businessTypes: [
      { id: 'construction_contractor', name: 'General Contractor & Construction' },
      { id: 'residential_builder', name: 'Residential Home Builder' },
      { id: 'trade_subcontractor', name: 'Trade Subcontractor (HVAC/Electrical)' },
    ],
  },
  {
    key: 'SAAS' as IndustryKey,
    name: 'SaaS & Technology Cloud',
    iconName: 'Cpu',
    description: 'B2B subscription software, developer tooling platforms, and scale-ups.',
    businessTypes: [
      { id: 'saas_scaleup', name: 'B2B SaaS Scale-Up & Cloud Tech' },
      { id: 'devtool_platform', name: 'Developer Tooling & API Platform' },
    ],
  },
  {
    key: 'CUSTOM' as IndustryKey,
    name: 'Custom Bespoke Architecture',
    iconName: 'Layers',
    description: 'Assemble your own bespoke configuration from ground up with full control.',
    businessTypes: [
      { id: 'custom_bespoke', name: 'Custom Tailored Workspace' },
    ],
  },
  {
    key: 'LEGAL' as IndustryKey,
    name: 'Legal & Jurisdictional Practice',
    iconName: 'Scale',
    description: 'Law firms, litigation advocates, corporate counsel, and conveyancing solicitors.',
    businessTypes: [
      { id: 'legal_practice', name: 'Law Firm & Legal Practice' },
    ],
  },
  {
    key: 'LOGISTICS' as IndustryKey,
    name: 'Logistics, Freight & Fleet',
    iconName: 'Truck',
    description: 'Freight brokerages, 3PL warehouses, carrier fleets, and intermodal transport.',
    businessTypes: [
      { id: 'logistics_freight', name: 'Freight Brokerage & Fleet Logistics' },
    ],
  },
  {
    key: 'FITNESS' as IndustryKey,
    name: 'Fitness, Health & Athletics',
    iconName: 'Dumbbell',
    description: 'Health clubs, CrossFit boxes, yoga studios, and athletic centers.',
    businessTypes: [
      { id: 'fitness_gym', name: 'Gym Club & Fitness Studio' },
    ],
  },
  {
    key: 'AUTOMOTIVE' as IndustryKey,
    name: 'Automotive & Fleet Repair',
    iconName: 'Wrench',
    description: 'Mechanic service bays, collision repair shops, tire centers, and auto dealerships.',
    businessTypes: [
      { id: 'automotive_repair', name: 'Automotive Repair & Service Bay' },
    ],
  },
];
