/**
 * Enterprise CRM / Business OS Centralized Configuration & Port Directory
 * Synchronized across all 21 microservices and the web-core frontend.
 */

export const MICROSERVICE_PORTS = {
  crm: 3001,
  sales: 3005,
  platform: 3008,
  automation: 3009,
  ai: 3010,
  auth: 3011,
  marketplace: 3012,
  bi: 3013,
  chat: 3014,
  finance: 3015,
  helpdesk: 3016,
  projects: 3017,
  hr: 3018,
  search: 3019,
  documents: 3020,
  admin: 3021,
  developer: 3022,
  audit: 3023,
  cms: 3024,
  settings: 3025,
  inventory: 3026,
  python_ai: 3030,
  web: 4000,
} as const;

export type MicroserviceKey = keyof typeof MICROSERVICE_PORTS;
export type MicroservicePort = typeof MICROSERVICE_PORTS[MicroserviceKey];

export interface MicroserviceMetadata {
  key: MicroserviceKey;
  name: string;
  category: string;
  port: number;
  envVar: string;
  defaultUrl: string;
  description: string;
}

export const MICROSERVICES_METADATA: Record<MicroserviceKey, MicroserviceMetadata> = {
  crm: {
    key: 'crm',
    name: 'Customer & Contacts Mesh',
    category: 'Core CRM',
    port: 3001,
    envVar: 'CRM_PORT',
    defaultUrl: 'http://localhost:3001',
    description: 'Companies, contacts, leads, and customer 360 data layer',
  },
  sales: {
    key: 'sales',
    name: 'Sales Pipeline Engine',
    category: 'Commercial Deals',
    port: 3005,
    envVar: 'SALES_PORT',
    defaultUrl: 'http://localhost:3005',
    description: 'Deals pipeline, stages, revenue forecasting, quotes, and commissions',
  },
  platform: {
    key: 'platform',
    name: 'Platform Core & Custom Objects',
    category: 'Application Foundation',
    port: 3008,
    envVar: 'PLATFORM_PORT',
    defaultUrl: 'http://localhost:3008',
    description: 'Custom schemas, dynamic records, and platform metadata engine',
  },
  automation: {
    key: 'automation',
    name: 'Automation & Workflow Engine',
    category: 'Orchestration & BullMQ',
    port: 3009,
    envVar: 'AUTOMATION_PORT',
    defaultUrl: 'http://localhost:3009',
    description: 'Visual DAG flows, BullMQ task workers, webhooks, and event bus',
  },
  ai: {
    key: 'ai',
    name: 'Enterprise AI Engine',
    category: 'Intelligence & Copilots',
    port: 3010,
    envVar: 'AI_PORT',
    defaultUrl: 'http://localhost:3010',
    description: 'Multi-LLM agent orchestrator, embeddings, and autonomous actions',
  },
  auth: {
    key: 'auth',
    name: 'Identity & Auth Sentinel',
    category: 'Security & Access',
    port: 3011,
    envVar: 'AUTH_PORT',
    defaultUrl: 'http://localhost:3011',
    description: 'JWT issuance, user registration, multi-tenant workspace isolation',
  },
  marketplace: {
    key: 'marketplace',
    name: 'App Marketplace & Plugins',
    category: 'Integrations',
    port: 3012,
    envVar: 'MARKETPLACE_PORT',
    defaultUrl: 'http://localhost:3012',
    description: 'Third-party integrations, extensions, and plugin registry',
  },
  bi: {
    key: 'bi',
    name: 'Business Intelligence & Analytics',
    category: 'Reporting & OLAP',
    port: 3013,
    envVar: 'BI_PORT',
    defaultUrl: 'http://localhost:3013',
    description: 'Cohort metrics, revenue dashboards, and executive reporting',
  },
  chat: {
    key: 'chat',
    name: 'Team Chat & Real-Time Sync',
    category: 'Collaboration',
    port: 3014,
    envVar: 'CHAT_PORT',
    defaultUrl: 'http://localhost:3014',
    description: 'Socket.IO real-time channels, direct messages, and team chat',
  },
  finance: {
    key: 'finance',
    name: 'Finance & Treasury Hub',
    category: 'Ledger & Invoices',
    port: 3015,
    envVar: 'FINANCE_PORT',
    defaultUrl: 'http://localhost:3015',
    description: 'Invoices, recurring billing, payments, and financial ledger',
  },
  helpdesk: {
    key: 'helpdesk',
    name: 'Helpdesk & SLA Sentinel',
    category: 'Support Operations',
    port: 3016,
    envVar: 'HELPDESK_PORT',
    defaultUrl: 'http://localhost:3016',
    description: 'Tickets, customer support routing, SLA monitors, and KB',
  },
  projects: {
    key: 'projects',
    name: 'Sprint & Project Service',
    category: 'Project Tasks',
    port: 3017,
    envVar: 'PROJECTS_PORT',
    defaultUrl: 'http://localhost:3017',
    description: 'Agile sprints, Kanban boards, project tasks, and milestones',
  },
  hr: {
    key: 'hr',
    name: 'HR & Employee Vault',
    category: 'People Operations',
    port: 3018,
    envVar: 'HR_PORT',
    defaultUrl: 'http://localhost:3018',
    description: 'Employee directory, PTO/leave requests, and org charts',
  },
  search: {
    key: 'search',
    name: 'Universal Search Mesh',
    category: 'Multi-Entity Query',
    port: 3019,
    envVar: 'SEARCH_PORT',
    defaultUrl: 'http://localhost:3019',
    description: 'Omni-search index spanning all CRM and business entities',
  },
  documents: {
    key: 'documents',
    name: 'Document & OCR Storage',
    category: 'Document Management',
    port: 3020,
    envVar: 'DOCUMENTS_PORT',
    defaultUrl: 'http://localhost:3020',
    description: 'File vault, PDF attachments, contracts, and document metadata',
  },
  admin: {
    key: 'admin',
    name: 'Tenant Admin & Governance',
    category: 'Superadmin Console',
    port: 3021,
    envVar: 'ADMIN_PORT',
    defaultUrl: 'http://localhost:3021',
    description: 'Multi-tenant organization management, billing tiers, and seat quotas',
  },
  developer: {
    key: 'developer',
    name: 'Developer & Webhooks Gateway',
    category: 'APIs & Ecosystem',
    port: 3022,
    envVar: 'DEVELOPER_PORT',
    defaultUrl: 'http://localhost:3022',
    description: 'API keys, outgoing webhook subscriptions, and developer console',
  },
  audit: {
    key: 'audit',
    name: 'Audit & SOC2 Compliance',
    category: 'Governance Logs',
    port: 3023,
    envVar: 'AUDIT_PORT',
    defaultUrl: 'http://localhost:3023',
    description: 'Immutable change audit log, security events, and compliance export',
  },
  cms: {
    key: 'cms',
    name: 'Content & Marketing Hub',
    category: 'Content Management',
    port: 3024,
    envVar: 'CMS_PORT',
    defaultUrl: 'http://localhost:3024',
    description: 'Landing page copy, articles, email marketing templates',
  },
  settings: {
    key: 'settings',
    name: 'Tenant Settings & Preferences',
    category: 'Configuration',
    port: 3025,
    envVar: 'SETTINGS_PORT',
    defaultUrl: 'http://localhost:3025',
    description: 'Tenant branding, feature flags, regional currency, and preferences',
  },
  inventory: {
    key: 'inventory',
    name: 'Inventory & Stock Warehouse',
    category: 'Supply Chain',
    port: 3026,
    envVar: 'INVENTORY_PORT',
    defaultUrl: 'http://localhost:3026',
    description: 'Stock levels, SKUs, warehouse tracking, and reorder alerts',
  },
  python_ai: {
    key: 'python_ai',
    name: 'Python AI & ML Infrastructure Service',
    category: 'AI & Machine Learning',
    port: 3030,
    envVar: 'PYTHON_AI_PORT',
    defaultUrl: 'http://localhost:3030',
    description: 'FastAPI microservice for local model inference, 384-d vector embeddings, dataset generation, and LoRA training',
  },
  web: {
    key: 'web',
    name: 'Business OS Web Core',
    category: 'Frontend Application',
    port: 4000,
    envVar: 'PORT',
    defaultUrl: 'http://localhost:4000',
    description: 'Next.js 16 App Router UI shell, cockpit, and command center',
  },
};

export const config = {
  appName: 'Business OS',
  version: '1.0.0',
  ports: MICROSERVICE_PORTS,
  metadata: MICROSERVICES_METADATA,
  apiEndpoints: {
    crm: process.env.CRM_API_URL || 'http://localhost:3001',
    sales: process.env.SALES_API_URL || 'http://localhost:3005',
    platform: process.env.PLATFORM_API_URL || 'http://localhost:3008',
    automation: process.env.AUTOMATION_API_URL || 'http://localhost:3009',
    ai: process.env.AI_API_URL || 'http://localhost:3010',
    auth: process.env.AUTH_API_URL || 'http://localhost:3011',
    marketplace: process.env.MARKETPLACE_API_URL || 'http://localhost:3012',
    bi: process.env.BI_API_URL || 'http://localhost:3013',
    chat: process.env.CHAT_API_URL || 'http://localhost:3014',
    finance: process.env.FINANCE_API_URL || 'http://localhost:3015',
    helpdesk: process.env.HELPDESK_API_URL || 'http://localhost:3016',
    projects: process.env.PROJECTS_API_URL || 'http://localhost:3017',
    hr: process.env.HR_API_URL || 'http://localhost:3018',
    search: process.env.SEARCH_API_URL || 'http://localhost:3019',
    documents: process.env.DOCUMENTS_API_URL || 'http://localhost:3020',
    admin: process.env.ADMIN_API_URL || 'http://localhost:3021',
    developer: process.env.DEVELOPER_API_URL || 'http://localhost:3022',
    audit: process.env.AUDIT_API_URL || 'http://localhost:3023',
    cms: process.env.CMS_API_URL || 'http://localhost:3024',
    settings: process.env.SETTINGS_API_URL || 'http://localhost:3025',
    inventory: process.env.INVENTORY_API_URL || 'http://localhost:3026',
    web: process.env.WEB_URL || 'http://localhost:4000',
  },
};
