export type NodeCategory =
  | 'TRIGGERS'
  | 'LOGIC'
  | 'DATA'
  | 'TRANSFORM'
  | 'AI'
  | 'AGENTS'
  | 'CRM'
  | 'SALES'
  | 'RECRUITMENT'
  | 'SUPPORT'
  | 'FINANCE'
  | 'HR'
  | 'DOCUMENTS'
  | 'CALENDAR'
  | 'COMMUNICATION'
  | 'MARKETING'
  | 'SOCIAL'
  | 'E_COMMERCE'
  | 'VOICE'
  | 'WHATSAPP'
  | 'BROWSER'
  | 'DATABASE'
  | 'INTEGRATIONS'
  | 'HUMAN'
  | 'SYSTEM'
  | 'OUTPUT'
  // Backward compatibility category aliases
  | 'TRIGGER'
  | 'RECRUITMENT_AI'
  | 'CANDIDATE'
  | 'AI_AGENT'
  | 'EXTERNAL';

export interface WorkflowNodeDefinition {
  id?: string;
  type: string;
  category: NodeCategory;
  name?: string;
  title: string;
  subtitle: string;
  description: string;
  icon?: string;
  iconName: string;
  color?: string;
  badge: string;
  version?: string;
  inputSchema?: Record<string, any>;
  inputs: Array<{ name: string; type: string; required?: boolean; description?: string }>;
  outputSchema?: Record<string, any>;
  outputs: Array<{ name: string; type: string; description?: string }>;
  configSchema?: Record<string, any>;
  defaultConfig: Record<string, any>;
  permissions?: string[];
  riskLevel?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  executionHandler?: string;
  retryPolicy?: { maxRetries: number; backoffMs: number };
  timeout?: number; // seconds
  supportsAsync?: boolean;
  supportsBatch?: boolean;
  supportsLoop?: boolean;
  supportsApproval?: boolean;
}

export const NODE_CATALOG: WorkflowNodeDefinition[] = [
  // ==========================================
  // 1. TRIGGERS (Recruitment, Events, Webhooks, CRON)
  // ==========================================
  {
    type: 'trigger:candidate_applied',
    category: 'TRIGGERS',
    title: 'Candidate Applied',
    subtitle: 'Fires when an applicant submits a job application',
    description: 'Triggers workflow execution immediately upon new candidate application via career portal, job board, or LinkedIn.',
    iconName: 'UserCheck',
    badge: 'Recruitment Trigger',
    inputs: [],
    outputs: [
      { name: 'candidate', type: 'object', description: 'Candidate application payload with name, email, role, resumeUrl' },
      { name: 'jobId', type: 'string', description: 'ID of the applied job vacancy' },
    ],
    defaultConfig: { jobFilter: 'ALL', channel: 'PORTAL' },
    riskLevel: 'LOW',
    timeout: 30,
  },
  {
    type: 'trigger:resume_uploaded',
    category: 'TRIGGERS',
    title: 'Resume Uploaded',
    subtitle: 'Fires when a CV or resume file is deposited',
    description: 'Triggers when a resume file (PDF, DOCX, image) is uploaded to the document vault or recruiter inbox.',
    iconName: 'FileUp',
    badge: 'Doc Trigger',
    inputs: [],
    outputs: [
      { name: 'fileId', type: 'string', description: 'Vault document ID' },
      { name: 'fileName', type: 'string', description: 'Original filename' },
      { name: 'fileUrl', type: 'string', description: 'Secure storage path' },
    ],
    defaultConfig: { vaultFolder: '/vault/inbound/resumes/' },
    riskLevel: 'LOW',
    timeout: 30,
  },
  {
    type: 'trigger:job_created',
    category: 'TRIGGERS',
    title: 'New Job Created',
    subtitle: 'Fires when a new hiring requisition is published',
    description: 'Triggers workflow when a new job requisition or role requirement is authored.',
    iconName: 'Briefcase',
    badge: 'Job Trigger',
    inputs: [],
    outputs: [{ name: 'job', type: 'object', description: 'Complete job profile with title, skills, salary, location' }],
    defaultConfig: { departmentFilter: 'ALL' },
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:candidate_updated',
    category: 'TRIGGERS',
    title: 'Candidate Updated',
    subtitle: 'Fires on candidate profile or stage change',
    description: 'Triggers when candidate information or interview status changes in the database.',
    iconName: 'UserCog',
    badge: 'Candidate Event',
    inputs: [],
    outputs: [{ name: 'candidate', type: 'object', description: 'Updated candidate entity' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:candidate_responded',
    category: 'TRIGGERS',
    title: 'Candidate Responded',
    subtitle: 'Fires when candidate replies via email or WhatsApp',
    description: 'Captures incoming candidate replies, scheduling slot picks, or questionnaire answers.',
    iconName: 'MessageSquareReply',
    badge: 'Communication',
    inputs: [],
    outputs: [{ name: 'reply', type: 'object', description: 'Reply content, sentiment, and metadata' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:interview_completed',
    category: 'TRIGGERS',
    title: 'Interview Completed',
    subtitle: 'Fires when an interviewer submits feedback scorecard',
    description: 'Triggers when an interview finishes or the scorecard evaluation is submitted.',
    iconName: 'CalendarCheck',
    badge: 'Interview Event',
    inputs: [],
    outputs: [{ name: 'scorecard', type: 'object', description: 'Scorecard ratings and notes' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:interview_cancelled',
    category: 'TRIGGERS',
    title: 'Interview Cancelled',
    subtitle: 'Fires when a scheduled meeting is cancelled',
    description: 'Triggers automated cancellation protocols, recruiter alerts, and rescheduling flows.',
    iconName: 'CalendarX',
    badge: 'Interview Event',
    inputs: [],
    outputs: [{ name: 'cancellation', type: 'object', description: 'Cancellation reason and timestamp' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:interview_missed',
    category: 'TRIGGERS',
    title: 'Interview Missed (No-Show)',
    subtitle: 'Fires when candidate or interviewer fails to join',
    description: 'Triggers automated recovery, candidate re-engagement, or recruiter review.',
    iconName: 'CalendarAlert',
    badge: 'Interview Event',
    inputs: [],
    outputs: [{ name: 'incident', type: 'object', description: 'No-show telemetry and meeting metadata' }],
    defaultConfig: { graceMinutes: 10 },
    riskLevel: 'MEDIUM',
  },
  {
    type: 'trigger:email_received',
    category: 'TRIGGERS',
    title: 'Email Received',
    subtitle: 'Inbound message on recruitment or CRM inbox',
    description: 'Fires when an email arrives at a monitored recruiter inbox or shared address.',
    iconName: 'Mail',
    badge: 'Email Event',
    inputs: [],
    outputs: [{ name: 'email', type: 'object', description: 'Inbound email with sender, subject, body, attachments' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:whatsapp_received',
    category: 'TRIGGERS',
    title: 'WhatsApp Message Received',
    subtitle: 'Incoming chat on WhatsApp Business API',
    description: 'Fires when an applicant or lead sends a message, button reply, or document over WhatsApp.',
    iconName: 'MessageSquare',
    badge: 'WhatsApp',
    inputs: [],
    outputs: [{ name: 'whatsappMessage', type: 'object', description: 'WhatsApp message payload' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:schedule',
    category: 'TRIGGERS',
    title: 'CRON / Schedule Trigger',
    subtitle: 'Fires on scheduled recurrence',
    description: 'Fires on scheduled cadence (e.g. daily at 9:00 AM, hourly sweep, periodic dunning).',
    iconName: 'Clock',
    badge: 'Schedule',
    inputs: [],
    outputs: [{ name: 'timestamp', type: 'string', description: 'Execution timestamp' }],
    defaultConfig: { cron: '0 9 * * *' },
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:webhook',
    category: 'TRIGGERS',
    title: 'Inbound Webhook',
    subtitle: 'Dedicated HTTP POST endpoint',
    description: 'Provides a secure dedicated URL to receive payloads from external ATS, HRIS, or CRM systems.',
    iconName: 'Zap',
    badge: 'Webhook',
    inputs: [],
    outputs: [{ name: 'payload', type: 'object', description: 'Received webhook JSON payload' }],
    defaultConfig: { authRequired: true },
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:api_request',
    category: 'TRIGGERS',
    title: 'API Request',
    subtitle: 'Synchronous or async internal API dispatch',
    description: 'Invoked programmatically via Business OS SDK or internal service mesh.',
    iconName: 'Terminal',
    badge: 'API Event',
    inputs: [],
    outputs: [{ name: 'requestBody', type: 'object' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:manual',
    category: 'TRIGGERS',
    title: 'Manual Trigger',
    subtitle: 'Triggered by recruiter button click or test console',
    description: 'Allows manual dispatch from candidate profile, table row action, or studio runner.',
    iconName: 'Play',
    badge: 'Manual',
    inputs: [],
    outputs: [{ name: 'user', type: 'string' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'trigger:new_lead',
    category: 'TRIGGERS',
    title: 'New Lead Ingested',
    subtitle: 'Fires when a new prospect is ingested',
    description: 'Triggers workflow execution immediately after a new lead is detected in CRM.',
    iconName: 'UserPlus',
    badge: 'CRM Event',
    inputs: [],
    outputs: [{ name: 'lead', type: 'object' }],
    defaultConfig: { sourceFilter: 'ALL' },
    riskLevel: 'LOW',
  },

  // ==========================================
  // 2. DOCUMENT NODES (Resume, OCR, Parsing, Storage)
  // ==========================================
  {
    type: 'doc:resume_upload',
    category: 'DOCUMENTS',
    title: 'Resume Upload',
    subtitle: 'Uploads and validates resume document',
    description: 'Ingests applicant CV from file stream, multipart upload, or cloud storage into Smart Vault.',
    iconName: 'FileUp',
    badge: 'Vault Store',
    inputs: [{ name: 'fileData', type: 'any', required: true, description: 'File buffer, base64, or URL' }],
    outputs: [
      { name: 'documentId', type: 'string', description: 'Stored document reference' },
      { name: 'vaultPath', type: 'string', description: 'Internal file path' },
    ],
    defaultConfig: { allowedFormats: ['pdf', 'docx', 'txt'], maxSizeBytes: 10485760 },
    riskLevel: 'LOW',
    timeout: 30,
  },
  {
    type: 'doc:resume_parse',
    category: 'DOCUMENTS',
    title: 'Resume Parse',
    subtitle: 'Extracts full structured CV sections',
    description: 'Parses resume layout into contact details, work history, education, skills, and certifications.',
    iconName: 'FileSpreadsheet',
    badge: 'Parser',
    inputs: [{ name: 'documentId', type: 'string', required: true, description: 'Document ID or raw text' }],
    outputs: [
      { name: 'parsedResume', type: 'object', description: 'Structured resume data' },
      { name: 'candidateName', type: 'string' },
      { name: 'candidateEmail', type: 'string' },
      { name: 'skills', type: 'array' },
      { name: 'yearsExperience', type: 'number' },
    ],
    defaultConfig: { extractEducation: true, extractSkills: true, extractWorkHistory: true },
    riskLevel: 'LOW',
    timeout: 45,
  },
  {
    type: 'doc:pdf_extract',
    category: 'DOCUMENTS',
    title: 'PDF Stream Extraction',
    subtitle: 'Extracts raw text streams and tables from PDF',
    description: 'Decodes native PDF text streams, bounding boxes, and tabular structures without OCR loss.',
    iconName: 'FileText',
    badge: 'PDF Engine',
    inputs: [{ name: 'documentId', type: 'string', required: true }],
    outputs: [{ name: 'text', type: 'string' }, { name: 'pageCount', type: 'number' }],
    defaultConfig: {},
    riskLevel: 'LOW',
    timeout: 30,
  },
  {
    type: 'doc:docx_extract',
    category: 'DOCUMENTS',
    title: 'DOCX Word Extraction',
    subtitle: 'Extracts text and styles from Microsoft Word files',
    description: 'Reads XML streams of Word documents preserving headings, bullets, and paragraphs.',
    iconName: 'FileCode',
    badge: 'DOCX Engine',
    inputs: [{ name: 'documentId', type: 'string', required: true }],
    outputs: [{ name: 'text', type: 'string' }],
    defaultConfig: {},
    riskLevel: 'LOW',
    timeout: 30,
  },
  {
    type: 'doc:ocr',
    category: 'DOCUMENTS',
    title: 'Neural Vision OCR',
    subtitle: 'High-accuracy OCR for scanned documents',
    description: 'Uses Document Intelligence neural vision to transcribe scanned PDFs, images, and camera captures.',
    iconName: 'Scan',
    badge: 'Neural OCR',
    inputs: [{ name: 'documentId', type: 'string', required: true }],
    outputs: [{ name: 'text', type: 'string' }, { name: 'ocrConfidence', type: 'number' }],
    defaultConfig: { cleanConcatenatedText: true },
    riskLevel: 'LOW',
    timeout: 60,
  },
  {
    type: 'doc:classify',
    category: 'DOCUMENTS',
    title: 'Document Classification',
    subtitle: 'Identifies file type and category automatically',
    description: 'Categorizes incoming document into Resume, Portfolio, Offer Letter, NDA, or Certificate.',
    iconName: 'Layers',
    badge: 'Classifier',
    inputs: [{ name: 'documentId', type: 'string', required: true }],
    outputs: [{ name: 'documentCategory', type: 'string' }, { name: 'confidence', type: 'number' }],
    defaultConfig: { categories: ['RESUME', 'COVER_LETTER', 'PORTFOLIO', 'CERTIFICATE', 'IDENTIFICATION'] },
    riskLevel: 'LOW',
  },
  {
    type: 'doc:validate',
    category: 'DOCUMENTS',
    title: 'Document Validation',
    subtitle: 'Validates file integrity and authenticity',
    description: 'Verifies checksum, format standards, page limits, and checks for corrupted or password-protected files.',
    iconName: 'ShieldCheck',
    badge: 'Validator',
    inputs: [{ name: 'documentId', type: 'string', required: true }],
    outputs: [{ name: 'isValid', type: 'boolean' }, { name: 'validationErrors', type: 'array' }],
    defaultConfig: { checkPasswordProtection: true, maxPages: 20 },
    riskLevel: 'LOW',
  },
  {
    type: 'doc:search',
    category: 'DOCUMENTS',
    title: 'Document Search',
    subtitle: 'Searches enterprise document repository',
    description: 'Executes full-text and semantic search across previously archived resumes and candidate dossiers.',
    iconName: 'Search',
    badge: 'Doc Search',
    inputs: [{ name: 'query', type: 'string', required: true }],
    outputs: [{ name: 'documents', type: 'array' }],
    defaultConfig: { limit: 10 },
    riskLevel: 'LOW',
  },
  {
    type: 'doc:storage',
    category: 'DOCUMENTS',
    title: 'Document Storage',
    subtitle: 'Archives file into persistent Smart Vault',
    description: 'Attaches file to candidate record, applies retention policies, and updates document indices.',
    iconName: 'HardDrive',
    badge: 'Vault Store',
    inputs: [{ name: 'documentId', type: 'string', required: true }, { name: 'candidateId', type: 'string' }],
    outputs: [{ name: 'vaultLocation', type: 'string' }],
    defaultConfig: { targetFolder: '/vault/candidates/archive/' },
    riskLevel: 'LOW',
  },

  // ==========================================
  // 3. AI & SCREENING NODES (Screening, Matching, Scoring)
  // ==========================================
  {
    type: 'ai:extract_candidate_profile',
    category: 'AI',
    title: 'Extract Candidate Profile',
    subtitle: 'Extracts full candidate profile into normalized schema',
    description: 'Transforms unstructured CV text into a verified candidate profile object with work milestones.',
    iconName: 'UserCheck',
    badge: 'Candidate AI',
    inputs: [{ name: 'resumeText', type: 'string', required: true }],
    outputs: [
      { name: 'profile', type: 'object', description: 'Structured candidate profile' },
      { name: 'fullName', type: 'string' },
      { name: 'email', type: 'string' },
      { name: 'phone', type: 'string' },
      { name: 'currentTitle', type: 'string' },
      { name: 'totalExperienceYears', type: 'number' },
      { name: 'topSkills', type: 'array' },
    ],
    defaultConfig: {},
    riskLevel: 'LOW',
    timeout: 30,
  },
  {
    type: 'ai:extract_job_requirements',
    category: 'AI',
    title: 'Extract Job Requirements',
    subtitle: 'Parses JD into weighted criteria and must-haves',
    description: 'Analyzes Job Description to extract essential requirements, preferred qualifications, and seniority level.',
    iconName: 'FileCheck',
    badge: 'JD Intelligence',
    inputs: [{ name: 'jobDescription', type: 'string', required: true }],
    outputs: [
      { name: 'requiredSkills', type: 'array' },
      { name: 'preferredSkills', type: 'array' },
      { name: 'minExperienceYears', type: 'number' },
      { name: 'seniorityLevel', type: 'string' },
    ],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'ai:extract_required_skills',
    category: 'RECRUITMENT',
    title: 'Extract Required Skills',
    subtitle: 'Extracts core non-negotiable competencies',
    description: 'Isolates mandatory tech stack and domain skills from vacancy requisition.',
    iconName: 'CheckSquare',
    badge: 'Skill Extractor',
    inputs: [{ name: 'jobDescription', type: 'string', required: true }],
    outputs: [{ name: 'mandatorySkills', type: 'array' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'ai:extract_preferred_skills',
    category: 'RECRUITMENT',
    title: 'Extract Preferred Skills',
    subtitle: 'Extracts bonus and nice-to-have capabilities',
    description: 'Detects secondary skills that provide competitive advantage for applicants.',
    iconName: 'Award',
    badge: 'Bonus Skills',
    inputs: [{ name: 'jobDescription', type: 'string', required: true }],
    outputs: [{ name: 'preferredSkills', type: 'array' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'ai:experience_analysis',
    category: 'RECRUITMENT',
    title: 'Experience Analysis',
    subtitle: 'Analyzes career trajectory and domain depth',
    description: 'Examines career progression, tenure per company, team leadership signals, and scope of impact.',
    iconName: 'TrendingUp',
    badge: 'Career Depth',
    inputs: [{ name: 'workHistory', type: 'array', required: true }],
    outputs: [
      { name: 'progressionPattern', type: 'string' },
      { name: 'averageTenureMonths', type: 'number' },
      { name: 'leadershipSignals', type: 'boolean' },
      { name: 'experienceSummary', type: 'string' },
    ],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'ai:education_analysis',
    category: 'RECRUITMENT',
    title: 'Education Analysis',
    subtitle: 'Verifies degree requirements and academic relevance',
    description: 'Checks educational qualifications against role prerequisites while honoring equivalent practical experience.',
    iconName: 'GraduationCap',
    badge: 'Academic',
    inputs: [{ name: 'education', type: 'array', required: true }, { name: 'requiredDegree', type: 'string' }],
    outputs: [{ name: 'educationMet', type: 'boolean' }, { name: 'highestDegree', type: 'string' }],
    defaultConfig: { acceptEquivalentExperience: true },
    riskLevel: 'LOW',
  },
  {
    type: 'ai:skill_matching',
    category: 'RECRUITMENT',
    title: 'Skill Matching Engine',
    subtitle: 'Computes semantic overlap between skills and JD',
    description: 'Matches candidate proficiencies against job tech stack with fuzzy synonyms and semantic taxonomy.',
    iconName: 'GitMerge',
    badge: 'Skill Matcher',
    inputs: [
      { name: 'candidateSkills', type: 'array', required: true },
      { name: 'jobSkills', type: 'array', required: true },
    ],
    outputs: [
      { name: 'skillMatchScore', type: 'number' },
      { name: 'matchedSkills', type: 'array' },
      { name: 'missingSkills', type: 'array' },
    ],
    defaultConfig: { minimumThreshold: 60 },
    riskLevel: 'LOW',
  },
  {
    type: 'ai:candidate_screening',
    category: 'RECRUITMENT',
    title: 'Candidate Screening Engine',
    subtitle: 'Holistic multi-factor candidate fit evaluation',
    description: 'Evaluates applicant against JD across skills, experience, and deliverables. Returns structured explainable criteria.',
    iconName: 'Sparkles',
    badge: 'AI Screening',
    inputs: [
      { name: 'candidateProfile', type: 'object', required: true },
      { name: 'jobRequirements', type: 'object', required: true },
    ],
    outputs: [
      { name: 'candidateScore', type: 'number', description: 'Overall fit score (0-100)' },
      { name: 'matchedRequirements', type: 'array' },
      { name: 'missingRequirements', type: 'array' },
      { name: 'strengths', type: 'array' },
      { name: 'concerns', type: 'array' },
      { name: 'summary', type: 'string' },
      { name: 'recommendation', type: 'string', description: 'SHORTLIST | HUMAN_REVIEW | REJECT' },
    ],
    defaultConfig: {
      antiBiasEnabled: true,
      strictness: 'BALANCED', // STRICT, BALANCED, LENIENT
      passingThreshold: 75,
    },
    riskLevel: 'MEDIUM',
    timeout: 45,
  },
  {
    type: 'ai:candidate_scoring',
    category: 'RECRUITMENT',
    title: 'Candidate Scoring Matrix',
    subtitle: 'Calculates normalized numerical score (0-100)',
    description: 'Computes objective score with weighted components: Skills (40%), Experience (35%), Domain (25%).',
    iconName: 'Award',
    badge: 'Score Matrix',
    inputs: [{ name: 'candidate', type: 'object', required: true }],
    outputs: [
      { name: 'candidateScore', type: 'number' },
      { name: 'tier', type: 'string', description: 'TIER_1_TOP | TIER_2_STRONG | TIER_3_MARGINAL | TIER_4_BELOW' },
    ],
    defaultConfig: { skillsWeight: 0.4, experienceWeight: 0.35, domainWeight: 0.25 },
    riskLevel: 'LOW',
  },
  {
    type: 'ai:candidate_classification',
    category: 'RECRUITMENT',
    title: 'Candidate Classification',
    subtitle: 'Segments candidate into seniority and archetype',
    description: 'Classifies candidate archetype (e.g. Lead Architect, Specialist IC, Generalist, Junior Contributor).',
    iconName: 'Tag',
    badge: 'Archetype',
    inputs: [{ name: 'candidate', type: 'object', required: true }],
    outputs: [{ name: 'archetype', type: 'string' }, { name: 'level', type: 'string' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'ai:candidate_summary',
    category: 'RECRUITMENT',
    title: 'Recruiter Executive Summary',
    subtitle: 'Generates concise 3-bullet recruiter dossier',
    description: 'Synthesizes resume, achievements, and scoring into an actionable brief for hiring managers.',
    iconName: 'FileText',
    badge: 'Dossier',
    inputs: [{ name: 'candidate', type: 'object', required: true }],
    outputs: [{ name: 'executiveSummary', type: 'string' }, { name: 'interviewQuestions', type: 'array' }],
    defaultConfig: { bulletCount: 3, generateTailoredQuestions: true },
    riskLevel: 'LOW',
  },
  {
    type: 'ai:duplicate_detection',
    category: 'RECRUITMENT',
    title: 'Duplicate Candidate Detection',
    subtitle: 'Detects previous applications and existing records',
    description: 'Checks email, phone, and name similarities against historical applicants to prevent duplicate records.',
    iconName: 'Copy',
    badge: 'Deduplicator',
    inputs: [{ name: 'candidate', type: 'object', required: true }],
    outputs: [
      { name: 'isDuplicate', type: 'boolean' },
      { name: 'existingCandidateId', type: 'string' },
      { name: 'matchConfidence', type: 'number' },
    ],
    defaultConfig: { emailExactMatch: true, nameFuzzyThreshold: 0.9 },
    riskLevel: 'LOW',
  },
  {
    type: 'ai:missing_info_detection',
    category: 'RECRUITMENT',
    title: 'Missing Information Detection',
    subtitle: 'Detects missing portfolio, phone, or work authorization',
    description: 'Identifies missing prerequisite data so automated follow-up can request it immediately.',
    iconName: 'AlertCircle',
    badge: 'Completeness',
    inputs: [{ name: 'candidate', type: 'object', required: true }],
    outputs: [{ name: 'hasMissingFields', type: 'boolean' }, { name: 'missingFields', type: 'array' }],
    defaultConfig: { checkPhone: true, checkWorkAuthorization: true, checkGithub: false },
    riskLevel: 'LOW',
  },
  {
    type: 'ai:recruitment_agent',
    category: 'RECRUITMENT',
    title: 'AI Recruitment Autonomous Agent',
    subtitle: 'Specialized agent that handles full screening and decisions',
    description: 'Autonomous recruitment copilot that reasons over candidate data, runs screening tools, and recommends actions.',
    iconName: 'Bot',
    badge: 'Autonomous AI',
    inputs: [{ name: 'candidate', type: 'object', required: true }, { name: 'jobId', type: 'string' }],
    outputs: [
      { name: 'decision', type: 'string' },
      { name: 'candidateScore', type: 'number' },
      { name: 'toolsExecuted', type: 'array' },
      { name: 'explanation', type: 'string' },
    ],
    defaultConfig: { model: 'groq/llama-3.3-70b-versatile', temperature: 0.1, autoAdvanceScore: 80 },
    riskLevel: 'HIGH',
    timeout: 60,
  },

  // ==========================================
  // 4. LOGIC NODES (Branching, Comparison, Gates, Loops)
  // ==========================================
  {
    type: 'logic:if_else',
    category: 'LOGIC',
    title: 'IF / ELSE Condition',
    subtitle: 'Branches flow into TRUE and FALSE paths',
    description: 'Evaluates variable condition (e.g. score >= 75) and directs execution to True or False branch.',
    iconName: 'GitFork',
    badge: 'Branch Gate',
    inputs: [{ name: 'value', type: 'any' }],
    outputs: [
      { name: 'true', type: 'branch', description: 'Evaluated true branch' },
      { name: 'false', type: 'branch', description: 'Evaluated false branch' },
    ],
    defaultConfig: { field: 'candidateScore', operator: 'GREATER_THAN_OR_EQUAL', value: 75 },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:score_above',
    category: 'LOGIC',
    title: 'SCORE ABOVE Threshold',
    subtitle: 'Shorthand gate for score >= threshold',
    description: 'Routes candidate to pass branch if candidateScore or leadScore meets or exceeds threshold.',
    iconName: 'ArrowUpRight',
    badge: 'Score Gate',
    inputs: [{ name: 'candidateScore', type: 'number' }],
    outputs: [
      { name: 'pass', type: 'branch' },
      { name: 'fail', type: 'branch' },
    ],
    defaultConfig: { threshold: 75 },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:score_below',
    category: 'LOGIC',
    title: 'SCORE BELOW Threshold',
    subtitle: 'Shorthand gate for score < threshold',
    description: 'Routes candidate to rejection or human review branch if score is under threshold.',
    iconName: 'ArrowDownRight',
    badge: 'Score Gate',
    inputs: [{ name: 'candidateScore', type: 'number' }],
    outputs: [
      { name: 'below', type: 'branch' },
      { name: 'above', type: 'branch' },
    ],
    defaultConfig: { threshold: 50 },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:switch',
    category: 'LOGIC',
    title: 'SWITCH / Case',
    subtitle: 'Multi-branch router based on variable value',
    description: 'Evaluates string variable (e.g. recommendation = SHORTLIST | REVIEW | REJECT) into dedicated handles.',
    iconName: 'GitBranch',
    badge: 'Router',
    inputs: [{ name: 'variable', type: 'string' }],
    outputs: [{ name: 'branches', type: 'array' }],
    defaultConfig: {
      key: 'recommendation',
      cases: [
        { value: 'SHORTLIST', handle: 'shortlist' },
        { value: 'HUMAN_REVIEW', handle: 'review' },
        { value: 'REJECT', handle: 'reject' },
      ],
    },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:filter',
    category: 'LOGIC',
    title: 'FILTER Array Items',
    subtitle: 'Filters collection matching specific predicate',
    description: 'Filters list of candidates, applications, or files based on criteria.',
    iconName: 'Filter',
    badge: 'Filter',
    inputs: [{ name: 'items', type: 'array', required: true }],
    outputs: [{ name: 'filteredItems', type: 'array' }],
    defaultConfig: { field: 'score', operator: '>=', value: 70 },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:compare',
    category: 'LOGIC',
    title: 'COMPARE Two Variables',
    subtitle: 'Compares dynamic value A against dynamic value B',
    description: 'Checks equality, greater than, or difference between two runtime context variables.',
    iconName: 'ArrowRightLeft',
    badge: 'Comparator',
    inputs: [{ name: 'varA', type: 'any' }, { name: 'varB', type: 'any' }],
    outputs: [{ name: 'isMatch', type: 'boolean' }],
    defaultConfig: { operator: 'EQUALS' },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:and',
    category: 'LOGIC',
    title: 'AND Gate',
    subtitle: 'Requires all upstream inputs to be satisfied',
    description: 'Continues execution only when all prerequisites evaluate to true.',
    iconName: 'Sliders',
    badge: 'Gate',
    inputs: [],
    outputs: [{ name: 'passed', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'logic:or',
    category: 'LOGIC',
    title: 'OR Gate',
    subtitle: 'Satisfied if any upstream input passes',
    description: 'Continues execution when at least one condition evaluates to true.',
    iconName: 'Sliders',
    badge: 'Gate',
    inputs: [],
    outputs: [{ name: 'passed', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'logic:not',
    category: 'LOGIC',
    title: 'NOT Inverter',
    subtitle: 'Inverts boolean flag',
    description: 'Turns true to false and false to true.',
    iconName: 'X',
    badge: 'Inverter',
    inputs: [{ name: 'input', type: 'boolean' }],
    outputs: [{ name: 'output', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'logic:loop',
    category: 'LOGIC',
    title: 'LOOP Controller',
    subtitle: 'Iterates through array of items with guardrail',
    description: 'Executes child branch for each item up to configured max iterations.',
    iconName: 'RotateCw',
    badge: 'Loop',
    inputs: [{ name: 'items', type: 'array', required: true }],
    outputs: [{ name: 'currentItem', type: 'any' }, { name: 'done', type: 'branch' }],
    defaultConfig: { maxIterations: 50 },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:for_each',
    category: 'LOGIC',
    title: 'FOR EACH Iteration',
    subtitle: 'Processes each element in list',
    description: 'Iterates through candidates or documents, applying subsequent nodes to each.',
    iconName: 'ListOrdered',
    badge: 'Iterator',
    inputs: [{ name: 'list', type: 'array', required: true }],
    outputs: [{ name: 'item', type: 'any' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'logic:split',
    category: 'LOGIC',
    title: 'SPLIT Parallel Branches',
    subtitle: 'Forks execution into multiple concurrent branches',
    description: 'Launches parallel independent workflow branches simultaneously.',
    iconName: 'GitFork',
    badge: 'Parallel',
    inputs: [],
    outputs: [{ name: 'branches', type: 'array' }],
    defaultConfig: { branchCount: 2 },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:merge',
    category: 'LOGIC',
    title: 'MERGE Branches',
    subtitle: 'Synchronizes parallel branches before continuing',
    description: 'Waits for all inbound parallel branches to complete before advancing.',
    iconName: 'GitMerge',
    badge: 'Join',
    inputs: [],
    outputs: [{ name: 'merged', type: 'boolean' }],
    defaultConfig: { waitAll: true },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:delay',
    category: 'LOGIC',
    title: 'DELAY Timer',
    subtitle: 'Pauses workflow execution for defined duration',
    description: 'Waits specified minutes, hours, or days before executing follow-up step.',
    iconName: 'Hourglass',
    badge: 'Delay',
    inputs: [],
    outputs: [{ name: 'resumed', type: 'boolean' }],
    defaultConfig: { duration: 2, unit: 'DAYS' },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:wait_for_event',
    category: 'LOGIC',
    title: 'WAIT for Event',
    subtitle: 'Suspends workflow until external callback or response arrives',
    description: 'Puts execution in WAITING state until applicant books interview or replies.',
    iconName: 'Clock',
    badge: 'Wait State',
    inputs: [],
    outputs: [{ name: 'eventPayload', type: 'object' }],
    defaultConfig: { eventName: 'candidate.responded', timeoutMinutes: 2880 },
    riskLevel: 'LOW',
  },
  {
    type: 'logic:stop',
    category: 'LOGIC',
    title: 'STOP Workflow',
    subtitle: 'Terminates workflow gracefully',
    description: 'Concludes execution without marking as failure (e.g. candidate disqualified or opted out).',
    iconName: 'Square',
    badge: 'Terminator',
    inputs: [],
    outputs: [],
    defaultConfig: { reason: 'DISQUALIFIED' },
    riskLevel: 'LOW',
  },

  // ==========================================
  // 5. CANDIDATE ACTION NODES
  // ==========================================
  // 5. CRM & RECRUITMENT ACTION NODES
  // ==========================================
  {
    type: 'candidate:create',
    category: 'CRM',
    title: 'Create Candidate Record',
    subtitle: 'Creates new candidate record in CRM database',
    description: 'Persists applicant contact details, applied role, resume reference, and custom metadata.',
    iconName: 'UserPlus',
    badge: 'Candidate CRM',
    inputs: [
      { name: 'name', type: 'string', required: true },
      { name: 'email', type: 'string', required: true },
      { name: 'appliedRole', type: 'string' },
    ],
    outputs: [{ name: 'candidateId', type: 'string' }],
    defaultConfig: { stage: 'APPLIED', source: 'WORKFLOW' },
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:update',
    category: 'CRM',
    title: 'Update Candidate',
    subtitle: 'Updates fields on existing candidate profile',
    description: 'Mutates candidate record with new contact info, scoring data, or screening notes.',
    iconName: 'UserCheck',
    badge: 'Candidate CRM',
    inputs: [{ name: 'candidateId', type: 'string', required: true }, { name: 'fields', type: 'object' }],
    outputs: [{ name: 'updated', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:move_stage',
    category: 'CANDIDATE',
    title: 'Move Candidate Stage',
    subtitle: 'Advances candidate along hiring pipeline',
    description: 'Transitions applicant stage: Applied -> Screening -> Shortlisted -> Interview -> Offer -> Hired.',
    iconName: 'ArrowRight',
    badge: 'Pipeline',
    inputs: [{ name: 'candidateId', type: 'string', required: true }],
    outputs: [{ name: 'newStage', type: 'string' }],
    defaultConfig: { targetStage: 'SHORTLISTED' },
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:assign_recruiter',
    category: 'CANDIDATE',
    title: 'Assign Recruiter',
    subtitle: 'Assigns hiring specialist or recruiter owner',
    description: 'Routes applicant to designated recruiter based on department, location, or round-robin balance.',
    iconName: 'UserCheck',
    badge: 'Assignment',
    inputs: [{ name: 'candidateId', type: 'string', required: true }],
    outputs: [{ name: 'recruiterId', type: 'string' }],
    defaultConfig: { method: 'ROUND_ROBIN' },
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:add_tag',
    category: 'CANDIDATE',
    title: 'Add Candidate Tag',
    subtitle: 'Attaches searchable tag or badge to candidate',
    description: 'Appends tags such as "Top Candidate", "High Fit", "Visa Sponsored", or "Immediate Joiner".',
    iconName: 'Tag',
    badge: 'Tagger',
    inputs: [{ name: 'candidateId', type: 'string', required: true }],
    outputs: [{ name: 'tags', type: 'array' }],
    defaultConfig: { tag: 'TOP_TALENT' },
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:remove_tag',
    category: 'CANDIDATE',
    title: 'Remove Candidate Tag',
    subtitle: 'Removes designated tag from candidate profile',
    description: 'Detaches labels when stage or eligibility changes.',
    iconName: 'Tag',
    badge: 'Tagger',
    inputs: [{ name: 'candidateId', type: 'string', required: true }],
    outputs: [{ name: 'remainingTags', type: 'array' }],
    defaultConfig: { tag: 'UNREVIEWED' },
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:add_note',
    category: 'CANDIDATE',
    title: 'Add Candidate Note',
    subtitle: 'Appends evaluation note to candidate timeline',
    description: 'Writes structured AI feedback, recruiter comments, or screening scorecard to candidate feed.',
    iconName: 'FileText',
    badge: 'Timeline',
    inputs: [{ name: 'candidateId', type: 'string', required: true }, { name: 'noteContent', type: 'string' }],
    outputs: [{ name: 'noteId', type: 'string' }],
    defaultConfig: { title: 'Automated AI Screening Note' },
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:create_task',
    category: 'CANDIDATE',
    title: 'Create Recruiter Task',
    subtitle: 'Schedules action item for hiring team member',
    description: 'Creates task in CRM for phone screen, reference verification, or offer letter preparation.',
    iconName: 'CheckSquare',
    badge: 'Task',
    inputs: [{ name: 'candidateId', type: 'string' }, { name: 'taskTitle', type: 'string' }],
    outputs: [{ name: 'taskId', type: 'string' }],
    defaultConfig: { title: 'Conduct Technical Phone Screen', dueHours: 48 },
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:shortlist',
    category: 'CANDIDATE',
    title: 'Shortlist Candidate',
    subtitle: 'Marks candidate as shortlisted for interview rounds',
    description: 'Advances candidate to Shortlisted state, updates dashboard metrics, and alerts recruitment team.',
    iconName: 'CheckCircle2',
    badge: 'Shortlist',
    inputs: [{ name: 'candidateId', type: 'string', required: true }],
    outputs: [{ name: 'isShortlisted', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:reject',
    category: 'CANDIDATE',
    title: 'Reject Candidate',
    subtitle: 'Marks candidate as rejected with reason',
    description: 'Updates candidate status to REJECTED with explainable feedback reason recorded in audit log.',
    iconName: 'XCircle',
    badge: 'Rejection',
    inputs: [{ name: 'candidateId', type: 'string', required: true }],
    outputs: [{ name: 'isRejected', type: 'boolean' }],
    defaultConfig: { reason: 'REQUIREMENTS_NOT_MET', sendRejectionEmail: false },
    riskLevel: 'MEDIUM',
  },
  {
    type: 'candidate:archive',
    category: 'CANDIDATE',
    title: 'Archive Candidate',
    subtitle: 'Retires profile into historical talent pool',
    description: 'Removes applicant from active pipeline while preserving profile for future matching.',
    iconName: 'Archive',
    badge: 'Archive',
    inputs: [{ name: 'candidateId', type: 'string', required: true }],
    outputs: [{ name: 'isArchived', type: 'boolean' }],
    defaultConfig: { talentPool: 'FUTURE_CONSIDERATION' },
    riskLevel: 'LOW',
  },
  {
    type: 'candidate:request_review',
    category: 'CANDIDATE',
    title: 'Request Human Review',
    subtitle: 'Flags candidate for manual recruiter verification',
    description: 'Sends candidate dossier to human review queue when scoring is borderline.',
    iconName: 'ShieldAlert',
    badge: 'Human Review',
    inputs: [{ name: 'candidateId', type: 'string', required: true }],
    outputs: [{ name: 'reviewRequestId', type: 'string' }],
    defaultConfig: { urgency: 'MEDIUM' },
    riskLevel: 'MEDIUM',
  },

  // ==========================================
  // 6. COMMUNICATION NODES (Email, WhatsApp, SMS, Invites)
  // ==========================================
  {
    type: 'comm:email',
    category: 'COMMUNICATION',
    title: 'Send Email',
    subtitle: 'Dispatches templated email with dynamic variables',
    description: 'Sends email via Resend integration supporting dynamic variables like {{candidate.firstName}}.',
    iconName: 'Mail',
    badge: 'Email',
    inputs: [
      { name: 'to', type: 'string', required: true },
      { name: 'subject', type: 'string', required: true },
      { name: 'body', type: 'string', required: true },
    ],
    outputs: [{ name: 'messageId', type: 'string' }, { name: 'emailSent', type: 'boolean' }],
    defaultConfig: {
      to: '{{candidate.email}}',
      subject: 'Update regarding your application for {{job.title}}',
      body: 'Hi {{candidate.firstName}},\n\nThank you for applying for {{job.title}} at our company.',
    },
    riskLevel: 'LOW',
  },
  {
    type: 'comm:whatsapp',
    category: 'WHATSAPP',
    title: 'Send WhatsApp',
    subtitle: 'Sends WhatsApp message or interactive button card',
    description: 'Dispatches instant mobile notification over WhatsApp Business API Cloud / Twilio.',
    iconName: 'MessageSquare',
    badge: 'WhatsApp',
    inputs: [{ name: 'to', type: 'string', required: true }, { name: 'message', type: 'string', required: true }],
    outputs: [{ name: 'whatsappSent', type: 'boolean' }, { name: 'messageId', type: 'string' }],
    defaultConfig: {
      to: '{{candidate.phone}}',
      message: 'Hi {{candidate.firstName}}! Your application for {{job.title}} has been reviewed.',
    },
    riskLevel: 'LOW',
  },
  {
    type: 'whatsapp:message_received',
    category: 'WHATSAPP',
    title: 'WhatsApp Message Received',
    subtitle: 'Fires when customer sends inbound WhatsApp message',
    description: 'Triggers conversational flow or routing upon incoming message from WhatsApp Cloud API.',
    iconName: 'MessageSquare',
    badge: 'WhatsApp Trigger',
    inputs: [],
    outputs: [
      { name: 'senderPhone', type: 'string' },
      { name: 'messageText', type: 'string' },
      { name: 'mediaUrl', type: 'string' },
    ],
    defaultConfig: {},
    riskLevel: 'LOW',
    timeout: 10,
  },
  {
    type: 'whatsapp:send_template',
    category: 'WHATSAPP',
    title: 'Send WhatsApp Template',
    subtitle: 'Dispatches pre-approved Meta WhatsApp HSM template',
    description: 'Sends official HSM utility or marketing template with variable parameters to customer.',
    iconName: 'MessageSquare',
    badge: 'WhatsApp HSM',
    inputs: [
      { name: 'to', type: 'string', required: true },
      { name: 'templateName', type: 'string', required: true },
      { name: 'parameters', type: 'object' },
    ],
    outputs: [{ name: 'whatsappSent', type: 'boolean' }, { name: 'messageId', type: 'string' }],
    defaultConfig: { templateName: 'appointment_confirmation' },
    riskLevel: 'LOW',
    timeout: 15,
  },
  {
    type: 'comm:sms',
    category: 'COMMUNICATION',
    title: 'Send SMS',
    subtitle: 'Direct mobile text alert',
    description: 'Dispatches urgent SMS alert to candidate mobile number.',
    iconName: 'Smartphone',
    badge: 'SMS',
    inputs: [{ name: 'to', type: 'string', required: true }, { name: 'text', type: 'string', required: true }],
    outputs: [{ name: 'smsSent', type: 'boolean' }],
    defaultConfig: { to: '{{candidate.phone}}', text: 'Hi {{candidate.firstName}}, please check your email for your interview invite.' },
    riskLevel: 'LOW',
  },
  {
    type: 'comm:interview_invitation',
    category: 'COMMUNICATION',
    title: 'Send Interview Invitation',
    subtitle: 'Dispatches formal interview invite with self-scheduler link',
    description: 'Invites candidate to select an interview slot from available calendar times.',
    iconName: 'CalendarPlus',
    badge: 'Invitation',
    inputs: [{ name: 'candidateEmail', type: 'string' }, { name: 'jobTitle', type: 'string' }],
    outputs: [{ name: 'invitationSent', type: 'boolean' }, { name: 'bookingLink', type: 'string' }],
    defaultConfig: {
      subject: 'Interview Invitation: {{job.title}} at Business OS',
      includeCalendarSlots: true,
      senderName: 'Talent Acquisition Team',
    },
    riskLevel: 'LOW',
  },
  {
    type: 'comm:rejection',
    category: 'COMMUNICATION',
    title: 'Send Rejection Email',
    subtitle: 'Sends respectful candidate disqualification email',
    description: 'Dispatches courteous, compliant notification letting candidate know they were not selected.',
    iconName: 'UserX',
    badge: 'Disposition',
    inputs: [{ name: 'to', type: 'string', required: true }],
    outputs: [{ name: 'rejectionSent', type: 'boolean' }],
    defaultConfig: {
      subject: 'Your application for {{job.title}}',
      body: 'Hi {{candidate.firstName}},\n\nThank you for speaking with us. While your background is impressive, we have decided to move forward with other candidates whose experience more closely matches our current needs.',
    },
    riskLevel: 'LOW',
  },
  {
    type: 'comm:follow_up',
    category: 'COMMUNICATION',
    title: 'Send Follow-up',
    subtitle: 'Gentle nudge for pending candidate response',
    description: 'Reminds applicant to complete scheduling or upload missing documents.',
    iconName: 'Clock',
    badge: 'Follow-up',
    inputs: [{ name: 'candidateEmail', type: 'string' }],
    outputs: [{ name: 'followUpSent', type: 'boolean' }],
    defaultConfig: {
      subject: 'Following up: Interview scheduling for {{job.title}}',
      message: 'Hi {{candidate.firstName}}, we would love to connect. Please pick a slot on our calendar.',
    },
    riskLevel: 'LOW',
  },
  {
    type: 'comm:reminder',
    category: 'COMMUNICATION',
    title: 'Send Reminder',
    subtitle: 'Pre-interview 24h / 1h reminder alert',
    description: 'Sends automated reminder prior to scheduled video or on-site interview with meeting link.',
    iconName: 'Bell',
    badge: 'Reminder',
    inputs: [{ name: 'interviewId', type: 'string' }],
    outputs: [{ name: 'reminderSent', type: 'boolean' }],
    defaultConfig: { sendVia: 'ALL', leadTimeHours: 24 },
    riskLevel: 'LOW',
  },
  {
    type: 'comm:custom_message',
    category: 'COMMUNICATION',
    title: 'Send Custom Message',
    subtitle: 'Dynamic multi-channel notification',
    description: 'Routes message to candidate preferred communication channel (Email, WhatsApp, or SMS).',
    iconName: 'MessageCircle',
    badge: 'Omnichannel',
    inputs: [{ name: 'channel', type: 'string' }, { name: 'message', type: 'string' }],
    outputs: [{ name: 'delivered', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'comm:ai_generate_message',
    category: 'COMMUNICATION',
    title: 'AI Generate Message',
    subtitle: 'Generates personalized email or chat tailored to candidate CV',
    description: 'Uses LLM to author personalized outreach highlighting candidate specific projects and achievements.',
    iconName: 'Wand2',
    badge: 'AI Copywriter',
    inputs: [{ name: 'candidateProfile', type: 'object' }, { name: 'tone', type: 'string' }],
    outputs: [{ name: 'generatedMessage', type: 'string' }],
    defaultConfig: { tone: 'PROFESSIONAL_WARM', length: 'SHORT' },
    riskLevel: 'LOW',
  },

  // ==========================================
  // 7. CALENDAR NODES (Availability, Bookings, No-Shows)
  // ==========================================
  {
    type: 'calendar:check_availability',
    category: 'CALENDAR',
    title: 'Check Availability',
    subtitle: 'Queries calendar system for open appointment windows',
    description: 'Finds available interview slots matching recruiter or hiring panel working hours.',
    iconName: 'CalendarSearch',
    badge: 'Schedule Engine',
    inputs: [{ name: 'interviewerId', type: 'string' }, { name: 'rangeDays', type: 'number' }],
    outputs: [{ name: 'availableSlots', type: 'array' }, { name: 'slotCount', type: 'number' }],
    defaultConfig: { rangeDays: 7, slotDurationMinutes: 45 },
    riskLevel: 'LOW',
  },
  {
    type: 'calendar:interviewer_availability',
    category: 'CALENDAR',
    title: 'Find Interviewer Availability',
    subtitle: 'Fetches free slots for specific hiring manager',
    description: 'Looks up busy/free blocks from Google Calendar, Outlook, or Cal.com.',
    iconName: 'UserCheck',
    badge: 'Interviewer',
    inputs: [{ name: 'interviewerEmail', type: 'string' }],
    outputs: [{ name: 'slots', type: 'array' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'calendar:candidate_availability',
    category: 'CALENDAR',
    title: 'Find Candidate Availability',
    subtitle: 'Extracts preferred time windows stated by applicant',
    description: 'Parses candidate time preferences from chat or application questionnaire.',
    iconName: 'Clock',
    badge: 'Candidate Time',
    inputs: [{ name: 'candidateReply', type: 'string' }],
    outputs: [{ name: 'preferredWindows', type: 'array' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'calendar:common_availability',
    category: 'CALENDAR',
    title: 'Find Common Availability',
    subtitle: 'Calculates intersection of interviewer and candidate slots',
    description: 'Discovers mutual open slots between hiring panel and candidate.',
    iconName: 'CalendarRange',
    badge: 'Intersection',
    inputs: [{ name: 'interviewerSlots', type: 'array' }, { name: 'candidateSlots', type: 'array' }],
    outputs: [{ name: 'commonSlots', type: 'array' }, { name: 'bestSlot', type: 'object' }],
    defaultConfig: { minimumNoticeHours: 12 },
    riskLevel: 'LOW',
  },
  {
    type: 'calendar:create_interview',
    category: 'CALENDAR',
    title: 'Book Interview',
    subtitle: 'Reserves meeting room, creates calendar event, and generates link',
    description: 'Creates confirmed calendar appointment with Google Meet or Zoom link and syncs to CRM.',
    iconName: 'CalendarCheck',
    badge: 'Booker',
    inputs: [
      { name: 'candidateId', type: 'string', required: true },
      { name: 'slot', type: 'object', required: true },
      { name: 'interviewType', type: 'string' },
    ],
    outputs: [
      { name: 'interviewId', type: 'string' },
      { name: 'meetingUrl', type: 'string' },
      { name: 'scheduledTime', type: 'string' },
    ],
    defaultConfig: { meetingPlatform: 'GOOGLE_MEET', title: 'Technical Interview: {{candidate.name}}' },
    riskLevel: 'LOW',
  },
  {
    type: 'calendar:reschedule',
    category: 'CALENDAR',
    title: 'Reschedule Interview',
    subtitle: 'Moves appointment to newly selected slot',
    description: 'Updates calendar booking, dispatches updated calendar invites, and notifies participants.',
    iconName: 'CalendarSync',
    badge: 'Rescheduler',
    inputs: [{ name: 'interviewId', type: 'string', required: true }, { name: 'newSlot', type: 'object', required: true }],
    outputs: [{ name: 'rescheduled', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'calendar:cancel',
    category: 'CALENDAR',
    title: 'Cancel Interview',
    subtitle: 'Deletes event from calendar and frees up slot',
    description: 'Cancels meeting on calendar and alerts all parties.',
    iconName: 'CalendarX',
    badge: 'Cancellation',
    inputs: [{ name: 'interviewId', type: 'string', required: true }, { name: 'reason', type: 'string' }],
    outputs: [{ name: 'cancelled', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'calendar:send_invite',
    category: 'CALENDAR',
    title: 'Send Calendar Invite (.ics)',
    subtitle: 'Dispatches ICS calendar attachment and invites',
    description: 'Sends formal ICS calendar invitation file to interviewer and applicant.',
    iconName: 'CalendarPlus',
    badge: 'ICS Invite',
    inputs: [{ name: 'interviewId', type: 'string', required: true }],
    outputs: [{ name: 'inviteDelivered', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'calendar:send_reminder',
    category: 'CALENDAR',
    title: 'Send Calendar Reminder',
    subtitle: 'Dispatches reminder notification before interview',
    description: 'Sends push notification or SMS prior to scheduled meeting.',
    iconName: 'Bell',
    badge: 'Reminder',
    inputs: [{ name: 'interviewId', type: 'string', required: true }],
    outputs: [{ name: 'reminderSent', type: 'boolean' }],
    defaultConfig: { minutesBefore: 60 },
    riskLevel: 'LOW',
  },
  {
    type: 'calendar:detect_noshow',
    category: 'CALENDAR',
    title: 'Detect No-Show',
    subtitle: 'Detects if candidate failed to join scheduled meeting',
    description: 'Monitors video conference presence and marks no-show status if unattended.',
    iconName: 'UserX',
    badge: 'No-Show',
    inputs: [{ name: 'interviewId', type: 'string', required: true }],
    outputs: [{ name: 'isNoShow', type: 'boolean' }],
    defaultConfig: { gracePeriodMinutes: 10 },
    riskLevel: 'MEDIUM',
  },

  // ==========================================
  // 8. HUMAN-IN-THE-LOOP (HITL) NODES
  // ==========================================
  {
    type: 'human:review',
    category: 'HUMAN',
    title: 'Human Review Gate',
    subtitle: 'Pauses workflow until recruiter inspects and approves',
    description: 'Suspends workflow in WAITING_FOR_APPROVAL. Recruiter inspects candidate dossier in Approval Center.',
    iconName: 'ShieldAlert',
    badge: 'HITL Gate',
    inputs: [{ name: 'payload', type: 'object' }, { name: 'reason', type: 'string' }],
    outputs: [
      { name: 'approved', type: 'branch', description: 'Path taken if human approves' },
      { name: 'rejected', type: 'branch', description: 'Path taken if human rejects' },
    ],
    defaultConfig: {
      riskLevel: 'HIGH',
      reason: 'Borderline candidate score or executive role requires human sign-off.',
      timeoutHours: 72,
    },
    riskLevel: 'HIGH',
  },
  {
    type: 'human:request_approval',
    category: 'HUMAN',
    title: 'Request Approval',
    subtitle: 'Sends formal approval request to hiring manager',
    description: 'Creates approval ticket in Approval Center with side-by-side candidate comparison.',
    iconName: 'UserCheck',
    badge: 'Sign-Off',
    inputs: [{ name: 'approverRole', type: 'string' }, { name: 'candidateId', type: 'string' }],
    outputs: [{ name: 'decision', type: 'string' }],
    defaultConfig: { approverRole: 'HIRING_MANAGER' },
    riskLevel: 'HIGH',
  },
  {
    type: 'human:recruiter_decision',
    category: 'HUMAN',
    title: 'Recruiter Decision',
    subtitle: 'Captures recruiter verdict (Shortlist, Hold, or Reject)',
    description: 'Routes workflow based on recruiter manual scorecard input.',
    iconName: 'CheckCircle',
    badge: 'Verdict',
    inputs: [],
    outputs: [
      { name: 'shortlist', type: 'branch' },
      { name: 'hold', type: 'branch' },
      { name: 'reject', type: 'branch' },
    ],
    defaultConfig: {},
    riskLevel: 'MEDIUM',
  },
  {
    type: 'human:escalate',
    category: 'HUMAN',
    title: 'Escalate to VP / Head of Talent',
    subtitle: 'Escalates high-priority exception or compensation request',
    description: 'Flags unusual case to leadership for review.',
    iconName: 'AlertTriangle',
    badge: 'Escalation',
    inputs: [{ name: 'reason', type: 'string' }],
    outputs: [{ name: 'escalated', type: 'boolean' }],
    defaultConfig: { targetRole: 'VP_TALENT' },
    riskLevel: 'CRITICAL',
  },

  // ==========================================
  // 9. OUTPUT NODES (Destination Writers)
  // ==========================================
  {
    type: 'output:update_candidate',
    category: 'OUTPUT',
    title: 'Update Candidate Record',
    subtitle: 'Persists workflow results directly to candidate entity',
    description: 'Saves candidateScore, strengths, recommendation, and interview status to the database.',
    iconName: 'Database',
    badge: 'DB Output',
    inputs: [{ name: 'candidateId', type: 'string', required: true }, { name: 'data', type: 'object' }],
    outputs: [{ name: 'success', type: 'boolean' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'output:create_shortlist',
    category: 'OUTPUT',
    title: 'Create Shortlist',
    subtitle: 'Appends candidate to hiring manager batch shortlist',
    description: 'Compiles vetted applicants into a polished shortlist presentation.',
    iconName: 'ListOrdered',
    badge: 'Shortlist Batch',
    inputs: [{ name: 'jobId', type: 'string' }, { name: 'candidateIds', type: 'array' }],
    outputs: [{ name: 'shortlistId', type: 'string' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'output:create_recruiter_task',
    category: 'OUTPUT',
    title: 'Create Recruiter Task',
    subtitle: 'Injects prioritized task into recruiter workspace',
    description: 'Places actionable reminder on recruiter cockpit with link to candidate record.',
    iconName: 'CheckSquare',
    badge: 'Task Output',
    inputs: [{ name: 'title', type: 'string', required: true }],
    outputs: [{ name: 'taskId', type: 'string' }],
    defaultConfig: { title: 'Review Candidate Dossier', priority: 'HIGH' },
    riskLevel: 'LOW',
  },
  {
    type: 'output:send_notification',
    category: 'OUTPUT',
    title: 'Send Team Notification',
    subtitle: 'Alerts Slack or internal notification bell',
    description: 'Notifies team channel about newly shortlisted high-scoring applicant.',
    iconName: 'Bell',
    badge: 'Alert Output',
    inputs: [{ name: 'channel', type: 'string' }, { name: 'message', type: 'string' }],
    outputs: [{ name: 'notified', type: 'boolean' }],
    defaultConfig: { channel: '#recruiting-alerts', message: '🌟 Top candidate shortlisted: {{candidate.name}} (Score: {{candidateScore}})' },
    riskLevel: 'LOW',
  },
  {
    type: 'output:create_report',
    category: 'OUTPUT',
    title: 'Generate Hiring Report',
    subtitle: 'Compiles pipeline statistics and conversion analytics',
    description: 'Generates PDF or dashboard analytics report on campaign throughput and pass rates.',
    iconName: 'BarChart2',
    badge: 'Report Output',
    inputs: [{ name: 'jobId', type: 'string' }],
    outputs: [{ name: 'reportId', type: 'string' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'output:export_csv',
    category: 'OUTPUT',
    title: 'Export to CSV / Excel',
    subtitle: 'Exports candidate batch to downloadable spreadsheet',
    description: 'Generates CSV containing candidate names, contacts, scores, and status.',
    iconName: 'FileSpreadsheet',
    badge: 'Export',
    inputs: [{ name: 'candidates', type: 'array' }],
    outputs: [{ name: 'downloadUrl', type: 'string' }],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'output:store_document',
    category: 'OUTPUT',
    title: 'Store Generated Document',
    subtitle: 'Saves candidate scorecard or contract to vault',
    description: 'Archives generated evaluation scorecard into persistent Smart Vault.',
    iconName: 'HardDrive',
    badge: 'Vault Store',
    inputs: [{ name: 'content', type: 'any' }, { name: 'fileName', type: 'string' }],
    outputs: [{ name: 'documentId', type: 'string' }],
    defaultConfig: { folder: '/vault/evaluations/' },
    riskLevel: 'LOW',
  },
  {
    type: 'output:create_activity',
    category: 'OUTPUT',
    title: 'Create Timeline Activity',
    subtitle: 'Writes audit activity to company timeline',
    description: 'Records milestone in central Activity Feed for governance and audit transparency.',
    iconName: 'Activity',
    badge: 'Activity Log',
    inputs: [{ name: 'title', type: 'string' }, { name: 'content', type: 'string' }],
    outputs: [{ name: 'activityId', type: 'string' }],
    defaultConfig: { title: 'Workflow Executed', type: 'WORKFLOW' },
    riskLevel: 'LOW',
  },
  {
    type: 'output:webhook',
    category: 'OUTPUT',
    title: 'Trigger Outbound Webhook',
    subtitle: 'POSTs payload to external webhook URL',
    description: 'Dispatches candidate evaluation or interview payload to external ATS or HRIS.',
    iconName: 'Zap',
    badge: 'Outbound HTTP',
    inputs: [{ name: 'url', type: 'string', required: true }, { name: 'payload', type: 'object' }],
    outputs: [{ name: 'statusCode', type: 'number' }],
    defaultConfig: { url: 'https://api.external-ats.com/candidates' },
    riskLevel: 'MEDIUM',
  },
  {
    type: 'output:trigger_workflow',
    category: 'OUTPUT',
    title: 'Trigger Another Workflow',
    subtitle: 'Chains execution to secondary workflow',
    description: 'Launches onboarding workflow or background check pipeline when candidate is hired.',
    iconName: 'GitCommit',
    badge: 'Sub-Workflow',
    inputs: [{ name: 'workflowId', type: 'string', required: true }, { name: 'payload', type: 'object' }],
    outputs: [{ name: 'triggeredExecutionId', type: 'string' }],
    defaultConfig: { workflowId: 'wf_onboarding_pipeline' },
    riskLevel: 'LOW',
  },

  // ==========================================
  // 10. SYSTEM NODES (Audit, Logging, Errors, Retries)
  // ==========================================
  {
    type: 'system:log',
    category: 'SYSTEM',
    title: 'Execution Log',
    subtitle: 'Records step execution telemetry and metrics',
    description: 'Captures node input, output, duration, and token usage into workflow execution log.',
    iconName: 'Terminal',
    badge: 'Logger',
    inputs: [{ name: 'message', type: 'string' }],
    outputs: [{ name: 'logged', type: 'boolean' }],
    defaultConfig: { level: 'INFO' },
    riskLevel: 'LOW',
  },
  {
    type: 'system:audit',
    category: 'SYSTEM',
    title: 'Enterprise Audit Trail',
    subtitle: 'Writes immutable audit trail entry',
    description: 'Creates auditable governance record for compliance (EEOC, GDPR, hiring fairness).',
    iconName: 'ShieldCheck',
    badge: 'Audit Trail',
    inputs: [{ name: 'action', type: 'string', required: true }, { name: 'entityId', type: 'string' }],
    outputs: [{ name: 'auditId', type: 'string' }],
    defaultConfig: { action: 'CANDIDATE_EVALUATED' },
    riskLevel: 'LOW',
  },
  {
    type: 'system:retry',
    category: 'SYSTEM',
    title: 'Retry Guard',
    subtitle: 'Retries step on transient API failure with exponential backoff',
    description: 'Catches rate limits or network glitches and retries step automatically.',
    iconName: 'RefreshCw',
    badge: 'Resilience',
    inputs: [],
    outputs: [{ name: 'retryCount', type: 'number' }],
    defaultConfig: { maxRetries: 3, backoffFactorMs: 1000 },
    riskLevel: 'LOW',
  },
  {
    type: 'system:error_handler',
    category: 'SYSTEM',
    title: 'Error Handler Branch',
    subtitle: 'Catches upstream failures and routes to fallback',
    description: 'Prevents workflow crash by catching errors and routing to alert or manual queue.',
    iconName: 'AlertTriangle',
    badge: 'Error Trap',
    inputs: [],
    outputs: [
      { name: 'success', type: 'branch' },
      { name: 'error', type: 'branch' },
    ],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'system:timeout',
    category: 'SYSTEM',
    title: 'Execution Timeout Guard',
    subtitle: 'Enforces maximum execution deadline',
    description: 'Terminates hanging steps if external API exceeds configured duration.',
    iconName: 'Clock',
    badge: 'Watchdog',
    inputs: [],
    outputs: [{ name: 'timedOut', type: 'boolean' }],
    defaultConfig: { timeoutSeconds: 30 },
    riskLevel: 'LOW',
  },
  {
    type: 'system:success',
    category: 'SYSTEM',
    title: 'Mark Execution Success',
    subtitle: 'Explicitly completes workflow run successfully',
    description: 'Marks workflow run as SUCCESS and updates tenant execution metrics.',
    iconName: 'CheckCircle2',
    badge: 'Success',
    inputs: [],
    outputs: [],
    defaultConfig: {},
    riskLevel: 'LOW',
  },
  {
    type: 'system:failure',
    category: 'SYSTEM',
    title: 'Mark Execution Failed',
    subtitle: 'Explicitly terminates run with error status',
    description: 'Marks workflow run as FAILED and dispatches incident alert.',
    iconName: 'XOctagon',
    badge: 'Failure',
    inputs: [{ name: 'errorMessage', type: 'string' }],
    outputs: [],
    defaultConfig: { errorMessage: 'Workflow halted due to unresolved condition' },
    riskLevel: 'LOW',
  },

  // ==========================================
  // 11. AI AGENT NODE (Reusable Autonomous Agent)
  // ==========================================
  {
    type: 'ai:agent',
    category: 'AGENTS',
    title: 'Autonomous AI Agent',
    subtitle: 'Goal-driven agent with tool execution loop and memory',
    description: 'Executes reasoning loop: Evaluates input -> Gathers context -> Calls tools -> Synthesizes result.',
    iconName: 'Bot',
    badge: 'Agent Loop',
    inputs: [{ name: 'goal', type: 'string' }, { name: 'context', type: 'object' }],
    outputs: [
      { name: 'response', type: 'string' },
      { name: 'toolsExecuted', type: 'array' },
      { name: 'tokenCost', type: 'number' },
      { name: 'confidence', type: 'number' },
    ],
    defaultConfig: {
      agentName: 'Ares Recruitment Copilot',
      goal: 'Evaluate candidate qualifications, check hiring policy, and recommend next step.',
      instructions: 'You are an objective hiring copilot. Evaluate candidate solely based on skills and verified deliverables. Never use protected characteristics.',
      model: 'groq/llama-3.3-70b-versatile',
      temperature: 0.1,
      maxIterations: 5,
      tokenBudget: 1500,
      timeout: 60,
      tools: ['doc_ocr', 'skill_matching', 'calendar_check', 'add_crm_activity'],
      approvalPolicy: 'APPROVAL_FOR_DISQUALIFICATION',
    },
    riskLevel: 'HIGH',
    timeout: 60,
  },

  // ==========================================
  // 12. ADVANCED LOGIC: SUB-WORKFLOW & LOOPS
  // ==========================================
  {
    type: 'logic:call_workflow',
    category: 'LOGIC',
    title: 'Call Sub-Workflow',
    subtitle: 'Execute another workflow DAG as a modular step',
    description: 'Invokes an independent workflow, passes mapped inputs, and optionally waits for its completion result.',
    iconName: 'Workflow',
    badge: 'Modular Logic',
    inputs: [{ name: 'subWorkflowInput', type: 'object', required: false, description: 'Parameters passed to sub-workflow' }],
    outputs: [
      { name: 'subWorkflowResult', type: 'object', description: 'Execution result returned by the sub-workflow' },
      { name: 'subWorkflowExecutionId', type: 'string', description: 'ID of sub-workflow execution' },
    ],
    defaultConfig: { targetWorkflowId: '', waitForCompletion: true, timeoutSeconds: 120 },
    riskLevel: 'LOW',
    timeout: 120,
    supportsAsync: true,
  },
  {
    type: 'logic:for_each',
    category: 'LOGIC',
    title: 'For Each Loop',
    subtitle: 'Iterate over an array with concurrency guard',
    description: 'Iterates through an array of items, executing child branch for each item up to maxIterations limit.',
    iconName: 'Repeat',
    badge: 'Loop Control',
    inputs: [{ name: 'items', type: 'array', required: true, description: 'Array to iterate over' }],
    outputs: [
      { name: 'currentItem', type: 'any', description: 'Current item in iteration loop' },
      { name: 'loopIndex', type: 'number', description: 'Current zero-based index' },
      { name: 'totalProcessed', type: 'number', description: 'Total items successfully processed' },
    ],
    defaultConfig: { arrayField: 'items', maxIterations: 50, failurePolicy: 'CONTINUE_ON_ERROR' },
    riskLevel: 'LOW',
    timeout: 180,
    supportsLoop: true,
  },
  {
    type: 'logic:try_catch',
    category: 'LOGIC',
    title: 'Try / Catch Block',
    subtitle: 'Catch downstream errors gracefully',
    description: 'Routes to try branch; if any error occurs, catches the error and executes catch handle without failing workflow.',
    iconName: 'ShieldAlert',
    badge: 'Fault Tolerance',
    inputs: [],
    outputs: [
      { name: 'errorDetails', type: 'object', description: 'Captured exception message and stack trace' },
      { name: 'recovered', type: 'boolean', description: 'True when execution safely recovered via catch branch' },
    ],
    defaultConfig: { retryOnCatch: false },
    riskLevel: 'LOW',
    timeout: 30,
  },

  // ==========================================
  // 13. DATA & TRANSFORMATION
  // ==========================================
  {
    type: 'data:filter',
    category: 'DATA',
    title: 'Filter Array',
    subtitle: 'Filter elements by condition or threshold',
    description: 'Filters an array of objects based on a property comparison condition.',
    iconName: 'Filter',
    badge: 'Data Processing',
    inputs: [{ name: 'array', type: 'array', required: true }],
    outputs: [{ name: 'filtered', type: 'array', description: 'Items meeting criteria' }],
    defaultConfig: { targetField: 'score', operator: 'GREATER_THAN', threshold: 70 },
    riskLevel: 'LOW',
    timeout: 10,
  },
  {
    type: 'data:aggregate',
    category: 'DATA',
    title: 'Aggregate Data',
    subtitle: 'Sum, average, count, min, or max',
    description: 'Performs statistical or reduction operations over a dataset.',
    iconName: 'Calculator',
    badge: 'Data Processing',
    inputs: [{ name: 'records', type: 'array', required: true }],
    outputs: [{ name: 'aggregation', type: 'object', description: 'Summary statistics' }],
    defaultConfig: { operation: 'COUNT', property: 'id' },
    riskLevel: 'LOW',
    timeout: 10,
  },
  {
    type: 'transform:extract_field',
    category: 'TRANSFORM',
    title: 'Extract Field',
    subtitle: 'Pluck nested attribute via dot-notation',
    description: 'Extracts deep nested fields from JSON context to top-level variable.',
    iconName: 'ArrowRightLeft',
    badge: 'Data Transform',
    inputs: [{ name: 'source', type: 'object', required: true }],
    outputs: [{ name: 'extractedValue', type: 'any' }],
    defaultConfig: { path: 'candidate.customData.score', destinationVariable: 'candidateScore' },
    riskLevel: 'LOW',
    timeout: 5,
  },

  // ==========================================
  // 14. SALES NODE PACK
  // ==========================================
  {
    type: 'sales:lead_qualify',
    category: 'SALES',
    title: 'AI Lead Qualification',
    subtitle: 'Score leads against Ideal Customer Profile (ICP)',
    description: 'Evaluates inbound lead budget, authority, need, and timeline (BANT) against enterprise ICP criteria.',
    iconName: 'Target',
    badge: 'Sales AI',
    inputs: [{ name: 'lead', type: 'object', required: true }],
    outputs: [
      { name: 'qualificationScore', type: 'number', description: 'ICP fit score 0-100' },
      { name: 'icpTier', type: 'string', description: 'ENTERPRISE, MID_MARKET, or SMB' },
      { name: 'routingAction', type: 'string', description: 'FAST_TRACK, STANDARD, or NURTURE' },
    ],
    defaultConfig: { minEnterpriseScore: 80, fastTrackThreshold: 85 },
    riskLevel: 'LOW',
    timeout: 30,
  },
  {
    type: 'sales:enrich_lead',
    category: 'SALES',
    title: 'Enrich Lead Profile',
    subtitle: 'Lookup domain, revenue, employee size',
    description: 'Enriches raw email and company domain with Firmographics data.',
    iconName: 'Sparkles',
    badge: 'Sales Intelligence',
    inputs: [{ name: 'domain', type: 'string', required: true }],
    outputs: [
      { name: 'companyData', type: 'object', description: 'Enriched company profile' },
      { name: 'industry', type: 'string' },
      { name: 'employeeCount', type: 'number' },
    ],
    defaultConfig: { provider: 'CLEARBIT_OR_INTERNAL' },
    riskLevel: 'LOW',
    timeout: 20,
  },
  {
    type: 'sales:cadence_step',
    category: 'SALES',
    title: 'Sales Cadence Step',
    subtitle: 'Advance lead through multi-channel outreach cadence',
    description: 'Executes next step in sales sequence (email touch, LinkedIn view, or task for AE).',
    iconName: 'Send',
    badge: 'Sales Cadence',
    inputs: [{ name: 'leadId', type: 'string', required: true }],
    outputs: [{ name: 'cadenceStep', type: 'number' }, { name: 'dispatched', type: 'boolean' }],
    defaultConfig: { stepNumber: 1, channel: 'EMAIL' },
    riskLevel: 'LOW',
    timeout: 15,
  },

  // ==========================================
  // 15. SUPPORT NODE PACK
  // ==========================================
  {
    type: 'support:create_ticket',
    category: 'SUPPORT',
    title: 'Create Support Ticket',
    subtitle: 'Provision ticket in helpdesk queue',
    description: 'Generates new customer support ticket with priority and tags.',
    iconName: 'LifeBuoy',
    badge: 'Support Ops',
    inputs: [{ name: 'subject', type: 'string', required: true }, { name: 'message', type: 'string', required: true }],
    outputs: [{ name: 'ticketId', type: 'string' }, { name: 'priority', type: 'string' }],
    defaultConfig: { defaultPriority: 'HIGH', teamQueue: 'TIER_1' },
    riskLevel: 'LOW',
    timeout: 15,
  },
  {
    type: 'support:sla_check',
    category: 'SUPPORT',
    title: 'SLA Breach Check',
    subtitle: 'Verify ticket response time against SLA tier',
    description: 'Calculates elapsed time against contractual response/resolution SLA.',
    iconName: 'Clock',
    badge: 'Support Governance',
    inputs: [{ name: 'ticketId', type: 'string', required: true }],
    outputs: [{ name: 'slaStatus', type: 'string' }, { name: 'minutesRemaining', type: 'number' }, { name: 'breached', type: 'boolean' }],
    defaultConfig: { targetMinutes: 60 },
    riskLevel: 'LOW',
    timeout: 10,
  },
  {
    type: 'support:escalate',
    category: 'SUPPORT',
    title: 'Escalate to Tier 2 / On-Call',
    subtitle: 'Alert senior engineer or manager on duty',
    description: 'Escalates unhandled support incident with context and logs.',
    iconName: 'AlertOctagon',
    badge: 'Support Escalation',
    inputs: [{ name: 'ticketId', type: 'string', required: true }, { name: 'reason', type: 'string' }],
    outputs: [{ name: 'escalationId', type: 'string' }, { name: 'assignedTo', type: 'string' }],
    defaultConfig: { alertChannel: 'SLACK_AND_PAGER' },
    riskLevel: 'MEDIUM',
    timeout: 15,
  },

  // ==========================================
  // 16. FINANCE NODE PACK
  // ==========================================
  {
    type: 'finance:invoice_ocr',
    category: 'FINANCE',
    title: 'Invoice OCR & Extraction',
    subtitle: 'Extract vendor, line items, taxes, and total',
    description: 'Parses accounts payable invoices (PDF/TIFF) into structured ledger entries.',
    iconName: 'Receipt',
    badge: 'Finance Automation',
    inputs: [{ name: 'fileUrl', type: 'string', required: true }],
    outputs: [
      { name: 'invoiceNumber', type: 'string' },
      { name: 'vendorName', type: 'string' },
      { name: 'totalAmount', type: 'number' },
      { name: 'taxAmount', type: 'number' },
      { name: 'lineItems', type: 'array' },
    ],
    defaultConfig: { autoValidateTaxId: true },
    riskLevel: 'LOW',
    timeout: 45,
  },
  {
    type: 'finance:reconcile',
    category: 'FINANCE',
    title: 'Ledger Reconciliation',
    subtitle: 'Match bank payout with ledger accounts',
    description: 'Compares transaction amounts and dates to perform automated dual Khata reconciliation.',
    iconName: 'Scale',
    badge: 'Finance Reconciliation',
    inputs: [{ name: 'transactionId', type: 'string', required: true }],
    outputs: [{ name: 'reconciled', type: 'boolean' }, { name: 'differenceAmount', type: 'number' }],
    defaultConfig: { toleranceCents: 0 },
    riskLevel: 'MEDIUM',
    timeout: 30,
  },
  {
    type: 'finance:high_risk_approval',
    category: 'FINANCE',
    title: 'High-Value Spend Approval',
    subtitle: 'Mandatory CFO/Manager sign-off above threshold',
    description: 'Suspends workflow in WAITING_FOR_APPROVAL if transaction or refund exceeds policy limits.',
    iconName: 'ShieldAlert',
    badge: 'Finance HITL',
    inputs: [{ name: 'amount', type: 'number', required: true }],
    outputs: [{ name: 'approved', type: 'boolean' }, { name: 'approver', type: 'string' }],
    defaultConfig: { thresholdAmount: 5000, approverRole: 'CFO' },
    riskLevel: 'HIGH',
    timeout: 60,
    supportsApproval: true,
  },

  // ==========================================
  // 17. HR NODE PACK
  // ==========================================
  {
    type: 'hr:create_employee',
    category: 'HR',
    title: 'Provision Employee Record',
    subtitle: 'Initialize HR profile and payroll account',
    description: 'Creates employee record upon accepted offer letter.',
    iconName: 'UserPlus',
    badge: 'HR Ops',
    inputs: [{ name: 'candidateId', type: 'string', required: true }, { name: 'salary', type: 'number' }],
    outputs: [{ name: 'employeeId', type: 'string' }, { name: 'companyEmail', type: 'string' }],
    defaultConfig: { department: 'Engineering', employmentType: 'FULL_TIME' },
    riskLevel: 'MEDIUM',
    timeout: 20,
  },
  {
    type: 'hr:onboarding_workflow',
    category: 'HR',
    title: 'Trigger Onboarding Checklist',
    subtitle: 'Assign hardware, email, and compliance tasks',
    description: 'Dispatches automated 30-day onboarding checklist for new hires.',
    iconName: 'ClipboardCheck',
    badge: 'HR Onboarding',
    inputs: [{ name: 'employeeId', type: 'string', required: true }],
    outputs: [{ name: 'tasksCreated', type: 'number' }, { name: 'dueDate', type: 'string' }],
    defaultConfig: { template: 'SOFTWARE_ENGINEER_30_DAYS' },
    riskLevel: 'LOW',
    timeout: 15,
  },

  // ==========================================
  // 18. MARKETING & E-COMMERCE
  // ==========================================
  {
    type: 'marketing:content_repurpose',
    category: 'MARKETING',
    title: 'AI Content Repurposing',
    subtitle: 'Generate multi-channel social campaign from draft',
    description: 'Translates a long-form article or video transcript into LinkedIn thought leadership, X/Twitter threads, and email newsletters.',
    iconName: 'Megaphone',
    badge: 'Marketing AI',
    inputs: [{ name: 'sourceContent', type: 'string', required: true }],
    outputs: [
      { name: 'linkedinPost', type: 'string' },
      { name: 'twitterThread', type: 'array' },
      { name: 'emailSummary', type: 'string' },
    ],
    defaultConfig: { tone: 'AUTHORITATIVE_YET_ACCESSIBLE', includeHashtags: true },
    riskLevel: 'LOW',
    timeout: 45,
  },
  {
    type: 'ecom:order_created',
    category: 'E_COMMERCE',
    title: 'Order Created Trigger',
    subtitle: 'Fires on checkout completion in Shopify/Stripe',
    description: 'Triggers workflow immediately when new e-commerce customer order is placed.',
    iconName: 'ShoppingBag',
    badge: 'E-Commerce Trigger',
    inputs: [],
    outputs: [
      { name: 'order', type: 'object' },
      { name: 'customerEmail', type: 'string' },
      { name: 'totalPrice', type: 'number' },
      { name: 'items', type: 'array' },
    ],
    defaultConfig: { currency: 'USD' },
    riskLevel: 'LOW',
    timeout: 20,
  },
  {
    type: 'ecom:inventory_check',
    category: 'E_COMMERCE',
    title: 'Inventory Availability Check',
    subtitle: 'Verify real-time stock levels',
    description: 'Queries warehouse or ERP stock levels before fulfilling order.',
    iconName: 'Package',
    badge: 'E-Commerce Ops',
    inputs: [{ name: 'sku', type: 'string', required: true }, { name: 'quantity', type: 'number', required: true }],
    outputs: [{ name: 'inStock', type: 'boolean' }, { name: 'availableQuantity', type: 'number' }],
    defaultConfig: { safetyStockBuffer: 5 },
    riskLevel: 'LOW',
    timeout: 10,
  },

  // ==========================================
  // 19. VOICE & FRONT DESK NODE PACK
  // ==========================================
  {
    type: 'voice:call_received',
    category: 'VOICE',
    title: 'Inbound Call Received',
    subtitle: 'Fires when phone line rings via Twilio/Vapi',
    description: 'Triggers AI front desk agent immediately upon incoming phone call.',
    iconName: 'PhoneCall',
    badge: 'Voice Trigger',
    inputs: [],
    outputs: [
      { name: 'callerPhone', type: 'string' },
      { name: 'callSid', type: 'string' },
      { name: 'callerName', type: 'string' },
    ],
    defaultConfig: { phoneLine: 'MAIN_OFFICE' },
    riskLevel: 'LOW',
    timeout: 10,
  },
  {
    type: 'voice:ai_receptionist',
    category: 'VOICE',
    title: 'AI Voice Receptionist',
    subtitle: 'Conversational agent triaging & scheduling caller',
    description: 'Speaks with caller, queries knowledge base for answers, checks calendar availability, and books appointment live on phone.',
    iconName: 'Bot',
    badge: 'Voice Agent',
    inputs: [{ name: 'callerPhone', type: 'string', required: true }],
    outputs: [
      { name: 'callDisposition', type: 'string', description: 'BOOKED, ANSWERED, or ESCALATED' },
      { name: 'transcript', type: 'string' },
      { name: 'appointmentBooked', type: 'boolean' },
      { name: 'customerIntent', type: 'string' },
    ],
    defaultConfig: { voiceId: 'jennifer-professional', maxDurationMinutes: 10, allowBooking: true },
    riskLevel: 'LOW',
    timeout: 180,
  },

  // ==========================================
  // 20. BROWSER AUTOMATION NODE PACK
  // ==========================================
  {
    type: 'browser:sandboxed_task',
    category: 'BROWSER',
    title: 'Sandboxed Browser Task',
    subtitle: 'Execute web actions, screenshots, or scrapers',
    description: 'Runs headless Chromium browser session to extract live pricing or verify web portals.',
    iconName: 'Globe',
    badge: 'Browser Ops',
    inputs: [{ name: 'url', type: 'string', required: true }, { name: 'action', type: 'string' }],
    outputs: [{ name: 'screenshotUrl', type: 'string' }, { name: 'extractedData', type: 'object' }],
    defaultConfig: { headless: true, timeoutSeconds: 60, screenshotOnFinish: true },
    riskLevel: 'HIGH',
    timeout: 60,
  },

  // ==========================================
  // 21. ARTIFACT & REPORT OUTPUT
  // ==========================================
  {
    type: 'output:create_artifact',
    category: 'OUTPUT',
    title: 'Generate Workflow Artifact',
    subtitle: 'Save structured report, PDF, or CSV to vault',
    description: 'Persists workflow execution output as an immutable business artifact in database and vault.',
    iconName: 'FileText',
    badge: 'Artifact Sink',
    inputs: [
      { name: 'name', type: 'string', required: true },
      { name: 'type', type: 'string', required: true },
      { name: 'data', type: 'any', required: true },
    ],
    outputs: [{ name: 'artifactId', type: 'string' }, { name: 'artifactUrl', type: 'string' }],
    defaultConfig: { artifactType: 'REPORT' },
    riskLevel: 'LOW',
    timeout: 15,
  },
  // ==========================================
  // 22. DATABASE & STORAGE NODE PACK
  // ==========================================
  {
    type: 'database:query',
    category: 'DATABASE',
    title: 'Database Query / Lookup',
    subtitle: 'Execute secure parameterized database query',
    description: 'Queries internal tenant database tables or external relational stores safely without raw SQL injection.',
    iconName: 'Database',
    badge: 'Database',
    inputs: [{ name: 'table', type: 'string', required: true }, { name: 'where', type: 'object' }],
    outputs: [{ name: 'records', type: 'array' }, { name: 'count', type: 'number' }],
    defaultConfig: { table: 'Contact', limit: 50 },
    riskLevel: 'MEDIUM',
    timeout: 30,
  },
  {
    type: 'database:insert',
    category: 'DATABASE',
    title: 'Database Insert Record',
    subtitle: 'Persist record into relational database',
    description: 'Inserts validated entity into database with tenant isolation and schema compliance.',
    iconName: 'Database',
    badge: 'Database Insert',
    inputs: [{ name: 'table', type: 'string', required: true }, { name: 'data', type: 'object', required: true }],
    outputs: [{ name: 'recordId', type: 'string' }, { name: 'created', type: 'boolean' }],
    defaultConfig: { table: 'Activity' },
    riskLevel: 'MEDIUM',
    timeout: 30,
  },

  // ==========================================
  // 23. INTEGRATIONS & CONNECTORS PACK
  // ==========================================
  {
    type: 'integration:http_request',
    category: 'INTEGRATIONS',
    title: 'HTTP REST / GraphQL Request',
    subtitle: 'Execute authenticated API request to external service',
    description: 'Communicates with third-party SaaS systems (Stripe, HubSpot, Twilio, Slack) with automatic header authentication and retry policy.',
    iconName: 'Link',
    badge: 'Connector',
    inputs: [
      { name: 'url', type: 'string', required: true },
      { name: 'method', type: 'string', required: true },
      { name: 'headers', type: 'object' },
      { name: 'body', type: 'object' },
    ],
    outputs: [{ name: 'status', type: 'number' }, { name: 'data', type: 'any' }],
    defaultConfig: { method: 'POST' },
    riskLevel: 'MEDIUM',
    timeout: 30,
  },
  {
    type: 'integration:webhook_dispatch',
    category: 'INTEGRATIONS',
    title: 'Outbound Webhook Dispatch',
    subtitle: 'POST signed HMAC payload to customer webhook endpoint',
    description: 'Dispatches real-time events to partner webhooks with signature verification and replay prevention.',
    iconName: 'Zap',
    badge: 'Webhook',
    inputs: [{ name: 'endpointUrl', type: 'string', required: true }, { name: 'payload', type: 'object', required: true }],
    outputs: [{ name: 'delivered', type: 'boolean' }, { name: 'responseCode', type: 'number' }],
    defaultConfig: { signPayload: true },
    riskLevel: 'LOW',
    timeout: 20,
  },
];

export const UNIVERSAL_NODE_CATALOG = NODE_CATALOG;
