export type NodeCategory = 'TRIGGER' | 'LOGIC' | 'AI' | 'COMMUNICATION' | 'CRM' | 'DOCUMENTS' | 'EXTERNAL';

export interface WorkflowNodeDefinition {
  type: string;
  category: NodeCategory;
  title: string;
  subtitle: string;
  description: string;
  iconName: string;
  badge: string;
  inputs: Array<{ name: string; type: string; required?: boolean; description?: string }>;
  outputs: Array<{ name: string; type: string; description?: string }>;
  defaultConfig: Record<string, any>;
  riskLevel?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

export const NODE_CATALOG: WorkflowNodeDefinition[] = [
  // ==========================================
  // TRIGGERS (19 nodes)
  // ==========================================
  {
    type: 'trigger:new_lead',
    category: 'TRIGGER',
    title: 'New Lead',
    subtitle: 'Fires when a new prospect or lead is ingested',
    description: 'Triggers workflow execution immediately after a new lead is detected in CRM, CSV upload, or external prospecting.',
    iconName: 'UserPlus',
    badge: 'CRM Event',
    inputs: [],
    outputs: [{ name: 'lead', type: 'object', description: 'Lead contact payload with email, name, company' }],
    defaultConfig: { sourceFilter: 'ALL' },
  },
  {
    type: 'trigger:new_contact',
    category: 'TRIGGER',
    title: 'New Contact Created',
    subtitle: 'Fires on Contact entity creation',
    description: 'Triggers when a Contact record is created in the database.',
    iconName: 'Contact',
    badge: 'CRM Event',
    inputs: [],
    outputs: [{ name: 'contact', type: 'object', description: 'Complete Contact record' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:new_company',
    category: 'TRIGGER',
    title: 'New Company Created',
    subtitle: 'Fires when an organization is added',
    description: 'Triggers when an enterprise Account or Company is registered.',
    iconName: 'Building',
    badge: 'CRM Event',
    inputs: [],
    outputs: [{ name: 'company', type: 'object', description: 'Company entity' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:new_deal',
    category: 'TRIGGER',
    title: 'New Deal Created',
    subtitle: 'Fires when a pipeline deal is opened',
    description: 'Triggers when a sales opportunity is logged.',
    iconName: 'Briefcase',
    badge: 'Sales Event',
    inputs: [],
    outputs: [{ name: 'deal', type: 'object', description: 'Deal record' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:deal_stage_changed',
    category: 'TRIGGER',
    title: 'Deal Stage Changed',
    subtitle: 'Fires on pipeline advancement',
    description: 'Triggers when a deal moves from one stage to another (e.g., Lead -> Proposal -> Won).',
    iconName: 'GitCommit',
    badge: 'Sales Event',
    inputs: [],
    outputs: [{ name: 'deal', type: 'object' }, { name: 'previousStage', type: 'string' }, { name: 'newStage', type: 'string' }],
    defaultConfig: { targetStage: 'ALL' },
  },
  {
    type: 'trigger:form_submitted',
    category: 'TRIGGER',
    title: 'Form Submitted',
    subtitle: 'Inbound web form or landing page lead',
    description: 'Captures submissions from embedded forms and landing pages.',
    iconName: 'FileText',
    badge: 'Inbound',
    inputs: [],
    outputs: [{ name: 'formData', type: 'object' }],
    defaultConfig: { formId: 'default' },
  },
  {
    type: 'trigger:website_event',
    category: 'TRIGGER',
    title: 'Website Behavioral Event',
    subtitle: 'Page view, pricing visited, cart intent',
    description: 'Fires on telemetry signals received from client analytics SDKs.',
    iconName: 'Globe',
    badge: 'Telemetry',
    inputs: [],
    outputs: [{ name: 'event', type: 'string' }, { name: 'sessionId', type: 'string' }],
    defaultConfig: { eventName: 'PAGE_VIEW' },
  },
  {
    type: 'trigger:email_received',
    category: 'TRIGGER',
    title: 'Email Received',
    subtitle: 'Inbound message on corporate inbox',
    description: 'Triggers on incoming customer emails via IMAP/Gmail/Outlook webhook.',
    iconName: 'Mail',
    badge: 'Communication',
    inputs: [],
    outputs: [{ name: 'sender', type: 'string' }, { name: 'subject', type: 'string' }, { name: 'body', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:whatsapp_received',
    category: 'TRIGGER',
    title: 'WhatsApp Received',
    subtitle: 'Incoming chat on WhatsApp Business API',
    description: 'Fires when an inbound WhatsApp message, button reply, or location is received.',
    iconName: 'MessageSquare',
    badge: 'WhatsApp',
    inputs: [],
    outputs: [{ name: 'from', type: 'string' }, { name: 'message', type: 'string' }, { name: 'messageId', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:sms_received',
    category: 'TRIGGER',
    title: 'SMS Received',
    subtitle: 'Inbound SMS message',
    description: 'Triggers on incoming SMS via Twilio or cellular gateway.',
    iconName: 'Smartphone',
    badge: 'SMS',
    inputs: [],
    outputs: [{ name: 'from', type: 'string' }, { name: 'body', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:call_received',
    category: 'TRIGGER',
    title: 'Call Received',
    subtitle: 'Inbound voice call event',
    description: 'Fires when telephony detects an inbound phone call or SIP connection.',
    iconName: 'PhoneIncoming',
    badge: 'Voice',
    inputs: [],
    outputs: [{ name: 'callerNumber', type: 'string' }, { name: 'callSid', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:ticket_created',
    category: 'TRIGGER',
    title: 'Ticket Created',
    subtitle: 'Customer support inquiry opened',
    description: 'Triggers when a customer logs an issue in Helpdesk.',
    iconName: 'Ticket',
    badge: 'Support',
    inputs: [],
    outputs: [{ name: 'ticket', type: 'object' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:document_uploaded',
    category: 'TRIGGER',
    title: 'Document Uploaded',
    subtitle: 'File deposited to documents vault',
    description: 'Fires when a PDF, invoice, contract, or scan is saved.',
    iconName: 'FolderPlus',
    badge: 'Documents',
    inputs: [],
    outputs: [{ name: 'document', type: 'object' }, { name: 'url', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:invoice_created',
    category: 'TRIGGER',
    title: 'Invoice Created',
    subtitle: 'Accounts receivable bill generated',
    description: 'Fires when a draft or finalized invoice is created in Finance.',
    iconName: 'Receipt',
    badge: 'Finance',
    inputs: [],
    outputs: [{ name: 'invoice', type: 'object' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:payment_received',
    category: 'TRIGGER',
    title: 'Payment Received',
    subtitle: 'Stripe, bank, or POS payment settled',
    description: 'Triggers upon verified transaction settlement.',
    iconName: 'CreditCard',
    badge: 'Payments',
    inputs: [],
    outputs: [{ name: 'amount', type: 'number' }, { name: 'currency', type: 'string' }, { name: 'customerEmail', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:schedule',
    category: 'TRIGGER',
    title: 'Schedule / CRON',
    subtitle: 'Recurring interval or cron expression',
    description: 'Fires on scheduled cadence (e.g., every morning at 9am, hourly sweep).',
    iconName: 'Clock',
    badge: 'Schedule',
    inputs: [],
    outputs: [{ name: 'timestamp', type: 'string' }],
    defaultConfig: { cron: '0 9 * * *', timezone: 'UTC' },
  },
  {
    type: 'trigger:webhook',
    category: 'TRIGGER',
    title: 'Webhook Received',
    subtitle: 'Custom HTTP POST endpoint',
    description: 'Provides a secure dedicated URL to receive external payloads.',
    iconName: 'Zap',
    badge: 'Webhook',
    inputs: [],
    outputs: [{ name: 'payload', type: 'object' }, { name: 'headers', type: 'object' }],
    defaultConfig: { authRequired: true },
  },
  {
    type: 'trigger:api_request',
    category: 'TRIGGER',
    title: 'API Request',
    subtitle: 'Direct REST API trigger',
    description: 'Fires via platform API key execution.',
    iconName: 'Code',
    badge: 'API',
    inputs: [],
    outputs: [{ name: 'data', type: 'object' }],
    defaultConfig: {},
  },
  {
    type: 'trigger:manual',
    category: 'TRIGGER',
    title: 'Manual Trigger',
    subtitle: 'User one-click dispatch',
    description: 'Allows human operators to initiate execution from CRM record page.',
    iconName: 'Play',
    badge: 'Manual',
    inputs: [],
    outputs: [{ name: 'triggeredBy', type: 'string' }],
    defaultConfig: {},
  },

  // ==========================================
  // LOGIC & FLOW CONTROL (13 nodes)
  // ==========================================
  {
    type: 'logic:if_else',
    category: 'LOGIC',
    title: 'If / Else Condition',
    subtitle: 'Branch workflow based on evaluation',
    description: 'Evaluates dynamic expressions (e.g., leadScore > 50, country == US).',
    iconName: 'GitFork',
    badge: 'Branching',
    inputs: [{ name: 'input', type: 'any' }],
    outputs: [{ name: 'true', type: 'flow' }, { name: 'false', type: 'flow' }],
    defaultConfig: { field: 'leadScore', operator: 'GREATER_THAN', value: 50 },
  },
  {
    type: 'logic:switch',
    category: 'LOGIC',
    title: 'Switch / Case',
    subtitle: 'Multi-way branching',
    description: 'Routes execution through multiple paths based on matching cases.',
    iconName: 'GitBranch',
    badge: 'Branching',
    inputs: [{ name: 'key', type: 'string' }],
    outputs: [{ name: 'caseA', type: 'flow' }, { name: 'caseB', type: 'flow' }, { name: 'default', type: 'flow' }],
    defaultConfig: { variable: 'industry' },
  },
  {
    type: 'logic:filter',
    category: 'LOGIC',
    title: 'Filter',
    subtitle: 'Halt execution if condition unmet',
    description: 'Stops workflow quietly if incoming item does not match requirements.',
    iconName: 'Filter',
    badge: 'Gate',
    inputs: [{ name: 'item', type: 'any' }],
    outputs: [{ name: 'passed', type: 'flow' }],
    defaultConfig: { condition: 'item.isActive == true' },
  },
  {
    type: 'logic:delay',
    category: 'LOGIC',
    title: 'Delay / Wait',
    subtitle: 'Pause execution for duration',
    description: 'Suspends workflow in BullMQ for minutes, hours, or days.',
    iconName: 'Hourglass',
    badge: 'Timing',
    inputs: [],
    outputs: [{ name: 'resumed', type: 'flow' }],
    defaultConfig: { duration: 1, unit: 'HOURS' },
  },
  {
    type: 'logic:loop',
    category: 'LOGIC',
    title: 'For Each Loop',
    subtitle: 'Iterate over array of items',
    description: 'Runs child steps for every element in an array or collection.',
    iconName: 'RotateCw',
    badge: 'Loop',
    inputs: [{ name: 'items', type: 'array' }],
    outputs: [{ name: 'item', type: 'any' }, { name: 'completed', type: 'flow' }],
    defaultConfig: { batchSize: 1 },
  },
  {
    type: 'logic:merge',
    category: 'LOGIC',
    title: 'Merge Branches',
    subtitle: 'Re-unite parallel paths',
    description: 'Waits for one or all upstream branches before continuing.',
    iconName: 'GitMerge',
    badge: 'Sync',
    inputs: [{ name: 'branchA', type: 'flow' }, { name: 'branchB', type: 'flow' }],
    outputs: [{ name: 'out', type: 'flow' }],
    defaultConfig: { mode: 'WAIT_ANY' },
  },
  {
    type: 'logic:rate_limit',
    category: 'LOGIC',
    title: 'Rate Limit',
    subtitle: 'Throttle execution volume',
    description: 'Ensures operations do not exceed tenant quotas or API limits.',
    iconName: 'Gauge',
    badge: 'Safety',
    inputs: [],
    outputs: [{ name: 'out', type: 'flow' }],
    defaultConfig: { maxPerMinute: 60 },
  },
  {
    type: 'logic:deduplicate',
    category: 'LOGIC',
    title: 'Deduplicate',
    subtitle: 'Prevent duplicate executions',
    description: 'Suppresses duplicate runs based on a composite idempotency hash.',
    iconName: 'Shield',
    badge: 'Guard',
    inputs: [{ name: 'uniqueKey', type: 'string' }],
    outputs: [{ name: 'unique', type: 'flow' }],
    defaultConfig: { ttlMinutes: 1440 },
  },
  {
    type: 'logic:human_approval',
    category: 'LOGIC',
    title: 'Human-in-the-Loop Approval',
    subtitle: 'Pause until reviewed by human',
    description: 'Suspends execution and posts an approval card to /automation/approvals.',
    iconName: 'ShieldAlert',
    badge: 'HITL',
    riskLevel: 'HIGH',
    inputs: [{ name: 'proposedAction', type: 'object' }],
    outputs: [{ name: 'approved', type: 'flow' }, { name: 'rejected', type: 'flow' }],
    defaultConfig: { riskLevel: 'HIGH', timeoutHours: 48 },
  },

  // ==========================================
  // AI & INTELLIGENCE (11 nodes)
  // ==========================================
  {
    type: 'ai:classify',
    category: 'AI',
    title: 'AI Classify',
    subtitle: 'Sort input into labeled categories',
    description: 'Categorizes emails, tickets, or intent using Groq high-speed LLM.',
    iconName: 'Sparkles',
    badge: 'Fast LLM',
    inputs: [{ name: 'text', type: 'string' }],
    outputs: [{ name: 'category', type: 'string' }, { name: 'confidence', type: 'number' }],
    defaultConfig: { categories: ['Sales Inquiry', 'Support Issue', 'Billing', 'Spam'] },
  },
  {
    type: 'ai:extract',
    category: 'AI',
    title: 'AI Entity Extraction',
    subtitle: 'Extract JSON entities from unstructured text',
    description: 'Extracts names, dates, amounts, phone numbers, and addresses.',
    iconName: 'Cpu',
    badge: 'Extraction',
    inputs: [{ name: 'text', type: 'string' }],
    outputs: [{ name: 'entities', type: 'object' }],
    defaultConfig: { schema: { name: 'string', email: 'string', budget: 'number' } },
  },
  {
    type: 'ai:summarize',
    category: 'AI',
    title: 'AI Summarize',
    subtitle: 'Condense long conversations or documents',
    description: 'Generates concise executive bullets from transcripts and threads.',
    iconName: 'FileText',
    badge: 'Summarizer',
    inputs: [{ name: 'content', type: 'string' }],
    outputs: [{ name: 'summary', type: 'string' }],
    defaultConfig: { maxWords: 100 },
  },
  {
    type: 'ai:score',
    category: 'AI',
    title: 'AI Lead & Risk Scoring',
    subtitle: 'Compute predictive engagement score',
    description: 'Scores leads 0-100 based on firmographics and activity velocity.',
    iconName: 'TrendingUp',
    badge: 'Predictive',
    inputs: [{ name: 'record', type: 'object' }],
    outputs: [{ name: 'score', type: 'number' }, { name: 'rationale', type: 'string' }],
    defaultConfig: { targetMetric: 'ICP_FIT' },
  },
  {
    type: 'ai:generate',
    category: 'AI',
    title: 'AI Content Generator',
    subtitle: 'Generate hyper-personalized copy',
    description: 'Drafts emails, proposals, responses, or social copy with context interpolation.',
    iconName: 'Bot',
    badge: 'Generative',
    inputs: [{ name: 'prompt', type: 'string' }, { name: 'context', type: 'object' }],
    outputs: [{ name: 'text', type: 'string' }],
    defaultConfig: { model: 'groq/compound', temperature: 0.7 },
  },
  {
    type: 'ai:agent',
    category: 'AI',
    title: 'Autonomous AI Agent',
    subtitle: 'Invoke reasoning agent with tools',
    description: 'Runs a multi-step ReAct agent runtime capable of calling CRM and external tools.',
    iconName: 'Bot',
    badge: 'ReAct Agent',
    riskLevel: 'MEDIUM',
    inputs: [{ name: 'task', type: 'string' }],
    outputs: [{ name: 'result', type: 'string' }, { name: 'toolExecutions', type: 'array' }],
    defaultConfig: { agentId: 'sales_outbound_sentinel', maxIterations: 8 },
  },
  {
    type: 'ai:rag_search',
    category: 'AI',
    title: 'RAG Knowledge Search',
    subtitle: 'Query vector knowledge base',
    description: 'Retrieves relevant documentation, FAQs, and product manuals.',
    iconName: 'Database',
    badge: 'Vector RAG',
    inputs: [{ name: 'query', type: 'string' }],
    outputs: [{ name: 'docs', type: 'array' }, { name: 'answer', type: 'string' }],
    defaultConfig: { topK: 3 },
  },
  {
    type: 'ai:sentiment',
    category: 'AI',
    title: 'Sentiment & Frustration Detector',
    subtitle: 'Analyze emotional tone',
    description: 'Detects angry, dissatisfied, or churn-risk customers for immediate human escalation.',
    iconName: 'Smile',
    badge: 'Sentiment',
    inputs: [{ name: 'message', type: 'string' }],
    outputs: [{ name: 'sentiment', type: 'string' }, { name: 'urgency', type: 'string' }],
    defaultConfig: { alertOnNegative: true },
  },

  // ==========================================
  // COMMUNICATION (7 nodes)
  // ==========================================
  {
    type: 'comm:email',
    category: 'COMMUNICATION',
    title: 'Send Email',
    subtitle: 'Dispatch email via Resend / SMTP',
    description: 'Sends rich HTML or plain text emails with tracking.',
    iconName: 'Mail',
    badge: 'Resend',
    riskLevel: 'MEDIUM',
    inputs: [{ name: 'to', type: 'string' }, { name: 'subject', type: 'string' }, { name: 'body', type: 'string' }],
    outputs: [{ name: 'messageId', type: 'string' }, { name: 'status', type: 'string' }],
    defaultConfig: { subject: 'Update from {{company}}' },
  },
  {
    type: 'comm:whatsapp',
    category: 'COMMUNICATION',
    title: 'Send WhatsApp Message',
    subtitle: 'Dispatch via WhatsApp Business API',
    description: 'Sends WhatsApp messages, interactive buttons, or payment links.',
    iconName: 'MessageSquare',
    badge: 'WhatsApp',
    riskLevel: 'MEDIUM',
    inputs: [{ name: 'to', type: 'string' }, { name: 'message', type: 'string' }],
    outputs: [{ name: 'whatsappMessageId', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'comm:sms',
    category: 'COMMUNICATION',
    title: 'Send SMS',
    subtitle: 'Dispatch cellular text via Twilio',
    description: 'Sends instant SMS confirmation or notification.',
    iconName: 'Smartphone',
    badge: 'Twilio',
    riskLevel: 'MEDIUM',
    inputs: [{ name: 'to', type: 'string' }, { name: 'text', type: 'string' }],
    outputs: [{ name: 'smsId', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'comm:slack',
    category: 'COMMUNICATION',
    title: 'Send Slack Alert',
    subtitle: 'Post notification to team channel',
    description: 'Dispatches hot deal alerts, churn warnings, or approval pings to Slack.',
    iconName: 'Hash',
    badge: 'Slack',
    inputs: [{ name: 'channel', type: 'string' }, { name: 'message', type: 'string' }],
    outputs: [{ name: 'sent', type: 'boolean' }],
    defaultConfig: { channel: '#sales-announcements' },
  },
  {
    type: 'comm:voice_call',
    category: 'COMMUNICATION',
    title: 'Place AI Voice Call',
    subtitle: 'Dial phone number with AI Agent',
    description: 'Initiates outbound call with conversational voice agent.',
    iconName: 'PhoneCall',
    badge: 'Voice Bot',
    riskLevel: 'HIGH',
    inputs: [{ name: 'to', type: 'string' }, { name: 'scriptContext', type: 'object' }],
    outputs: [{ name: 'callId', type: 'string' }, { name: 'disposition', type: 'string' }],
    defaultConfig: { agentPersona: 'Receptionist' },
  },
  {
    type: 'comm:calendar',
    category: 'COMMUNICATION',
    title: 'Book Calendar Appointment',
    subtitle: 'Schedule meeting with sales rep',
    description: 'Reserves slot on Google Calendar or Calendly.',
    iconName: 'Calendar',
    badge: 'Calendar',
    inputs: [{ name: 'attendeeEmail', type: 'string' }, { name: 'slotTime', type: 'string' }],
    outputs: [{ name: 'bookingId', type: 'string' }, { name: 'meetingLink', type: 'string' }],
    defaultConfig: {},
  },

  // ==========================================
  // CRM OPERATIONS (10 nodes)
  // ==========================================
  {
    type: 'crm:create_contact',
    category: 'CRM',
    title: 'Create Contact',
    subtitle: 'Insert new person into CRM',
    description: 'Saves a new Contact record in the tenant workspace.',
    iconName: 'UserPlus',
    badge: 'CRM Write',
    riskLevel: 'LOW',
    inputs: [{ name: 'firstName', type: 'string' }, { name: 'email', type: 'string' }],
    outputs: [{ name: 'contactId', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'crm:update_contact',
    category: 'CRM',
    title: 'Update Contact',
    subtitle: 'Modify contact properties or tags',
    description: 'Updates fields, customData, and tags for a contact.',
    iconName: 'UserCheck',
    badge: 'CRM Write',
    riskLevel: 'LOW',
    inputs: [{ name: 'contactId', type: 'string' }, { name: 'fields', type: 'object' }],
    outputs: [{ name: 'updated', type: 'boolean' }],
    defaultConfig: {},
  },
  {
    type: 'crm:create_deal',
    category: 'CRM',
    title: 'Create Deal',
    subtitle: 'Open sales deal in pipeline',
    description: 'Creates a deal associated with contact and company.',
    iconName: 'DollarSign',
    badge: 'CRM Write',
    riskLevel: 'MEDIUM',
    inputs: [{ name: 'title', type: 'string' }, { name: 'amount', type: 'number' }, { name: 'stage', type: 'string' }],
    outputs: [{ name: 'dealId', type: 'string' }],
    defaultConfig: { stage: 'Lead', amount: 5000 },
  },
  {
    type: 'crm:move_deal',
    category: 'CRM',
    title: 'Move Deal Stage',
    subtitle: 'Advance deal in Kanban',
    description: 'Changes deal stage to Proposal, Won, Lost, etc.',
    iconName: 'ArrowRight',
    badge: 'CRM Write',
    riskLevel: 'MEDIUM',
    inputs: [{ name: 'dealId', type: 'string' }, { name: 'newStage', type: 'string' }],
    outputs: [{ name: 'updated', type: 'boolean' }],
    defaultConfig: { newStage: 'Won' },
  },
  {
    type: 'crm:create_task',
    category: 'CRM',
    title: 'Create CRM Task',
    subtitle: 'Assign action item to rep',
    description: 'Adds follow-up task with due date to user queue.',
    iconName: 'CheckSquare',
    badge: 'CRM Task',
    riskLevel: 'LOW',
    inputs: [{ name: 'title', type: 'string' }, { name: 'assignedTo', type: 'string' }],
    outputs: [{ name: 'taskId', type: 'string' }],
    defaultConfig: { priority: 'HIGH' },
  },
  {
    type: 'crm:add_activity',
    category: 'CRM',
    title: 'Log Timeline Activity',
    subtitle: 'Record note, call, or interaction',
    description: 'Appends activity log to contact or deal timeline.',
    iconName: 'Clock',
    badge: 'Activity',
    riskLevel: 'LOW',
    inputs: [{ name: 'type', type: 'string' }, { name: 'content', type: 'string' }],
    outputs: [{ name: 'activityId', type: 'string' }],
    defaultConfig: { type: 'NOTE' },
  },
  {
    type: 'crm:update_lead_score',
    category: 'CRM',
    title: 'Update Lead Score',
    subtitle: 'Increment or decrement score',
    description: 'Adjusts lead engagement points.',
    iconName: 'Star',
    badge: 'Scoring',
    riskLevel: 'LOW',
    inputs: [{ name: 'contactId', type: 'string' }, { name: 'scoreDelta', type: 'number' }],
    outputs: [{ name: 'newScore', type: 'number' }],
    defaultConfig: { scoreDelta: 10 },
  },

  // ==========================================
  // DOCUMENTS & OCR (5 nodes)
  // ==========================================
  {
    type: 'doc:ocr',
    category: 'DOCUMENTS',
    title: 'OCR & Vision Parse',
    subtitle: 'Extract data from invoice / ID / PDF',
    description: 'Performs optical character recognition and field parsing.',
    iconName: 'Scan',
    badge: 'OCR',
    inputs: [{ name: 'documentUrl', type: 'string' }],
    outputs: [{ name: 'extractedFields', type: 'object' }, { name: 'rawText', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'doc:generate_pdf',
    category: 'DOCUMENTS',
    title: 'Generate PDF Document',
    subtitle: 'Render contract, invoice, or quote',
    description: 'Produces professional PDF from template and context data.',
    iconName: 'File',
    badge: 'PDF Maker',
    inputs: [{ name: 'templateId', type: 'string' }, { name: 'data', type: 'object' }],
    outputs: [{ name: 'pdfUrl', type: 'string' }],
    defaultConfig: {},
  },
  {
    type: 'doc:send_signature',
    category: 'DOCUMENTS',
    title: 'Send for E-Signature',
    subtitle: 'Dispatch contract for digital signing',
    description: 'Initiates legally compliant e-sign workflow.',
    iconName: 'FileSignature',
    badge: 'E-Sign',
    riskLevel: 'HIGH',
    inputs: [{ name: 'signerEmail', type: 'string' }, { name: 'documentUrl', type: 'string' }],
    outputs: [{ name: 'signatureRequestId', type: 'string' }],
    defaultConfig: {},
  },

  // ==========================================
  // EXTERNAL & BROWSER (4 nodes)
  // ==========================================
  {
    type: 'ext:http_request',
    category: 'EXTERNAL',
    title: 'HTTP Request / REST API',
    subtitle: 'Call external endpoint',
    description: 'Executes GET, POST, PUT, DELETE request with custom headers and body.',
    iconName: 'Globe',
    badge: 'HTTP',
    inputs: [{ name: 'url', type: 'string' }, { name: 'method', type: 'string' }, { name: 'body', type: 'any' }],
    outputs: [{ name: 'statusCode', type: 'number' }, { name: 'data', type: 'any' }],
    defaultConfig: { method: 'POST', url: 'https://api.external.com' },
  },
  {
    type: 'ext:browser_agent',
    category: 'EXTERNAL',
    title: 'Browser Automation Agent',
    subtitle: 'Execute web actions without API',
    description: 'Sandboxed browser agent opens pages, clicks, fills forms, and scrapes data.',
    iconName: 'Compass',
    badge: 'Browser Agent',
    riskLevel: 'HIGH',
    inputs: [{ name: 'url', type: 'string' }, { name: 'instruction', type: 'string' }],
    outputs: [{ name: 'extractedJson', type: 'object' }, { name: 'screenshotUrl', type: 'string' }],
    defaultConfig: { action: 'EXTRACT_TABLE', timeoutSeconds: 30 },
  },
  {
    type: 'ext:db_query',
    category: 'EXTERNAL',
    title: 'Database Query',
    subtitle: 'Query PostgreSQL or Supabase',
    description: 'Reads or writes records to external SQL database connector.',
    iconName: 'Database',
    badge: 'Data Sync',
    riskLevel: 'HIGH',
    inputs: [{ name: 'connectorKey', type: 'string' }, { name: 'query', type: 'string' }],
    outputs: [{ name: 'rows', type: 'array' }],
    defaultConfig: {},
  },
];
