export interface WorkflowNodeDefinition {
  type: string;
  category: 'TRIGGER' | 'LOGIC' | 'AI' | 'COMMUNICATION' | 'CRM' | 'DOCUMENTS' | 'EXTERNAL' | 'FINANCE';
  title: string;
  subtitle: string;
  description: string;
  iconName: string;
  badge: string;
  inputs?: Array<{ name: string; type: string; required?: boolean; description?: string }>;
  outputs?: Array<{ name: string; type: string; description?: string }>;
  defaultConfig?: Record<string, any>;
  riskLevel?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

export const NODE_CATALOG: WorkflowNodeDefinition[] = [
  // TRIGGERS
  {
    type: 'trigger:new_lead',
    category: 'TRIGGER',
    title: 'New Lead Ingestion',
    subtitle: 'Fires when a new prospect is ingested',
    description: 'Triggers workflow execution immediately after a new lead is detected via website, form, or CRM.',
    iconName: 'UserPlus',
    badge: 'CRM Event',
    defaultConfig: { sourceFilter: 'ALL' },
  },
  {
    type: 'trigger:whatsapp_received',
    category: 'TRIGGER',
    title: 'Inbound WhatsApp',
    subtitle: 'Incoming chat on WhatsApp Business API',
    description: 'Fires when an inbound WhatsApp message, button reply, or audio note is received.',
    iconName: 'MessageSquare',
    badge: 'WhatsApp',
    defaultConfig: {},
  },
  {
    type: 'trigger:document_uploaded',
    category: 'TRIGGER',
    title: 'Document Uploaded',
    subtitle: 'File deposited to vault or uploaded',
    description: 'Fires when a PDF invoice, agreement, receipt, or spec document is uploaded.',
    iconName: 'FileText',
    badge: 'OCR Trigger',
    defaultConfig: {},
  },
  {
    type: 'trigger:call_received',
    category: 'TRIGGER',
    title: 'Inbound Call Received',
    subtitle: 'Telephony detects incoming phone call',
    description: 'Fires when telephony detects an inbound phone call or missed call via Twilio/SIP.',
    iconName: 'PhoneIncoming',
    badge: 'Voice Event',
    defaultConfig: {},
  },
  {
    type: 'trigger:deal_stage_changed',
    category: 'TRIGGER',
    title: 'Deal Stage Changed',
    subtitle: 'Fires on pipeline stage movement',
    description: 'Triggers when a sales opportunity advances from Lead to Proposal, Negotiation, or Won.',
    iconName: 'Briefcase',
    badge: 'Sales Event',
    defaultConfig: { targetStage: 'ALL' },
  },
  {
    type: 'trigger:schedule',
    category: 'TRIGGER',
    title: 'CRON / Schedule Trigger',
    subtitle: 'Fires on scheduled recurrence',
    description: 'Fires on scheduled cadence (e.g. daily at 9:00 AM, hourly sweep, end-of-month dunning).',
    iconName: 'Clock',
    badge: 'Schedule',
    defaultConfig: { cron: '0 9 * * *' },
  },
  {
    type: 'trigger:webhook',
    category: 'TRIGGER',
    title: 'Custom Inbound Webhook',
    subtitle: 'Dedicated HTTP POST endpoint',
    description: 'Provides a secure dedicated URL to receive payloads from external systems and webhooks.',
    iconName: 'Zap',
    badge: 'Webhook',
    defaultConfig: { authRequired: true },
  },
  {
    type: 'trigger:manual',
    category: 'TRIGGER',
    title: 'Manual Dispatch',
    subtitle: 'Operator one-click execution',
    description: 'Allows human operators to initiate execution from CRM record page or admin dashboard.',
    iconName: 'Play',
    badge: 'Manual',
    defaultConfig: {},
  },

  // AI & INTELLIGENCE
  {
    type: 'ai:score',
    category: 'AI',
    title: 'AI Lead & ICP Score',
    subtitle: 'Calculates 0-100 buying intent score',
    description: 'Evaluates firmographics, domain health, and engagement signals to predict conversion.',
    iconName: 'Sparkles',
    badge: 'Predictive AI',
    defaultConfig: { targetMetric: 'ICP_FIT' },
  },
  {
    type: 'ai:classify',
    category: 'AI',
    title: 'AI Intent Classifier',
    subtitle: 'Sorts inquiries into routing categories',
    description: 'Classifies inbound emails, tickets, or messages into Sales, Support, Billing, or Escalation.',
    iconName: 'Sparkles',
    badge: 'Classifier',
    defaultConfig: { categories: ['Sales', 'Support', 'Billing', 'VIP'] },
  },
  {
    type: 'ai:generate',
    category: 'AI',
    title: 'AI Copywriter & Drafter',
    subtitle: 'Generates personalized sales responses',
    description: 'Drafts bespoke follow-up emails, proposals, or WhatsApp scripts using lead context.',
    iconName: 'Bot',
    badge: 'Generative AI',
    defaultConfig: { model: 'groq/compound', temperature: 0.7 },
  },
  {
    type: 'ai:vision_ocr',
    category: 'AI',
    title: 'Neural Vision OCR',
    subtitle: 'Extracts tabular invoice & receipt data',
    description: 'Neural vision scans invoice PDFs, extracts line items, VAT, and vendor bank details.',
    iconName: 'FileText',
    badge: 'Vision AI',
    defaultConfig: {},
  },
  {
    type: 'ai:swarm_agent',
    category: 'AI',
    title: 'Autonomous Agent Swarm',
    subtitle: 'Multi-agent goal-driven execution',
    description: 'Spawns autonomous agent with dynamic tool use, web research, and CRM data enrichment.',
    iconName: 'Bot',
    badge: 'Agent Swarm',
    riskLevel: 'MEDIUM',
    defaultConfig: { maxIterations: 5 },
  },

  // LOGIC & FLOW CONTROL
  {
    type: 'logic:if_else',
    category: 'LOGIC',
    title: 'If / Else Branch',
    subtitle: 'Conditional decision fork',
    description: 'Evaluates expressions (e.g. score >= 60, dealValue > $5,000) and branches True / False.',
    iconName: 'GitFork',
    badge: 'Conditional',
    defaultConfig: { field: 'leadScore', operator: 'GREATER_THAN', value: 60 },
  },
  {
    type: 'logic:human_approval',
    category: 'LOGIC',
    title: 'Human-In-The-Loop Approval',
    subtitle: 'Halts workflow for human review',
    description: 'Pauses workflow execution until manager or CFO reviews and approves in /automation/approvals.',
    iconName: 'ShieldAlert',
    badge: 'HITL Gate',
    riskLevel: 'HIGH',
    defaultConfig: { riskLevel: 'HIGH', timeoutHours: 48 },
  },
  {
    type: 'logic:delay',
    category: 'LOGIC',
    title: 'Time Delay / Wait',
    subtitle: 'Pause execution for duration',
    description: 'Suspends workflow in BullMQ queue for specified minutes, hours, or days.',
    iconName: 'Clock',
    badge: 'Scheduler',
    defaultConfig: { duration: 1, unit: 'HOURS' },
  },

  // COMMUNICATION
  {
    type: 'comm:whatsapp',
    category: 'COMMUNICATION',
    title: 'Send WhatsApp Message',
    subtitle: 'Instant WhatsApp template or dynamic text',
    description: 'Sends verified WhatsApp HSM template or conversational message with calendar link.',
    iconName: 'MessageSquare',
    badge: 'WhatsApp',
    defaultConfig: { message: 'Hi {{firstName}}! Thanks for checking out our platform.' },
  },
  {
    type: 'comm:email',
    category: 'COMMUNICATION',
    title: 'Send Personalized Email',
    subtitle: 'Dispatches branded email with tracking',
    description: 'Sends transactional or marketing email via SendGrid/SES with open and click telemetry.',
    iconName: 'Mail',
    badge: 'Email',
    defaultConfig: { subject: 'Follow up from our executive team' },
  },
  {
    type: 'comm:sms',
    category: 'COMMUNICATION',
    title: 'Send High-Priority SMS',
    subtitle: 'Twilio SMS urgent notification',
    description: 'Sends instant SMS confirmation or OTP code to prospect or assigned rep.',
    iconName: 'Smartphone',
    badge: 'SMS',
    defaultConfig: {},
  },

  // CRM & FINANCE
  {
    type: 'crm:add_activity',
    category: 'CRM',
    title: 'Record CRM Activity',
    subtitle: 'Logs timeline event or call note',
    description: 'Appends a structured event to the contact and company interaction history.',
    iconName: 'Clock',
    badge: 'CRM Task',
    defaultConfig: { type: 'NOTE', title: 'Automated workflow milestone' },
  },
  {
    type: 'crm:update_lead',
    category: 'CRM',
    title: 'Update Contact / Deal',
    subtitle: 'Modifies attributes or stage',
    description: 'Updates CRM pipeline status, owner assignment, or custom metadata fields.',
    iconName: 'Database',
    badge: 'CRM Record',
    defaultConfig: {},
  },
  {
    type: 'finance:post_khata',
    category: 'FINANCE',
    title: 'Post Dual Khata Ledger',
    subtitle: 'Double-entry journal voucher post',
    description: 'Creates balanced double-entry accounting records in Official and Management ledger books.',
    iconName: 'FileText',
    badge: 'Dual Khata',
    defaultConfig: { ledger: 'OFFICIAL' },
  },
  {
    type: 'ext:webhook',
    category: 'EXTERNAL',
    title: 'Outbound Webhook',
    subtitle: 'HTTP POST to Zapier, Make, or ERP',
    description: 'Calls external webhook endpoint with signature authentication.',
    iconName: 'Globe',
    badge: 'Webhook',
    defaultConfig: { method: 'POST' },
  },
];

export const STARTER_NODES = [
  {
    id: 'n1',
    type: 'studioNode',
    position: { x: 80, y: 160 },
    data: {
      type: 'trigger:new_lead',
      category: 'TRIGGER',
      title: 'New Lead Ingestion',
      subtitle: 'Triggers immediately upon new prospect capture via website or CRM',
      iconName: 'UserPlus',
      badge: 'CRM Trigger',
      status: 'IDLE',
      config: { sourceFilter: 'ALL' },
    },
  },
  {
    id: 'n2',
    type: 'studioNode',
    position: { x: 480, y: 160 },
    data: {
      type: 'ai:score',
      category: 'AI',
      title: 'AI ICP Score Evaluation',
      subtitle: 'Evaluates firmographics and assigns 0-100 buying intent score',
      iconName: 'Sparkles',
      badge: 'Predictive AI',
      status: 'IDLE',
      config: { targetMetric: 'ICP_FIT' },
    },
  },
  {
    id: 'n3',
    type: 'studioNode',
    position: { x: 880, y: 160 },
    data: {
      type: 'logic:if_else',
      category: 'LOGIC',
      title: 'High Intent Lead Gate',
      subtitle: 'Branches workflow if computed score >= 60 points',
      iconName: 'GitFork',
      badge: 'Conditional',
      status: 'IDLE',
      config: { field: 'leadScore', operator: 'GREATER_THAN', value: 60 },
    },
  },
  {
    id: 'n4',
    type: 'studioNode',
    position: { x: 1280, y: 80 },
    data: {
      type: 'comm:whatsapp',
      category: 'COMMUNICATION',
      title: 'WhatsApp VIP Concierge',
      subtitle: 'Sends instant calendar booking card to qualified prospect',
      iconName: 'MessageSquare',
      badge: 'WhatsApp',
      status: 'IDLE',
      config: { message: 'Hi {{firstName}}! Thanks for checking out Business OS.' },
    },
  },
  {
    id: 'n5',
    type: 'studioNode',
    position: { x: 1280, y: 280 },
    data: {
      type: 'crm:add_activity',
      category: 'CRM',
      title: 'Queue Low-Touch Nurture',
      subtitle: 'Records contact timeline note and enters weekly email digest',
      iconName: 'Clock',
      badge: 'CRM Task',
      status: 'IDLE',
      config: { type: 'NOTE', title: 'Low touch lead' },
    },
  },
];

export const STARTER_EDGES = [
  { id: 'e1-2', source: 'n1', target: 'n2', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
  { id: 'e2-3', source: 'n2', target: 'n3', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
  { id: 'e3-4', source: 'n3', target: 'n4', sourceHandle: 'true', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
  { id: 'e3-5', source: 'n3', target: 'n5', sourceHandle: 'false', animated: true, style: { stroke: '#f43f5e', strokeWidth: 2 } },
];

export const DEFAULT_WORKFLOWS_LIST = [
  {
    id: 'wf_lead_qual',
    name: 'Flagship Enterprise Lead Qualification & Fast-Track Routing',
    description: 'Enriches inbound leads with Apollo-style data, evaluates ICP score with Groq, and alerts sales Slack.',
    isActive: true,
    triggerType: 'trigger:new_lead',
    nodeCount: 5,
    lastRun: '10 mins ago',
    successRate: '99.1%',
  },
  {
    id: 'wf_wa_sales',
    name: 'WhatsApp Autonomous Sales Concierge',
    description: 'Engages inbound WhatsApp prospects, answers pricing queries, and books meetings on Google Calendar.',
    isActive: true,
    triggerType: 'trigger:whatsapp_received',
    nodeCount: 4,
    lastRun: '22 mins ago',
    successRate: '98.5%',
  },
  {
    id: 'wf_ocr_invoice',
    name: 'Autonomous OCR Invoice & Dual Khata Reconciler',
    description: 'Neural vision scans vendor invoices, checks CFO approval gate if > $1,000, and posts to Dual Khata ledger.',
    isActive: true,
    triggerType: 'trigger:document_uploaded',
    nodeCount: 4,
    lastRun: '1 hour ago',
    successRate: '100%',
  },
  {
    id: 'wf_missed_call',
    name: 'Missed Call Rapid AI Recovery',
    description: 'Detects unanswered customer calls and dispatches instant SMS and WhatsApp follow-up with calendar slot.',
    isActive: true,
    triggerType: 'trigger:call_received',
    nodeCount: 3,
    lastRun: '2 hours ago',
    successRate: '97.8%',
  },
];

export const DEFAULT_WORKFLOWS_DATA: Record<string, any> = {
  wf_lead_qual: {
    id: 'wf_lead_qual',
    name: 'Flagship Enterprise Lead Qualification & Fast-Track Routing',
    description: 'Enriches inbound leads with Apollo-style data, evaluates ICP score with Groq, and alerts sales Slack.',
    isActive: true,
    triggerType: 'trigger:new_lead',
    nodeCount: 5,
    lastRun: '10 mins ago',
    successRate: '99.1%',
    nodes: STARTER_NODES,
    edges: STARTER_EDGES,
  },
  wf_wa_sales: {
    id: 'wf_wa_sales',
    name: 'WhatsApp Autonomous Sales Concierge',
    description: 'Engages inbound WhatsApp prospects, answers pricing queries, and books meetings on Google Calendar.',
    isActive: true,
    triggerType: 'trigger:whatsapp_received',
    nodeCount: 4,
    lastRun: '22 mins ago',
    successRate: '98.5%',
    nodes: [
      {
        id: 'w1',
        type: 'studioNode',
        position: { x: 80, y: 160 },
        data: {
          type: 'trigger:whatsapp_received',
          category: 'TRIGGER',
          title: 'Inbound WhatsApp Message',
          subtitle: 'Prospect initiates inquiry via WhatsApp Business phone number',
          iconName: 'MessageSquare',
          badge: 'WhatsApp',
          status: 'IDLE',
        },
      },
      {
        id: 'w2',
        type: 'studioNode',
        position: { x: 480, y: 160 },
        data: {
          type: 'ai:classify',
          category: 'AI',
          title: 'Intent & Urgency Classification',
          subtitle: 'Categorizes query (Pricing, Demo, Support, Partnership)',
          iconName: 'Sparkles',
          badge: 'Groq AI',
          status: 'IDLE',
        },
      },
      {
        id: 'w3',
        type: 'studioNode',
        position: { x: 880, y: 160 },
        data: {
          type: 'ai:generate',
          category: 'AI',
          title: 'AI Contextual Response Drafter',
          subtitle: 'Generates helpful response with embedded calendar link',
          iconName: 'Bot',
          badge: 'Generative AI',
          status: 'IDLE',
        },
      },
      {
        id: 'w4',
        type: 'studioNode',
        position: { x: 1280, y: 160 },
        data: {
          type: 'comm:whatsapp',
          category: 'COMMUNICATION',
          title: 'Dispatch Instant WhatsApp Reply',
          subtitle: 'Sends verified interactive message back to user',
          iconName: 'MessageSquare',
          badge: 'WhatsApp API',
          status: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'ew1-2', source: 'w1', target: 'w2', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'ew2-3', source: 'w2', target: 'w3', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'ew3-4', source: 'w3', target: 'w4', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
  wf_ocr_invoice: {
    id: 'wf_ocr_invoice',
    name: 'Autonomous OCR Invoice & Dual Khata Reconciler',
    description: 'Neural vision scans vendor invoices, checks CFO approval gate if > $1,000, and posts to Dual Khata ledger.',
    isActive: true,
    triggerType: 'trigger:document_uploaded',
    nodeCount: 4,
    lastRun: '1 hour ago',
    successRate: '100%',
    nodes: [
      {
        id: 'inv1',
        type: 'studioNode',
        position: { x: 80, y: 160 },
        data: {
          type: 'trigger:document_uploaded',
          category: 'TRIGGER',
          title: 'Vendor Invoice PDF Upload',
          subtitle: 'Accounts Payable scans or uploads receipt',
          iconName: 'FileText',
          badge: 'OCR Trigger',
          status: 'IDLE',
        },
      },
      {
        id: 'inv2',
        type: 'studioNode',
        position: { x: 480, y: 160 },
        data: {
          type: 'ai:vision_ocr',
          category: 'AI',
          title: 'Neural Vision OCR Extraction',
          subtitle: 'Extracts vendor, subtotal, VAT, line items, and IBAN',
          iconName: 'FileText',
          badge: 'Vision AI',
          status: 'IDLE',
        },
      },
      {
        id: 'inv3',
        type: 'studioNode',
        position: { x: 880, y: 160 },
        data: {
          type: 'logic:human_approval',
          category: 'LOGIC',
          title: 'CFO High-Value Approval Gate',
          subtitle: 'Requires 1-click sign-off if total > $1,000',
          iconName: 'ShieldAlert',
          badge: 'HITL Gate',
          status: 'IDLE',
        },
      },
      {
        id: 'inv4',
        type: 'studioNode',
        position: { x: 1280, y: 160 },
        data: {
          type: 'finance:post_khata',
          category: 'FINANCE',
          title: 'Dual Khata Double-Entry Post',
          subtitle: 'Posts verified journal voucher to Official and Management books',
          iconName: 'FileText',
          badge: 'Dual Khata',
          status: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'einv1-2', source: 'inv1', target: 'inv2', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'einv2-3', source: 'inv2', target: 'inv3', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'einv3-4', source: 'inv3', target: 'inv4', sourceHandle: 'approved', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
  wf_missed_call: {
    id: 'wf_missed_call',
    name: 'Missed Call Rapid AI Recovery',
    description: 'Detects unanswered customer calls and dispatches instant SMS and WhatsApp follow-up with calendar slot.',
    isActive: true,
    triggerType: 'trigger:call_received',
    nodeCount: 3,
    lastRun: '2 hours ago',
    successRate: '97.8%',
    nodes: [
      {
        id: 'mc1',
        type: 'studioNode',
        position: { x: 80, y: 160 },
        data: {
          type: 'trigger:call_received',
          category: 'TRIGGER',
          title: 'Unanswered Incoming Call',
          subtitle: 'Customer called during peak hours with no agent available',
          iconName: 'PhoneIncoming',
          badge: 'Telephony',
          status: 'IDLE',
        },
      },
      {
        id: 'mc2',
        type: 'studioNode',
        position: { x: 480, y: 160 },
        data: {
          type: 'comm:sms',
          category: 'COMMUNICATION',
          title: 'Instant SMS Apology & Booking',
          subtitle: 'Sends immediate text: "Sorry we missed you! Book a slot here."',
          iconName: 'Smartphone',
          badge: 'Twilio SMS',
          status: 'IDLE',
        },
      },
      {
        id: 'mc3',
        type: 'studioNode',
        position: { x: 880, y: 160 },
        data: {
          type: 'crm:add_activity',
          category: 'CRM',
          title: 'Log Missed Call Milestone',
          subtitle: 'Creates high-priority callback task on sales rep board',
          iconName: 'Clock',
          badge: 'CRM Task',
          status: 'IDLE',
        },
      },
    ],
    edges: [
      { id: 'emc1-2', source: 'mc1', target: 'mc2', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
      { id: 'emc2-3', source: 'mc2', target: 'mc3', animated: true, style: { stroke: '#10b981', strokeWidth: 2 } },
    ],
  },
};
