export interface FeatureItem {
  id: string;
  name: string;
  shortDesc: string;
  category: number;
  categoryName: string;
  iconName: string;
  route: string;
  badge?: string;
  defaultInNiches: string[]; // which default niches include this
}

export interface FeatureCategory {
  id: number;
  name: string;
  icon: string;
  description: string;
}

export const FEATURE_CATEGORIES: FeatureCategory[] = [
  { id: 1, name: 'Core CRM & Operations', icon: '👥', description: 'Contact ledger, deals pipeline, tickets, tasks, employees & onboarding' },
  { id: 2, name: 'AI & Neural Autonomy', icon: '🧠', description: 'Enrichment, sentiment analysis, predictive scoring & vector AI' },
  { id: 3, name: 'Financials, Salary & Dual Khata', icon: '💰', description: 'Invoices, salary payroll, Dual Khata, quotes & taxes' },
  { id: 4, name: 'Multi-Industry Niche Hubs', icon: '🏥', description: 'Hospital EHR, Real Estate MLS, Restaurant POS & Retail Khata' },
  { id: 5, name: 'Marketing & Social Media', icon: '🚀', description: 'Social post generator, 4-network previews, email builder & stats' },
  { id: 6, name: 'B2B Lead Prospector', icon: '🎯', description: 'Apollo/ZoomInfo prospect database, filters & bulk CRM import' },
  { id: 7, name: 'OCR Neural Document Vision', icon: '📄', description: 'Receipt/invoice scanner, auto-extraction & schema synthesizer' },
  { id: 8, name: 'Real-Time Communication', icon: '💬', description: 'Team chat channels, embeddable live widgets & AI copilot' },
  { id: 9, name: 'Legal, E-Sign & Contracts', icon: '⚖️', description: 'Digital e-signatures, offer letters, NDAs & document vault' },
  { id: 10, name: 'Low-Code Platform Engine', icon: '🛠️', description: 'Custom objects, schema builder, dynamic forms & UI page builder' },
  { id: 11, name: 'Security, RBAC & Admin', icon: '🛡️', description: 'Super-admin console, audit logs, ABAC matrix & developer API' },
  { id: 12, name: 'Glassmorphism UX & Pricing', icon: '✨', description: 'Performance mode, dual-curve charts, usage credits & tiers' },
];

export const ALL_67_FEATURES: FeatureItem[] = [
  // 1. Core CRM & Operations
  {
    id: 'feat_contacts',
    name: 'Dynamic Contact & Account Management',
    shortDesc: 'Comprehensive contact directory with customer ledger & company links.',
    category: 1,
    categoryName: 'Core CRM & Operations',
    iconName: 'Users',
    route: '/',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_employee_org_tree',
    name: 'Employee Org Hierarchy Tree (CEO ➔ Manager ➔ Clerk)',
    shortDesc: 'Visual reporting tree mapping leadership, managers, leads, and clerks.',
    category: 1,
    categoryName: 'Core CRM & Operations',
    iconName: 'Network',
    route: '/directory',
    badge: 'Tree',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_deals',
    name: 'Visual Deal Pipeline & Stages',
    shortDesc: 'Interactive pipeline stages with predictive health scoring.',
    category: 1,
    categoryName: 'Core CRM & Operations',
    iconName: 'Briefcase',
    route: '/deals',
    defaultInNiches: ['all', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_projects',
    name: 'Project Milestone & Task Tracking',
    shortDesc: 'Sprint boards, kitchen queues, and delivery milestone tracker.',
    category: 1,
    categoryName: 'Core CRM & Operations',
    iconName: 'ClipboardList',
    route: '/projects',
    defaultInNiches: ['all', 'realestate', 'restaurant', 'sme', 'agency'],
  },
  {
    id: 'feat_tickets',
    name: 'Customer Support Helpdesk & Triage',
    shortDesc: 'Multi-priority ticket inbox with customer inquiry history.',
    category: 1,
    categoryName: 'Core CRM & Operations',
    iconName: 'Ticket',
    route: '/tickets',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_slas',
    name: 'SLA Escalation Policy Engine',
    shortDesc: 'Service level agreement countdowns and breach mitigation.',
    category: 1,
    categoryName: 'Core CRM & Operations',
    iconName: 'Clock',
    route: '/slas',
    defaultInNiches: ['all', 'hospital', 'sme'],
  },
  {
    id: 'feat_activity_timeline',
    name: 'Unified Activity & Interaction Timeline',
    shortDesc: 'Chronological timeline of calls, meetings, emails & notes.',
    category: 1,
    categoryName: 'Core CRM & Operations',
    iconName: 'Activity',
    route: '/contacts/1',
    defaultInNiches: ['all', 'hospital', 'realestate', 'sme', 'agency'],
  },
  {
    id: 'feat_global_search',
    name: 'Global Command Palette (⌘K)',
    shortDesc: 'Keyboard-driven search & action shortcuts across all records.',
    category: 1,
    categoryName: 'Core CRM & Operations',
    iconName: 'Search',
    route: '/dashboard',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_onboarding',
    name: 'Employee Onboarding Kanban Pipeline',
    shortDesc: '5-stage hire tracker from offer accepted to equipment setup.',
    category: 1,
    categoryName: 'Core CRM & Operations',
    iconName: 'Contact',
    route: '/onboarding',
    defaultInNiches: ['all', 'hospital', 'restaurant', 'retail', 'sme'],
  },

  // 2. Autonomous AI & Predictive Intelligence (7)
  {
    id: 'feat_contact_enrichment',
    name: 'Automatic Contact Enrichment AI',
    shortDesc: 'Auto-scans registries and profiles to fill company size & tech stack.',
    category: 2,
    categoryName: 'AI & Neural Autonomy',
    iconName: 'Sparkles',
    route: '/',
    defaultInNiches: ['all', 'sme', 'agency'],
  },
  {
    id: 'feat_sentiment_analysis',
    name: 'NLP Client Sentiment Scoring',
    shortDesc: 'Scores customer sentiment (Happy, Neutral, At-Risk) in real time.',
    category: 2,
    categoryName: 'AI & Neural Autonomy',
    iconName: 'Brain',
    route: '/tickets',
    defaultInNiches: ['all', 'hospital', 'restaurant', 'sme', 'agency'],
  },
  {
    id: 'feat_smart_summarization',
    name: 'Smart 3-Bullet Pre-Call Summarization',
    shortDesc: 'Generative AI summary of customer touchpoints before calls.',
    category: 2,
    categoryName: 'AI & Neural Autonomy',
    iconName: 'FileText',
    route: '/deals',
    defaultInNiches: ['all', 'realestate', 'sme', 'agency'],
  },
  {
    id: 'feat_predictive_scoring',
    name: 'Predictive Deal Win Probability',
    shortDesc: 'Statistical machine learning conversion likelihood scoring.',
    category: 2,
    categoryName: 'AI & Neural Autonomy',
    iconName: 'TrendingUp',
    route: '/deals',
    defaultInNiches: ['all', 'realestate', 'sme'],
  },
  {
    id: 'feat_pipeline_anomalies',
    name: 'Deal Health & Pipeline Stalling Alerts',
    shortDesc: 'Flags deals lingering too long in negotiation stages.',
    category: 2,
    categoryName: 'AI & Neural Autonomy',
    iconName: 'AlertTriangle',
    route: '/deals',
    defaultInNiches: ['all', 'realestate', 'sme'],
  },
  {
    id: 'feat_next_best_action',
    name: 'Next Best Action (NBA) Engine',
    shortDesc: 'Autonomous recommendations for reps on immediate next steps.',
    category: 2,
    categoryName: 'AI & Neural Autonomy',
    iconName: 'Zap',
    route: '/deals',
    defaultInNiches: ['all', 'realestate', 'sme', 'agency'],
  },
  {
    id: 'feat_vector_knowledge',
    name: 'Vector Knowledge Base & Prompt Studio',
    shortDesc: 'Enterprise document embeddings and customizable LLM prompts.',
    category: 2,
    categoryName: 'AI & Neural Autonomy',
    iconName: 'Database',
    route: '/platform/ai',
    defaultInNiches: ['all', 'sme'],
  },

  // 3. Financials, Billing, CPQ & Dual Khata Ledger (8)
  {
    id: 'feat_invoices',
    name: 'Commercial Invoicing & PDF Export',
    shortDesc: 'Professional itemized invoices with real-time PDF generation.',
    category: 3,
    categoryName: 'Financials, Salary & Dual Khata',
    iconName: 'Receipt',
    route: '/invoices',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_salary_payroll',
    name: 'Salary System & Monthly Payroll Engine',
    shortDesc: 'Base salary, allowances, statutory tax deductions & payslip generator.',
    category: 3,
    categoryName: 'Financials, Salary & Dual Khata',
    iconName: 'DollarSign',
    route: '/directory',
    badge: 'Payroll',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_khata_ledger',
    name: 'Dual Khata Ledger & Cash-Flow Tracker',
    shortDesc: 'Dual debit/credit balance bookkeeping for customers & vendors.',
    category: 3,
    categoryName: 'Financials, Salary & Dual Khata',
    iconName: 'Database',
    route: '/dashboard',
    badge: 'Khata',
    defaultInNiches: ['all', 'retail', 'restaurant', 'realestate', 'sme'],
  },
  {
    id: 'feat_cpq_quotes',
    name: 'Commercial CPQ Proposals & Quotes',
    shortDesc: 'Configure, Price, Quote proposals with dynamic discount tiers.',
    category: 3,
    categoryName: 'Financials, Salary & Dual Khata',
    iconName: 'FileBadge',
    route: '/quotes',
    defaultInNiches: ['all', 'realestate', 'sme', 'agency'],
  },
  {
    id: 'feat_subscriptions',
    name: 'Recurring SaaS Subscriptions & MRR',
    shortDesc: 'Seat licenses, billing cycles, renewals, and churn metrics.',
    category: 3,
    categoryName: 'Financials, Salary & Dual Khata',
    iconName: 'DollarSign',
    route: '/subscriptions',
    defaultInNiches: ['all', 'sme'],
  },
  {
    id: 'feat_price_books',
    name: 'Multi-Tier Price Books & Catalogs',
    shortDesc: 'Menu pricing, pharmacy drug formularies, and product tiers.',
    category: 3,
    categoryName: 'Financials, Salary & Dual Khata',
    iconName: 'Layers',
    route: '/price-books',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'agency'],
  },
  {
    id: 'feat_payment_links',
    name: 'Instant Payment Links & POS QR Codes',
    shortDesc: 'Direct Stripe checkout links and dynamic table QR codes.',
    category: 3,
    categoryName: 'Financials, Salary & Dual Khata',
    iconName: 'Zap',
    route: '/payment-links',
    defaultInNiches: ['all', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_taxes',
    name: 'Multi-Jurisdiction Sales Tax (VAT/GST)',
    shortDesc: 'Automated regional tax calculations and compliance rules.',
    category: 3,
    categoryName: 'Financials, Salary & Dual Khata',
    iconName: 'Receipt',
    route: '/taxes',
    defaultInNiches: ['all', 'retail', 'restaurant', 'sme'],
  },

  // 4. Multi-Industry Niche Hubs (5)
  {
    id: 'feat_hospital_hub',
    name: 'Hospital Command Hub & Bed Occupancy',
    shortDesc: 'Clinical telemetry, patient EHR triage, and on-call doctor queue.',
    category: 4,
    categoryName: 'Multi-Industry Niche Hubs',
    iconName: 'Stethoscope',
    route: '/industry/hospital',
    defaultInNiches: ['all', 'hospital'],
  },
  {
    id: 'feat_realestate_hub',
    name: 'Real Estate Property & MLS Portfolio',
    shortDesc: 'Property square footage, escrow milestones, and open-house tours.',
    category: 4,
    categoryName: 'Multi-Industry Niche Hubs',
    iconName: 'Home',
    route: '/industry/realestate',
    defaultInNiches: ['all', 'realestate'],
  },
  {
    id: 'feat_restaurant_hub',
    name: 'Restaurant Table Floor Plan & POS Orders',
    shortDesc: 'Live dining floor map, kitchen ticket queue (KOT), and VIP regulars.',
    category: 4,
    categoryName: 'Multi-Industry Niche Hubs',
    iconName: 'UtensilsCrossed',
    route: '/industry/restaurant',
    defaultInNiches: ['all', 'restaurant'],
  },
  {
    id: 'feat_retail_hub',
    name: 'Retail POS Cashier & Barcode Scanner',
    shortDesc: 'Counter register, barcode SKU inventory, and customer credit ledger.',
    category: 4,
    categoryName: 'Multi-Industry Niche Hubs',
    iconName: 'ShoppingBag',
    route: '/industry/retail',
    defaultInNiches: ['all', 'retail'],
  },
  {
    id: 'feat_industry_switcher',
    name: 'Instant Niche Profile Studio',
    shortDesc: 'Adapts navigation, vocabulary, and feature presets on the fly.',
    category: 4,
    categoryName: 'Multi-Industry Niche Hubs',
    iconName: 'Sparkles',
    route: '/industry',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },

  // 5. Marketing, Social Media & Email Suite (8)
  {
    id: 'feat_social_composer',
    name: 'Multi-Channel AI Social Post Generator',
    shortDesc: 'Creates high-converting social copy across networks simultaneously.',
    category: 5,
    categoryName: 'Marketing & Social Media',
    iconName: 'Share2',
    route: '/social',
    defaultInNiches: ['all', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_social_previews',
    name: '4-Network Live Preview Simulators',
    shortDesc: 'Pixel-perfect live previews for 𝕏, Facebook, Instagram & LinkedIn.',
    category: 5,
    categoryName: 'Marketing & Social Media',
    iconName: 'Share2',
    route: '/social',
    defaultInNiches: ['all', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_social_queue',
    name: 'Social Media Scheduled Post Queue',
    shortDesc: 'Manage queued publishing times and post engagement telemetry.',
    category: 5,
    categoryName: 'Marketing & Social Media',
    iconName: 'Calendar',
    route: '/social',
    defaultInNiches: ['all', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_email_builder',
    name: 'Drag-and-Drop Visual Email Builder',
    shortDesc: 'Design responsive marketing emails with live desktop/mobile previews.',
    category: 5,
    categoryName: 'Marketing & Social Media',
    iconName: 'Mail',
    route: '/email-marketing',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_email_inbox_sim',
    name: 'Dual Viewport Email Inbox Simulator',
    shortDesc: 'Instant preview toggle between desktop and mobile client viewports.',
    category: 5,
    categoryName: 'Marketing & Social Media',
    iconName: 'Mail',
    route: '/email-marketing',
    defaultInNiches: ['all', 'sme', 'agency'],
  },
  {
    id: 'feat_email_merge_tags',
    name: 'Dynamic Personalization Merge Tags',
    shortDesc: '1-click variable insertion for first name, company & deal value.',
    category: 5,
    categoryName: 'Marketing & Social Media',
    iconName: 'Sparkles',
    route: '/email-marketing',
    defaultInNiches: ['all', 'sme', 'agency'],
  },
  {
    id: 'feat_email_telemetry',
    name: 'Live Email Open & Click Telemetry',
    shortDesc: 'Real-time telemetry stream of opens, link clicks & delivery stats.',
    category: 5,
    categoryName: 'Marketing & Social Media',
    iconName: 'Activity',
    route: '/email-marketing',
    defaultInNiches: ['all', 'sme', 'agency'],
  },
  {
    id: 'feat_email_templates',
    name: 'High-Converting Template Library',
    shortDesc: 'Pre-built email templates for SaaS launches, B2B sales & promos.',
    category: 5,
    categoryName: 'Marketing & Social Media',
    iconName: 'Layers',
    route: '/email-marketing',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },

  // 6. B2B Lead Prospector & Bulk Ingestion (4)
  {
    id: 'feat_b2b_database',
    name: '275M+ B2B Prospect Database',
    shortDesc: 'Search verified leads simulated across Apollo, ZoomInfo & UpLead.',
    category: 6,
    categoryName: 'B2B Lead Prospector',
    iconName: 'Database',
    route: '/lead-prospector',
    badge: '275M+',
    defaultInNiches: ['all', 'sme', 'agency', 'realestate'],
  },
  {
    id: 'feat_b2b_filters',
    name: 'Granular Prospect Targeting Filters',
    shortDesc: 'Filter by industry, employee count, annual revenue, and geography.',
    category: 6,
    categoryName: 'B2B Lead Prospector',
    iconName: 'Filter',
    route: '/lead-prospector',
    defaultInNiches: ['all', 'sme', 'agency'],
  },
  {
    id: 'feat_b2b_bulk_import',
    name: '1-Click Bulk CRM Lead Ingestion',
    shortDesc: 'Select multiple prospects and batch import them into contacts.',
    category: 6,
    categoryName: 'B2B Lead Prospector',
    iconName: 'Download',
    route: '/lead-prospector',
    defaultInNiches: ['all', 'sme', 'agency'],
  },
  {
    id: 'feat_b2b_enrichment',
    name: 'Verified Direct Dials & Emails',
    shortDesc: 'Enriched metadata including corporate emails and LinkedIn profiles.',
    category: 6,
    categoryName: 'B2B Lead Prospector',
    iconName: 'CheckCircle2',
    route: '/lead-prospector',
    defaultInNiches: ['all', 'sme', 'agency'],
  },

  // 7. OCR & Neural Vision Processing (3)
  {
    id: 'feat_ocr_camera_capture',
    name: 'Document Camera & Image Ingestion',
    shortDesc: 'Upload or capture physical receipts, invoices, and bills on mobile/desktop.',
    category: 7,
    categoryName: 'OCR Neural Document Vision',
    iconName: 'Camera',
    route: '/ocr-invoice',
    badge: 'OCR',
    defaultInNiches: ['all', 'hospital', 'restaurant', 'retail', 'sme'],
  },
  {
    id: 'feat_ocr_vision_extraction',
    name: 'Automated Neural Vision Extraction',
    shortDesc: 'Neural OCR extracts vendor, date, line items, and totals automatically.',
    category: 7,
    categoryName: 'OCR Neural Document Vision',
    iconName: 'Scan',
    route: '/ocr-invoice',
    defaultInNiches: ['all', 'hospital', 'restaurant', 'retail', 'sme'],
  },
  {
    id: 'feat_ocr_schema_synthesizer',
    name: 'Smart Schema Synthesizer',
    shortDesc: 'Analyzes document structures to auto-generate matching database schemas.',
    category: 7,
    categoryName: 'OCR Neural Document Vision',
    iconName: 'Sparkles',
    route: '/smart-upload',
    defaultInNiches: ['all', 'sme'],
  },

  // 8. Real-Time Communications & Embedded Chat (4)
  {
    id: 'feat_team_chat',
    name: 'Internal Team Messaging Channels',
    shortDesc: 'Real-time team chat with channel support and direct messages.',
    category: 8,
    categoryName: 'Real-Time Communication',
    iconName: 'MessageSquare',
    route: '/chat',
    defaultInNiches: ['all', 'hospital', 'restaurant', 'sme', 'agency'],
  },
  {
    id: 'feat_chat_widget_builder',
    name: 'Embeddable Live Chat Widget Builder',
    shortDesc: 'Lightweight JavaScript snippet to embed live support on external websites.',
    category: 8,
    categoryName: 'Real-Time Communication',
    iconName: 'Code2',
    route: '/chat-widgets',
    defaultInNiches: ['all', 'sme', 'agency', 'retail'],
  },
  {
    id: 'feat_chat_widget_customizer',
    name: 'Chat Theme & Domain Whitelisting',
    shortDesc: 'Customize greeting triggers, colors, and allowed CORS domains.',
    category: 8,
    categoryName: 'Real-Time Communication',
    iconName: 'Sliders',
    route: '/chat-widgets',
    defaultInNiches: ['all', 'sme', 'agency'],
  },
  {
    id: 'feat_ai_copilot',
    name: 'Omnipresent Floating AI Copilot',
    shortDesc: 'Quick questions, natural language CRM queries, and action dispatch.',
    category: 8,
    categoryName: 'Real-Time Communication',
    iconName: 'Bot',
    route: '/dashboard',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },

  // 9. Legal, E-Signatures, Agreements & HR (5)
  {
    id: 'feat_e_signatures',
    name: 'Digital E-Signature Signing Studio',
    shortDesc: 'Tamper-proof digital signatures and audit certificate verification.',
    category: 9,
    categoryName: 'Legal, E-Sign & Contracts',
    iconName: 'FileSignature',
    route: '/e-signatures',
    defaultInNiches: ['all', 'hospital', 'realestate', 'sme', 'agency'],
  },
  {
    id: 'feat_offer_letters',
    name: 'Executive Offer Letter Generator',
    shortDesc: 'Legally binding employment offers with salary and equity grant parameters.',
    category: 9,
    categoryName: 'Legal, E-Sign & Contracts',
    iconName: 'FileText',
    route: '/offer-letters',
    defaultInNiches: ['all', 'sme', 'hospital'],
  },
  {
    id: 'feat_ndas',
    name: 'Mutual & Vendor NDA Contract Ledger',
    shortDesc: 'Non-disclosure agreement generator with audit certificates.',
    category: 9,
    categoryName: 'Legal, E-Sign & Contracts',
    iconName: 'FileCheck',
    route: '/ndas',
    defaultInNiches: ['all', 'realestate', 'sme', 'agency'],
  },
  {
    id: 'feat_doc_vault',
    name: 'Enterprise Document Vault',
    shortDesc: 'Cloud file explorer with folder hierarchies and permission tags.',
    category: 9,
    categoryName: 'Legal, E-Sign & Contracts',
    iconName: 'Folder',
    route: '/documents',
    defaultInNiches: ['all', 'hospital', 'realestate', 'sme', 'agency'],
  },
  {
    id: 'feat_s3_uploads',
    name: 'AWS S3 Presigned URL & Quota Manager',
    shortDesc: 'Direct cloud upload signer with storage quota dials.',
    category: 9,
    categoryName: 'Legal, E-Sign & Contracts',
    iconName: 'CloudUpload',
    route: '/s3-uploads',
    defaultInNiches: ['all', 'sme'],
  },

  // 10. Low-Code Engine & Custom Objects (5)
  {
    id: 'feat_schema_builder',
    name: 'Visual Custom Object Schema Builder',
    shortDesc: 'Define custom database entities and relational foreign key fields.',
    category: 10,
    categoryName: 'Low-Code Platform Engine',
    iconName: 'Database',
    route: '/platform/schema',
    defaultInNiches: ['all', 'sme'],
  },
  {
    id: 'feat_dynamic_form_table',
    name: 'Dynamic Form & Table Auto-Renderer',
    shortDesc: 'Auto-generates functional UI tables and forms for any custom entity.',
    category: 10,
    categoryName: 'Low-Code Platform Engine',
    iconName: 'Layers',
    route: '/platform/objects',
    defaultInNiches: ['all', 'sme'],
  },
  {
    id: 'feat_lowcode_kanban',
    name: 'Low-Code Kanban Board Builder',
    shortDesc: 'Converts any object select field into a drag-and-drop workflow board.',
    category: 10,
    categoryName: 'Low-Code Platform Engine',
    iconName: 'Briefcase',
    route: '/platform/objects',
    defaultInNiches: ['all', 'sme'],
  },
  {
    id: 'feat_nav_builder',
    name: 'Drag-and-Drop Sidebar Navigation Designer',
    shortDesc: 'Customize menu layout and item ordering per user role.',
    category: 10,
    categoryName: 'Low-Code Platform Engine',
    iconName: 'Sliders',
    route: '/platform/navigation',
    defaultInNiches: ['all', 'sme'],
  },
  {
    id: 'feat_dashboard_builder',
    name: 'Drag-and-Drop Dashboard UI Builder',
    shortDesc: 'Visual canvas to position metric cards, charts, and table widgets.',
    category: 10,
    categoryName: 'Low-Code Platform Engine',
    iconName: 'LayoutDashboard',
    route: '/customization',
    defaultInNiches: ['all', 'sme', 'agency'],
  },

  // 11. Security, Compliance & Super-Admin (6)
  {
    id: 'feat_super_admin',
    name: 'Multi-Tenant Super-Admin Console',
    shortDesc: 'Manage tenant accounts, seat allocations, and platform licenses.',
    category: 11,
    categoryName: 'Security, RBAC & Admin',
    iconName: 'Building',
    route: '/super-admin',
    defaultInNiches: ['all'],
  },
  {
    id: 'feat_audit_logs',
    name: 'Immutable SOC2 / HIPAA Audit Event Logs',
    shortDesc: 'Chronological actor activity stream for enterprise compliance.',
    category: 11,
    categoryName: 'Security, RBAC & Admin',
    iconName: 'ShieldAlert',
    route: '/audit-logs',
    defaultInNiches: ['all', 'hospital', 'sme'],
  },
  {
    id: 'feat_rbac_matrix',
    name: 'Granular RBAC & ABAC Permission Matrix',
    shortDesc: 'Object and field-level permission grids (Create, Read, Update, Delete).',
    category: 11,
    categoryName: 'Security, RBAC & Admin',
    iconName: 'ShieldCheck',
    route: '/platform/roles',
    defaultInNiches: ['all', 'hospital', 'sme'],
  },
  {
    id: 'feat_localization',
    name: 'Multi-Language Translation Dictionary',
    shortDesc: 'Live dictionary supporting English, Spanish, French, and German.',
    category: 11,
    categoryName: 'Security, RBAC & Admin',
    iconName: 'Globe2',
    route: '/localization',
    defaultInNiches: ['all', 'sme', 'retail'],
  },
  {
    id: 'feat_search_cluster',
    name: 'Full-Text Search Engine Cluster Console',
    shortDesc: 'Cluster telemetry, shard health, and index reindexing tools.',
    category: 11,
    categoryName: 'Security, RBAC & Admin',
    iconName: 'SearchCheck',
    route: '/search-index',
    defaultInNiches: ['all'],
  },
  {
    id: 'feat_developer_api',
    name: 'Developer API Tokens & Webhooks',
    shortDesc: 'API keys, webhook endpoints, and rate-limiting rules.',
    category: 11,
    categoryName: 'Security, RBAC & Admin',
    iconName: 'Code2',
    route: '/developer',
    defaultInNiches: ['all', 'sme'],
  },

  // 12. Glassmorphism UX & Monetization (4)
  {
    id: 'feat_obsidian_glass',
    name: 'Dark Obsidian Glassmorphism System',
    shortDesc: 'Frosted blur cards, radial warm ambient glows, and micro-animations.',
    category: 12,
    categoryName: 'Glassmorphism UX & Pricing',
    iconName: 'Sparkles',
    route: '/dashboard',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_interactive_charts',
    name: 'Dual-Curve Financial & Donut Charts',
    shortDesc: 'Interactive bezier curves and circular ARR target gauges.',
    category: 12,
    categoryName: 'Glassmorphism UX & Pricing',
    iconName: 'TrendingUp',
    route: '/dashboard',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_performance_mode',
    name: 'High-Contrast GPU-Lite Performance Toggle',
    shortDesc: 'Solid obsidian surfaces with WCAG AAA contrast for low-spec hardware.',
    category: 12,
    categoryName: 'Glassmorphism UX & Pricing',
    iconName: 'Sliders',
    route: '/dashboard',
    defaultInNiches: ['all', 'hospital', 'realestate', 'restaurant', 'retail', 'sme', 'agency'],
  },
  {
    id: 'feat_tiered_monetization',
    name: 'Tiered Pricing Suites & Usage Metering',
    shortDesc: 'Specialized packaging editions with live credit metering & top-up.',
    category: 12,
    categoryName: 'Glassmorphism UX & Pricing',
    iconName: 'DollarSign',
    route: '/subscriptions',
    defaultInNiches: ['all', 'sme'],
  },
];
