import { IndustryNiche } from '@/components/industry/IndustryContext';

export interface EmployeeNode {
  id: string;
  firstName: string;
  lastName: string;
  jobTitle: string;
  department: string;
  level: number; // 0: CEO/Director, 1: Manager/VP, 2: Team Lead/Supervisor, 3: Clerk/Staff/Associate
  managerId: string | null;
  email: string;
  phone: string;
  avatar: string;
  startDate: string;
  employmentType: 'Full-Time' | 'Part-Time' | 'Contractor';
  salary: {
    baseMonthly: number;
    allowances: number;
    bonus: number;
    taxDeductions: number;
    netMonthly: number;
    currency: string;
    paymentStatus: 'PAID' | 'PROCESSING' | 'PENDING';
    lastPayDate: string;
  };
  niche: IndustryNiche;
}

export const INITIAL_NICHE_EMPLOYEES: Record<IndustryNiche, EmployeeNode[]> = {
  all: [
    {
      id: 'emp_01',
      firstName: 'Alexander',
      lastName: 'Wright',
      jobTitle: 'Chief Executive Officer (CEO)',
      department: 'Executive Leadership',
      level: 0,
      managerId: null,
      email: 'a.wright@businessos.io',
      phone: '+1 (555) 019-2831',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-01-15',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 18500,
        allowances: 2500,
        bonus: 5000,
        taxDeductions: 4200,
        netMonthly: 21800,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'all',
    },
    {
      id: 'emp_02',
      firstName: 'Sophia',
      lastName: 'Martinez',
      jobTitle: 'VP of Enterprise Sales & Operations (Manager)',
      department: 'Sales & Revenue',
      level: 1,
      managerId: 'emp_01',
      email: 's.martinez@businessos.io',
      phone: '+1 (555) 392-8812',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      startDate: '2024-03-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 12000,
        allowances: 1500,
        bonus: 2500,
        taxDeductions: 2600,
        netMonthly: 13400,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'all',
    },
    {
      id: 'emp_03',
      firstName: 'David',
      lastName: 'Chen',
      jobTitle: 'VP of Engineering & Tech (Manager)',
      department: 'Engineering',
      level: 1,
      managerId: 'emp_01',
      email: 'd.chen@businessos.io',
      phone: '+1 (555) 772-9104',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-08-10',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 13500,
        allowances: 1800,
        bonus: 2000,
        taxDeductions: 2900,
        netMonthly: 14400,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'all',
    },
    {
      id: 'emp_04',
      firstName: 'Liam',
      lastName: 'Zhang',
      jobTitle: 'Senior Account Executive (Team Lead)',
      department: 'Sales & Revenue',
      level: 2,
      managerId: 'emp_02',
      email: 'l.zhang@businessos.io',
      phone: '+1 (555) 431-7782',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      startDate: '2024-09-15',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 7500,
        allowances: 800,
        bonus: 1800,
        taxDeductions: 1600,
        netMonthly: 8500,
        currency: '$',
        paymentStatus: 'PROCESSING',
        lastPayDate: '2026-08-28',
      },
      niche: 'all',
    },
    {
      id: 'emp_05',
      firstName: 'Elena',
      lastName: 'Rostova',
      jobTitle: 'Lead Software Architect (Team Lead)',
      department: 'Engineering',
      level: 2,
      managerId: 'emp_03',
      email: 'e.rostova@businessos.io',
      phone: '+1 (555) 902-3319',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-01-10',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 9000,
        allowances: 1000,
        bonus: 1200,
        taxDeductions: 1900,
        netMonthly: 9300,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'all',
    },
    {
      id: 'emp_06',
      firstName: 'Marcus',
      lastName: 'Brody',
      jobTitle: 'CRM Billing & Operations Clerk',
      department: 'Sales & Revenue',
      level: 3,
      managerId: 'emp_04',
      email: 'm.brody@businessos.io',
      phone: '+1 (555) 129-4458',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-06-20',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 4200,
        allowances: 400,
        bonus: 300,
        taxDeductions: 750,
        netMonthly: 4150,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'all',
    },
    {
      id: 'emp_07',
      firstName: 'Chloe',
      lastName: 'Dubois',
      jobTitle: 'Customer Support & Helpdesk Clerk',
      department: 'Engineering',
      level: 3,
      managerId: 'emp_05',
      email: 'c.dubois@businessos.io',
      phone: '+1 (555) 884-1290',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-11-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 3800,
        allowances: 350,
        bonus: 250,
        taxDeductions: 680,
        netMonthly: 3720,
        currency: '$',
        paymentStatus: 'PENDING',
        lastPayDate: '2026-08-28',
      },
      niche: 'all',
    },
  ],

  hospital: [
    {
      id: 'hosp_01',
      firstName: 'Dr. Arthur',
      lastName: 'Sterling, MD',
      jobTitle: 'Chief Medical Officer (CMO / CEO)',
      department: 'Executive Medical Board',
      level: 0,
      managerId: null,
      email: 'a.sterling@hospital.org',
      phone: '+1 (555) 201-9988',
      avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
      startDate: '2022-04-10',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 24000,
        allowances: 3000,
        bonus: 6000,
        taxDeductions: 5500,
        netMonthly: 27500,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'hospital',
    },
    {
      id: 'hosp_02',
      firstName: 'Dr. Evelyn',
      lastName: 'Vance, MD',
      jobTitle: 'Head of Surgery & Trauma (Manager)',
      department: 'Surgical Department',
      level: 1,
      managerId: 'hosp_01',
      email: 'e.vance@hospital.org',
      phone: '+1 (555) 302-8877',
      avatar: 'https://images.unsplash.com/photo-1594824813501-44754528448f?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-05-15',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 19500,
        allowances: 2000,
        bonus: 4000,
        taxDeductions: 4200,
        netMonthly: 21300,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'hospital',
    },
    {
      id: 'hosp_03',
      firstName: 'Sister Mary',
      lastName: 'Jenkins, RN',
      jobTitle: 'Chief of Nursing & Patient Care (Manager)',
      department: 'Nursing & Inpatient Care',
      level: 1,
      managerId: 'hosp_01',
      email: 'm.jenkins@hospital.org',
      phone: '+1 (555) 441-2980',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-09-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 11000,
        allowances: 1200,
        bonus: 1500,
        taxDeductions: 2200,
        netMonthly: 11500,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'hospital',
    },
    {
      id: 'hosp_04',
      firstName: 'Dr. Julian',
      lastName: 'Bashir',
      jobTitle: 'Attending Anesthesiologist (Team Lead)',
      department: 'Surgical Department',
      level: 2,
      managerId: 'hosp_02',
      email: 'j.bashir@hospital.org',
      phone: '+1 (555) 887-3321',
      avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
      startDate: '2024-02-18',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 14500,
        allowances: 1500,
        bonus: 2500,
        taxDeductions: 3100,
        netMonthly: 15400,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'hospital',
    },
    {
      id: 'hosp_05',
      firstName: 'Claire',
      lastName: 'Temple',
      jobTitle: 'Registered Triage Nurse (Staff)',
      department: 'Nursing & Inpatient Care',
      level: 3,
      managerId: 'hosp_03',
      email: 'c.temple@hospital.org',
      phone: '+1 (555) 991-0023',
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-03-12',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 5500,
        allowances: 600,
        bonus: 500,
        taxDeductions: 980,
        netMonthly: 5620,
        currency: '$',
        paymentStatus: 'PROCESSING',
        lastPayDate: '2026-08-28',
      },
      niche: 'hospital',
    },
    {
      id: 'hosp_06',
      firstName: 'Gail',
      lastName: 'McConaughey',
      jobTitle: 'Medical Admissions & Records Clerk',
      department: 'Executive Medical Board',
      level: 3,
      managerId: 'hosp_03',
      email: 'g.mcconaughey@hospital.org',
      phone: '+1 (555) 773-4411',
      avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-08-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 3900,
        allowances: 400,
        bonus: 200,
        taxDeductions: 690,
        netMonthly: 3810,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'hospital',
    },
  ],

  realestate: [
    {
      id: 're_01',
      firstName: 'Richard',
      lastName: 'Sterling',
      jobTitle: 'Principal Managing Broker (CEO)',
      department: 'Brokerage Leadership',
      level: 0,
      managerId: null,
      email: 'r.sterling@luxuryrealty.com',
      phone: '+1 (555) 883-1029',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
      startDate: '2021-06-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 15000,
        allowances: 2500,
        bonus: 12000,
        taxDeductions: 4800,
        netMonthly: 24700,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'realestate',
    },
    {
      id: 're_02',
      firstName: 'Victoria',
      lastName: 'Sinclair',
      jobTitle: 'Senior Commercial Listing Director (Manager)',
      department: 'Commercial MLS Division',
      level: 1,
      managerId: 're_01',
      email: 'v.sinclair@luxuryrealty.com',
      phone: '+1 (555) 440-2918',
      avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-02-15',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 9500,
        allowances: 1500,
        bonus: 6500,
        taxDeductions: 2800,
        netMonthly: 14700,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'realestate',
    },
    {
      id: 're_03',
      firstName: 'Lucas',
      lastName: 'Davenport',
      jobTitle: 'Senior Escrow Officer (Team Lead)',
      department: 'Contracts & Escrow',
      level: 2,
      managerId: 're_02',
      email: 'l.davenport@luxuryrealty.com',
      phone: '+1 (555) 671-8890',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      startDate: '2024-07-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 6800,
        allowances: 800,
        bonus: 2000,
        taxDeductions: 1450,
        netMonthly: 8150,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'realestate',
    },
    {
      id: 're_04',
      firstName: 'Amara',
      lastName: 'Okafor',
      jobTitle: 'Escrow & MLS Listing Clerk',
      department: 'Contracts & Escrow',
      level: 3,
      managerId: 're_03',
      email: 'a.okafor@luxuryrealty.com',
      phone: '+1 (555) 332-9011',
      avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-04-10',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 3800,
        allowances: 400,
        bonus: 600,
        taxDeductions: 720,
        netMonthly: 4080,
        currency: '$',
        paymentStatus: 'PROCESSING',
        lastPayDate: '2026-08-28',
      },
      niche: 'realestate',
    },
  ],

  restaurant: [
    {
      id: 'rest_01',
      firstName: 'Chef Marco',
      lastName: 'Pierre',
      jobTitle: 'Executive Chef & General Manager (CEO)',
      department: 'Culinary & Operations Leadership',
      level: 0,
      managerId: null,
      email: 'marco@bistroluxury.com',
      phone: '+1 (555) 771-4091',
      avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=150&auto=format&fit=crop&q=80',
      startDate: '2022-01-10',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 9800,
        allowances: 1200,
        bonus: 2500,
        taxDeductions: 2100,
        netMonthly: 11400,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'restaurant',
    },
    {
      id: 'rest_02',
      firstName: 'Antoine',
      lastName: 'Roux',
      jobTitle: 'Sous Chef (Kitchen Manager)',
      department: 'Hot Line & Prep Kitchen',
      level: 1,
      managerId: 'rest_01',
      email: 'a.roux@bistroluxury.com',
      phone: '+1 (555) 662-1180',
      avatar: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-04-12',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 6200,
        allowances: 600,
        bonus: 800,
        taxDeductions: 1100,
        netMonthly: 6500,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'restaurant',
    },
    {
      id: 'rest_03',
      firstName: 'Isabella',
      lastName: 'Conti',
      jobTitle: 'Head Floor Manager / Maître D’',
      department: 'Dining Room & Floor',
      level: 1,
      managerId: 'rest_01',
      email: 'i.conti@bistroluxury.com',
      phone: '+1 (555) 991-3829',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-08-20',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 5500,
        allowances: 500,
        bonus: 1200,
        taxDeductions: 950,
        netMonthly: 6250,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'restaurant',
    },
    {
      id: 'rest_04',
      firstName: 'Mateo',
      lastName: 'Silva',
      jobTitle: 'Senior Line Cook (Team Lead)',
      department: 'Hot Line & Prep Kitchen',
      level: 2,
      managerId: 'rest_02',
      email: 'm.silva@bistroluxury.com',
      phone: '+1 (555) 441-9988',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      startDate: '2024-06-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 3800,
        allowances: 300,
        bonus: 400,
        taxDeductions: 620,
        netMonthly: 3880,
        currency: '$',
        paymentStatus: 'PROCESSING',
        lastPayDate: '2026-08-28',
      },
      niche: 'restaurant',
    },
    {
      id: 'rest_05',
      firstName: 'Zoe',
      lastName: 'Kravitz',
      jobTitle: 'POS Cashier & Hostess Clerk',
      department: 'Dining Room & Floor',
      level: 3,
      managerId: 'rest_03',
      email: 'z.kravitz@bistroluxury.com',
      phone: '+1 (555) 123-9900',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-09-10',
      employmentType: 'Part-Time',
      salary: {
        baseMonthly: 2600,
        allowances: 200,
        bonus: 300,
        taxDeductions: 410,
        netMonthly: 2690,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'restaurant',
    },
  ],

  retail: [
    {
      id: 'ret_01',
      firstName: 'Tariq',
      lastName: 'Al-Mansoor',
      jobTitle: 'Store Owner & Operations Director (CEO)',
      department: 'Store Management',
      level: 0,
      managerId: null,
      email: 'tariq@grandmarket.com',
      phone: '+1 (555) 991-8844',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      startDate: '2021-02-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 8500,
        allowances: 1000,
        bonus: 2000,
        taxDeductions: 1700,
        netMonthly: 9800,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'retail',
    },
    {
      id: 'ret_02',
      firstName: 'Farah',
      lastName: 'Hassan',
      jobTitle: 'Inventory & Floor Manager (Manager)',
      department: 'Stock & Merchandising',
      level: 1,
      managerId: 'ret_01',
      email: 'f.hassan@grandmarket.com',
      phone: '+1 (555) 772-1133',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-07-15',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 5200,
        allowances: 500,
        bonus: 600,
        taxDeductions: 920,
        netMonthly: 5380,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'retail',
    },
    {
      id: 'ret_03',
      firstName: 'Kareem',
      lastName: 'Bakir',
      jobTitle: 'Head Cashier & Khata Ledger Clerk',
      department: 'Checkout POS Counter',
      level: 2,
      managerId: 'ret_02',
      email: 'k.bakir@grandmarket.com',
      phone: '+1 (555) 441-7788',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      startDate: '2024-03-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 3400,
        allowances: 300,
        bonus: 300,
        taxDeductions: 550,
        netMonthly: 3450,
        currency: '$',
        paymentStatus: 'PROCESSING',
        lastPayDate: '2026-08-28',
      },
      niche: 'retail',
    },
    {
      id: 'ret_04',
      firstName: 'Layla',
      lastName: 'Noor',
      jobTitle: 'Shelf Stocker & Inventory Barcode Clerk',
      department: 'Stock & Merchandising',
      level: 3,
      managerId: 'ret_02',
      email: 'l.noor@grandmarket.com',
      phone: '+1 (555) 229-8800',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-05-15',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 2800,
        allowances: 250,
        bonus: 200,
        taxDeductions: 430,
        netMonthly: 2820,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'retail',
    },
  ],

  sme: [
    {
      id: 'sme_01',
      firstName: 'David',
      lastName: 'Kessler',
      jobTitle: 'Chief Executive Officer (CEO)',
      department: 'Executive Leadership',
      level: 0,
      managerId: null,
      email: 'd.kessler@hypersaas.io',
      phone: '+1 (555) 012-9934',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-01-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 16000,
        allowances: 2000,
        bonus: 4000,
        taxDeductions: 3500,
        netMonthly: 18500,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'sme',
    },
    {
      id: 'sme_02',
      firstName: 'Samantha',
      lastName: 'Cole',
      jobTitle: 'VP of Sales & Growth (Manager)',
      department: 'Revenue & SDRs',
      level: 1,
      managerId: 'sme_01',
      email: 's.cole@hypersaas.io',
      phone: '+1 (555) 349-8812',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-06-10',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 11500,
        allowances: 1200,
        bonus: 3000,
        taxDeductions: 2400,
        netMonthly: 13300,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'sme',
    },
    {
      id: 'sme_03',
      firstName: 'Oliver',
      lastName: 'Quinn',
      jobTitle: 'Senior SDR Lead (Team Lead)',
      department: 'Revenue & SDRs',
      level: 2,
      managerId: 'sme_02',
      email: 'o.quinn@hypersaas.io',
      phone: '+1 (555) 782-9901',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      startDate: '2024-04-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 6200,
        allowances: 600,
        bonus: 1500,
        taxDeductions: 1300,
        netMonthly: 7000,
        currency: '$',
        paymentStatus: 'PROCESSING',
        lastPayDate: '2026-08-28',
      },
      niche: 'sme',
    },
    {
      id: 'sme_04',
      firstName: 'Maya',
      lastName: 'Lin',
      jobTitle: 'SDR Outbound & Lead Gen Clerk',
      department: 'Revenue & SDRs',
      level: 3,
      managerId: 'sme_03',
      email: 'm.lin@hypersaas.io',
      phone: '+1 (555) 431-7788',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-02-15',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 3800,
        allowances: 350,
        bonus: 500,
        taxDeductions: 700,
        netMonthly: 3950,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'sme',
    },
  ],

  agency: [
    {
      id: 'agn_01',
      firstName: 'Julian',
      lastName: 'Vanderbilt',
      jobTitle: 'Executive Creative Director & Partner (CEO)',
      department: 'Creative Leadership',
      level: 0,
      managerId: null,
      email: 'j.vanderbilt@agencyvanguard.com',
      phone: '+1 (555) 993-2211',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      startDate: '2022-03-01',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 14000,
        allowances: 1800,
        bonus: 3500,
        taxDeductions: 3100,
        netMonthly: 16200,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'agency',
    },
    {
      id: 'agn_02',
      firstName: 'Natasha',
      lastName: 'Romanova',
      jobTitle: 'Art Director & Brand Lead (Manager)',
      department: 'Brand Design & 3D',
      level: 1,
      managerId: 'agn_01',
      email: 'n.romanova@agencyvanguard.com',
      phone: '+1 (555) 441-8890',
      avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
      startDate: '2023-05-10',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 8500,
        allowances: 900,
        bonus: 1500,
        taxDeductions: 1750,
        netMonthly: 9150,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'agency',
    },
    {
      id: 'agn_03',
      firstName: 'Lucas',
      lastName: 'Moreau',
      jobTitle: 'Copywriter & Content Production Clerk',
      department: 'Brand Design & 3D',
      level: 3,
      managerId: 'agn_02',
      email: 'l.moreau@agencyvanguard.com',
      phone: '+1 (555) 662-7711',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      startDate: '2025-01-20',
      employmentType: 'Full-Time',
      salary: {
        baseMonthly: 3600,
        allowances: 350,
        bonus: 300,
        taxDeductions: 640,
        netMonthly: 3610,
        currency: '$',
        paymentStatus: 'PAID',
        lastPayDate: '2026-08-28',
      },
      niche: 'agency',
    },
  ],

  custom: [],
};
